### ISSUE TITLE
Add module for VTP configuration

### ISSUE THREAD

**Issue by UvixCreative** [ansible-collections/cisco.ios#1001]
##### SUMMARY

Create a module that can be used for configuring VTP

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

cisco.ios.vtp

##### ADDITIONAL INFORMATION

VLANs can be configured using the cisco.ios collection, but VTP is another well-established way of maintaining consistent VLANs across devices. Configuring VTP via Ansible could be useful for many use cases.

This can be accomplished currently with ios_commands, but that has no practical means of implementing idempotence.

I propose that the minimum implementation should enable configuring domain, mode, primary, password, and version. File, interface, pruning, and trunk could conceivably be added at a later time as I believe these to be far less common configurations.

```yaml
---
- name: VTP demo playbook
  hosts: all
  gather_facts: false

  tasks:
    - name: "Configure VTP"
      cisco.ios.vtp:
        version: 3
        domain: Demo_Domain
        password: password123
        mode: server
        primary: true
```

**Comment by jdetwiler16** [comment]
I second this! Also, if anyone is looking for the code snippet to make a VTP server as primary, here you go!

```
- name: Make Device VTP Primary 
  cisco.ios.ios_command:
    commands:
    - command: 'vtp primary'
      check_all: true
      prompt: 
        - Enter VTP Password
        - No conflicting
      answer:
        - "{{ passwd_vtp }}"
        - y
  vars:
    ansible_command_timeout: 90
```
