### ISSUE TITLE
 Network resource modules behaves inconsistently between IOS/EOS and IOS L3 interfaces doesn’t fn as expected for non-existing interfaces

### ISSUE THREAD

**Issue by termlen0** [ansible-collections/cisco.ios#101]
##### SUMMARY

Playbook tasks that use the IOS Resource modules do not print out the proposed changes when executed in check mode.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

An example would be ios_l3_interfaces. But it is not just this one module.

##### ANSIBLE VERSION

```paste below
[student1@ansible-1 ~]$ ansible --version
ansible 2.9.9
  config file = /home/student1/.ansible.cfg
  configured module search path = ['/home/student1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
[student1@ansible-1 ~]$ 
```

##### CONFIGURATION

```paste below
[student1@ansible-1 ~]$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/student1/.ansible.cfg) = ['/home/student1/lab_inventory/hosts']
DEFAULT_STDOUT_CALLBACK(/home/student1/.ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/student1/.ansible.cfg) = 60
DEPRECATION_WARNINGS(/home/student1/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/student1/.ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/student1/.ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/home/student1/.ansible.cfg) = 200
RETRY_FILES_ENABLED(/home/student1/.ansible.cfg) = False
[student1@ansible-1 ~]$ 

```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux release 8.2 (Ootpa)

##### STEPS TO REPRODUCE

```yaml
---
- name: IOS Resource module test
  hosts: rtr1
  gather_facts: no
  tags: ios
  tasks:
    - name: GATHER L3 CONFIG
      ios_facts:
        gather_subset: min
        gather_network_resources: l3_interfaces

    - name: DISPLAY INTERFACE DATA
      debug: var=ansible_network_resources

    - name: ADD LOOPBACK
      ios_l3_interfaces:
        config: 
          - name: Loopback 100
            ipv4:
              - address: 192.168.0.1/24
        state: merged        
          
        
- name: EOS Resource module test
  hosts: rtr2
  gather_facts: no
  tags: eos
  tasks:
    - name: GATHER L3 CONFIG
      eos_facts:
        gather_subset: min
        gather_network_resources: l3_interfaces

    - name: DISPLAY INTERFACE DATA
      debug: var=ansible_network_resources

    - name: ADD LOOPBACK
      eos_l3_interfaces:
        config: 
          - name: Loopback 100
            ipv4:
              - address: 192.168.0.1/24
        state: merged    
```

##### EXPECTED RESULTS

I would expect the module to behave identically for IOS vs EOS:
As you can see below, the loopback interface does not exist on the IOS device:

```
ip-172-16-157-41#sh ip int bri
Interface              IP-Address      OK? Method Status                Protocol
GigabitEthernet1       172.16.157.41   YES DHCP   up                    up      
VirtualPortGroup0      192.168.35.101  YES NVRAM  up                    up      
ip-172-16-157-41#
```

##### ACTUAL RESULTS

Only the EOS module shows proposed changes while running in check mode.

```paste below
[student1@ansible-1 ~]$ ansible-playbook resource_test.yaml --check -v
Using /home/student1/.ansible.cfg as config file

PLAY [IOS Resource module test] ******************************************************************************************************************************

TASK [GATHER L3 CONFIG] **************************************************************************************************************************************
[WARNING]: default value for `gather_subset` will be changed to `min` from `!config` v2.11 onwards
ok: [rtr1] => changed=false 
  ansible_facts:
    ansible_net_api: cliconf
    ansible_net_gather_network_resources:
    - l3_interfaces
    ansible_net_gather_subset:
    - default
    ansible_net_hostname: ip-172-16-157-41
    ansible_net_image: bootflash:packages.conf
    ansible_net_iostype: IOS-XE
    ansible_net_model: CSR1000V
    ansible_net_python_version: 3.6.8
    ansible_net_serialnum: 9YD8TTQFUJB
    ansible_net_system: ios
    ansible_net_version: 16.09.02
    ansible_network_resources:
      l3_interfaces:
      - ipv4:
        - address: dhcp
        name: GigabitEthernet1
    discovered_interpreter_python: /usr/libexec/platform-python

TASK [DISPLAY INTERFACE DATA] ********************************************************************************************************************************
ok: [rtr1] => 
  ansible_network_resources:
    l3_interfaces:
    - ipv4:
      - address: dhcp
      name: GigabitEthernet1

TASK [ADD LOOPBACK] ******************************************************************************************************************************************
ok: [rtr1] => changed=false 
  before:
  - ipv4:
    - address: dhcp
    name: GigabitEthernet1
  commands: []

PLAY [EOS Resource module test] ******************************************************************************************************************************

TASK [GATHER L3 CONFIG] **************************************************************************************************************************************
ok: [rtr2] => changed=false 
  ansible_facts:
    ansible_net_api: cliconf
    ansible_net_fqdn: rtr2
    ansible_net_gather_network_resources:
    - l3_interfaces
    ansible_net_gather_subset:
    - default
    ansible_net_hostname: rtr2
    ansible_net_image: flash:vEOS-Router.swi
    ansible_net_model: vEOS
    ansible_net_python_version: 3.6.8
    ansible_net_serialnum: 93951E4FEE89BDE6745A9293888C4D5C
    ansible_net_system: eos
    ansible_net_version: 4.22.1FX-VEOSRouter-cloud
    ansible_network_resources:
      l3_interfaces:
      - ipv4:
        - address: dhcp
        name: Ethernet1
      - ipv4:
        - address: 192.168.2.2/32
        name: Loopback0
      - ipv4:
        - address: 10.101.101.2/24
        name: Tunnel0
      - ipv4:
        - address: 10.200.200.2/24
        name: Tunnel1
    discovered_interpreter_python: /usr/libexec/platform-python

TASK [DISPLAY INTERFACE DATA] ********************************************************************************************************************************
ok: [rtr2] => 
  ansible_network_resources:
    l3_interfaces:
    - ipv4:
      - address: dhcp
      name: Ethernet1
    - ipv4:
      - address: 192.168.2.2/32
      name: Loopback0
    - ipv4:
      - address: 10.101.101.2/24
      name: Tunnel0
    - ipv4:
      - address: 10.200.200.2/24
      name: Tunnel1

TASK [ADD LOOPBACK] ******************************************************************************************************************************************
changed: [rtr2] => changed=true 
  after:
  - ipv4:
    - address: dhcp
    name: Ethernet1
  - ipv4:
    - address: 192.168.2.2/32
    name: Loopback0
  - ipv4:
    - address: 10.101.101.2/24
    name: Tunnel0
  - ipv4:
    - address: 10.200.200.2/24
    name: Tunnel1
  before:
  - ipv4:
    - address: dhcp
    name: Ethernet1
  - ipv4:
    - address: 192.168.2.2/32
    name: Loopback0
  - ipv4:
    - address: 10.101.101.2/24
    name: Tunnel0
  - ipv4:
    - address: 10.200.200.2/24
    name: Tunnel1
  commands:
  - interface Loopback100
  - ip address 192.168.0.1/24

PLAY RECAP ***************************************************************************************************************************************************
rtr1                       : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
rtr2                       : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```
