### ISSUE TITLE
cisco.ios.ios_snmp_server: subsequent runs using "state: replace" adds/removes snmp group contexts - Not Idempotent

### ISSUE THREAD

**Issue by Disco402** [ansible-collections/cisco.ios#1015]
##### SUMMARY
I need to configure the following snmp configuration on a Cisco switch.  

```
snmp-server group snmp_ro_group v3 priv read snmp_view_ro access snmp_acl
snmp-server group snmp_ro_group v3 priv context vlan- match prefix read snmp_view_ro access snmp_acl
snmp-server view snmp_view_ro iso included
```

The documentation would suggest you could do this with the following:

```
    - name: Apply the SNMPv3 views and groups
      cisco.ios.ios_snmp_server:
        config:
          views:
            - name: snmp_view_ro
              family_name: iso
              included: true
          groups:
            - group: snmp_ro_group
              version: v3
              version_option: priv
              acl_v4: snmp_acl
              read: snmp_view_ro
            - group: snmp_ro_group
              version: v3
              version_option: priv
              acl_v4: snmp_acl
              read: snmp_view_ro
              context: "vlan- match prefix"
        state: replaced
```

However each time this play is run, ansible adds and removes the snmp-server context config and is not idempotent

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`cisco.ios.ios_snmp_server`

##### ANSIBLE VERSION

```
ansible [core 2.12.10]
  config file = /home/user/ansible/network-ansible/cisco/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 22 2023, 10:22:35) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION

```
ansible-galaxy collection list cisco.ios

# /usr/lib/python3/dist-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  2.8.1

# /home/user/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  6.1.0
```

##### CONFIGURATION

```
DEFAULT_FORKS(/home/user/ansible/network-ansible/cisco/ansible.cfg) = 20
HOST_KEY_CHECKING(/home/user/ansible/network-ansible/cisco/ansible.cfg) = False
INTERPRETER_PYTHON(/home/user/ansible/network-ansible/cisco/ansible.cfg) = auto_silent
```

##### OS / ENVIRONMENT

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
```
##### STEPS TO REPRODUCE

```
--
## Configure SNMP

- name: Configure SNMP
  # 'all' is okay here, because the fail task will force the user to specify a limit on the command line, using -l or --limit
  hosts: all
  gather_facts: no
  tasks:
    - name: checking limit arg
      fail:
        msg: "you must use -l or --limit - when you really want to use all hosts, use -l 'all'"
      when: ansible_limit is not defined
      run_once: true

    - name: Apply the SNMPv3 views and groups
      cisco.ios.ios_snmp_server:
        config:
          views:
            - name: snmp_view_ro
              family_name: iso
              included: true
          groups:
            - group: snmp_ro_group
              version: v3
              version_option: priv
              acl_v4: snmp_acl
              read: snmp_view_ro
            - group: snmp_ro_group
              version: v3
              version_option: priv
              acl_v4: snmp_acl
              read: snmp_view_ro
              context: "vlan- match prefix"
        state: replaced
```

Then run with `ansible-playbook -i hosts.yml -l all snmp.yml`

##### EXPECTED RESULTS

Initial run:
```
snmp-server group snmp_ro_group v3 priv read snmp_view_ro access snmp_acl
snmp-server group snmp_ro_group v3 priv context vlan- match prefix read snmp_view_ro access snmp_acl
snmp-server view snmp_view_ro iso included
```

No changes on subsequent runs

##### ACTUAL RESULTS

On subsequent runs of this playbook Instead of having both 
```
snmp-server group snmp_ro_group v3 priv read snmp_view_ro access snmp_acl
snmp-server group snmp_ro_group v3 priv context vlan- match prefix read snmp_view_ro access snmp_acl
```

It seems to flip between adding and removing `snmp-server group snmp_ro_group v3 priv context vlan- match prefix read snmp_view_ro access snmp_acl` (Run 2 & 3)

Initial Run:
```
changed: [test] => {
    "after": {
        "groups": [
            {
                "acl_v4": "snmp_acl",
                "group": "snmp_ro_group",
                "read": "snmp_view_ro",
                "version": "v3",
                "version_option": "priv"
            },
            {
                "acl_v4": "snmp_acl",
                "context": "vlan-",
                "group": "snmp_ro_group",
                "match": "prefix",
                "read": "snmp_view_ro",
                "version": "v3",
                "version_option": "priv"
            }
        ],
        "views": [
            {
                "family_name": "iso",
                "included": true,
                "name": "snmp_view_ro"
            }
        ]
    },
    "before": {},
    "changed": true,
    "commands": [
        "snmp-server group snmp_ro_group v3 priv read snmp_view_ro access snmp_acl",
        "snmp-server group snmp_ro_group v3 priv context vlan- match prefix read snmp_view_ro access snmp_acl",
        "snmp-server view snmp_view_ro iso included"
    ],
    "invocation": {
        "module_args": {
            "config": {
                "accounting": null,
                "cache": null,
                "chassis_id": null,
                "communities": null,
                "contact": null,
                "context": null,
                "drop": null,
                "engine_id": null,
                "file_transfer": null,
                "groups": [
                    {
                        "acl_v4": "snmp_acl",
                        "acl_v6": null,
                        "context": null,
                        "group": "snmp_ro_group",
                        "match": null,
                        "notify": null,
                        "read": "snmp_view_ro",
                        "version": "v3",
                        "version_option": "priv",
                        "write": null
                    },
                    {
                        "acl_v4": "snmp_acl",
                        "acl_v6": null,
                        "context": "vlan- match prefix",
                        "group": "snmp_ro_group",
                        "match": null,
                        "notify": null,
                        "read": "snmp_view_ro",
                        "version": "v3",
                        "version_option": "priv",
                        "write": null
                    }
                ],
                "hosts": null,
                "if_index": null,
                "inform": null,
                "ip": null,
                "location": null,
                "manager": null,
                "packet_size": null,
                "password_policy": null,
                "queue_length": null,
                "source_interface": null,
                "system_shutdown": null,
                "trap_source": null,
                "trap_timeout": null,
                "traps": null,
                "users": null,
                "views": [
                    {
                        "excluded": null,
                        "family_name": "iso",
                        "included": true,
                        "name": "snmp_view_ro"
                    }
                ]
            },
            "running_config": null,
            "state": "replaced"
        }
    }
}
```

Run 2:
```
changed: [test] => {
    "after": {
        "groups": [
            {
                "acl_v4": "snmp_acl",
                "group": "snmp_ro_group",
                "read": "snmp_view_ro",
                "version": "v3",
                "version_option": "priv"
            }
        ],
        "views": [
            {
                "family_name": "iso",
                "included": true,
                "name": "snmp_view_ro"
            }
        ]
    },
    "before": {
        "groups": [
            {
                "acl_v4": "snmp_acl",
                "group": "snmp_ro_group",
                "read": "snmp_view_ro",
                "version": "v3",
                "version_option": "priv"
            },
            {
                "acl_v4": "snmp_acl",
                "context": "vlan-",
                "group": "snmp_ro_group",
                "match": "prefix",
                "read": "snmp_view_ro",
                "version": "v3",
                "version_option": "priv"
            }
        ],
        "views": [
            {
                "family_name": "iso",
                "included": true,
                "name": "snmp_view_ro"
            }
        ]
    },
    "changed": true,
    "commands": [
        "snmp-server group snmp_ro_group v3 priv context vlan- match prefix read snmp_view_ro access snmp_acl",
        "no snmp-server group snmp_ro_group v3 priv context vlan- match prefix read snmp_view_ro access snmp_acl"
    ],
    "invocation": {
        "module_args": {
            "config": {
                "accounting": null,
                "cache": null,
                "chassis_id": null,
                "communities": null,
                "contact": null,
                "context": null,
                "drop": null,
                "engine_id": null,
                "file_transfer": null,
                "groups": [
                    {
                        "acl_v4": "snmp_acl",
                        "acl_v6": null,
                        "context": null,
                        "group": "snmp_ro_group",
                        "match": null,
                        "notify": null,
                        "read": "snmp_view_ro",
                        "version": "v3",
                        "version_option": "priv",
                        "write": null
                    },
                    {
                        "acl_v4": "snmp_acl",
                        "acl_v6": null,
                        "context": "vlan- match prefix",
                        "group": "snmp_ro_group",
                        "match": null,
                        "notify": null,
                        "read": "snmp_view_ro",
                        "version": "v3",
                        "version_option": "priv",
                        "write": null
                    }
                ],
                "hosts": null,
                "if_index": null,
                "inform": null,
                "ip": null,
                "location": null,
                "manager": null,
                "packet_size": null,
                "password_policy": null,
                "queue_length": null,
                "source_interface": null,
                "system_shutdown": null,
                "trap_source": null,
                "trap_timeout": null,
                "traps": null,
                "users": null,
                "views": [
                    {
                        "excluded": null,
                        "family_name": "iso",
                        "included": true,
                        "name": "snmp_view_ro"
                    }
                ]
            },
            "running_config": null,
            "state": "replaced"
        }
    }
}
```

Run 3:
```
changed: [test] => {
    "after": {
        "groups": [
            {
                "acl_v4": "snmp_acl",
                "group": "snmp_ro_group",
                "read": "snmp_view_ro",
                "version": "v3",
                "version_option": "priv"
            },
            {
                "acl_v4": "snmp_acl",
                "context": "vlan-",
                "group": "snmp_ro_group",
                "match": "prefix",
                "read": "snmp_view_ro",
                "version": "v3",
                "version_option": "priv"
            }
        ],
        "views": [
            {
                "family_name": "iso",
                "included": true,
                "name": "snmp_view_ro"
            }
        ]
    },
    "before": {
        "groups": [
            {
                "acl_v4": "snmp_acl",
                "group": "snmp_ro_group",
                "read": "snmp_view_ro",
                "version": "v3",
                "version_option": "priv"
            }
        ],
        "views": [
            {
                "family_name": "iso",
                "included": true,
                "name": "snmp_view_ro"
            }
        ]
    },
    "changed": true,
    "commands": [
        "snmp-server group snmp_ro_group v3 priv context vlan- match prefix read snmp_view_ro access snmp_acl"
    ],
    "invocation": {
        "module_args": {
            "config": {
                "accounting": null,
                "cache": null,
                "chassis_id": null,
                "communities": null,
                "contact": null,
                "context": null,
                "drop": null,
                "engine_id": null,
                "file_transfer": null,
                "groups": [
                    {
                        "acl_v4": "snmp_acl",
                        "acl_v6": null,
                        "context": null,
                        "group": "snmp_ro_group",
                        "match": null,
                        "notify": null,
                        "read": "snmp_view_ro",
                        "version": "v3",
                        "version_option": "priv",
                        "write": null
                    },
                    {
                        "acl_v4": "snmp_acl",
                        "acl_v6": null,
                        "context": "vlan- match prefix",
                        "group": "snmp_ro_group",
                        "match": null,
                        "notify": null,
                        "read": "snmp_view_ro",
                        "version": "v3",
                        "version_option": "priv",
                        "write": null
                    }
                ],
                "hosts": null,
                "if_index": null,
                "inform": null,
                "ip": null,
                "location": null,
                "manager": null,
                "packet_size": null,
                "password_policy": null,
                "queue_length": null,
                "source_interface": null,
                "system_shutdown": null,
                "trap_source": null,
                "trap_timeout": null,
                "traps": null,
                "users": null,
                "views": [
                    {
                        "excluded": null,
                        "family_name": "iso",
                        "included": true,
                        "name": "snmp_view_ro"
                    }
                ]
            },
            "running_config": null,
            "state": "replaced"
        }
    }
}
```
Run 4 (Same as run 2) this then just flip flops between 2&3:
```
changed: [test] => {
    "after": {
        "groups": [
            {
                "acl_v4": "snmp_acl",
                "group": "snmp_ro_group",
                "read": "snmp_view_ro",
                "version": "v3",
                "version_option": "priv"
            }
        ],
        "views": [
            {
                "family_name": "iso",
                "included": true,
                "name": "snmp_view_ro"
            }
        ]
    },
    "before": {
        "groups": [
            {
                "acl_v4": "snmp_acl",
                "group": "snmp_ro_group",
                "read": "snmp_view_ro",
                "version": "v3",
                "version_option": "priv"
            },
            {
                "acl_v4": "snmp_acl",
                "context": "vlan-",
                "group": "snmp_ro_group",
                "match": "prefix",
                "read": "snmp_view_ro",
                "version": "v3",
                "version_option": "priv"
            }
        ],
        "views": [
            {
                "family_name": "iso",
                "included": true,
                "name": "snmp_view_ro"
            }
        ]
    },
    "changed": true,
    "commands": [
        "snmp-server group snmp_ro_group v3 priv context vlan- match prefix read snmp_view_ro access snmp_acl",
        "no snmp-server group snmp_ro_group v3 priv context vlan- match prefix read snmp_view_ro access snmp_acl"
    ],
    "invocation": {
        "module_args": {
            "config": {
                "accounting": null,
                "cache": null,
                "chassis_id": null,
                "communities": null,
                "contact": null,
                "context": null,
                "drop": null,
                "engine_id": null,
                "file_transfer": null,
                "groups": [
                    {
                        "acl_v4": "snmp_acl",
                        "acl_v6": null,
                        "context": null,
                        "group": "snmp_ro_group",
                        "match": null,
                        "notify": null,
                        "read": "snmp_view_ro",
                        "version": "v3",
                        "version_option": "priv",
                        "write": null
                    },
                    {
                        "acl_v4": "snmp_acl",
                        "acl_v6": null,
                        "context": "vlan- match prefix",
                        "group": "snmp_ro_group",
                        "match": null,
                        "notify": null,
                        "read": "snmp_view_ro",
                        "version": "v3",
                        "version_option": "priv",
                        "write": null
                    }
                ],
                "hosts": null,
                "if_index": null,
                "inform": null,
                "ip": null,
                "location": null,
                "manager": null,
                "packet_size": null,
                "password_policy": null,
                "queue_length": null,
                "source_interface": null,
                "system_shutdown": null,
                "trap_source": null,
                "trap_timeout": null,
                "traps": null,
                "users": null,
                "views": [
                    {
                        "excluded": null,
                        "family_name": "iso",
                        "included": true,
                        "name": "snmp_view_ro"
                    }
                ]
            },
            "running_config": null,
            "state": "replaced"
        }
    }
}
```

**Comment by roverflow** [comment]
Hi @Disco402, I noticed a problem in your playbook. You're using "vlan- match prefix" in the attribute context, which is causing the above issue. Instead, you should use the `match` attribute to fix the issue and ensure idempotency.

```yml
  - name: Apply the SNMPv3 views and groups
    cisco.ios.ios_snmp_server:
      config:
        views:
          - name: snmp_view_ro
            family_name: iso
            included: true
        groups:
          - group: snmp_ro_group
            version: v3
            version_option: priv
            acl_v4: snmp_acl
            read: snmp_view_ro
          - group: snmp_ro_group
            version: v3
            version_option: priv
            acl_v4: snmp_acl
            read: snmp_view_ro
            context: "vlan-"
            match: prefix
      state: replaced
```
