### ISSUE TITLE
What are the argument specifications for the cisco.ios.ios_vrf module and the address-family parameter

### ISSUE THREAD

**Issue by dwebr** [ansible-collections/cisco.ios#1027]
##### SUMMARY
It's unclear what the list of dicts that are passed to the address-family parament in the cisco.ios.ios_vrf module should be. 
The documentation simply states "The list of address families with MDT parameters to be configured on the remote IOS device.". 

I've tried passing parameters like the following 
```yaml

# group_vars/ variable file for a particular group
pair_vrfs:
  - name: aci
    description: aci_test_vrf
    state: present
    address_family:
      - afi: ipv4 unicast
        safi: unicast
    interfaces:
      - GigabitEthernet1/0/1
      - 
# Then reference that variable  structure in a playbook using cisco.ios.ios_vrf

- name: "PLAY 1 - MiniDC Build Lab"
  hosts: nxos ios
  gather_facts: false
  connection: network_cli

  tasks:      
    - name: Add Data Plane VRFs
      cisco.ios.ios_vrf:
        vrfs: "{{ pair_vrfs | default([]) + device_vrfs | default([])}}"
      when: ansible_network_os == 'ios' and (pair_vrfs is defined or device_vrfs is defined)
      tags: ['vrfs','vrf']      
```
But that results in a fatal error when run ...

```
PLAY [PLAY 1 - MiniDC Build Lab] ************************************************************************************************************************************************************************************************************

TASK [Add Data Plane VRFs] ******************************************************************************************************************************************************************************************************************
fatal: [SIM-DR0x]: FAILED! => {"changed": false, "module_stderr": "'mdt'", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}
```
I suspect I just don't have the arguments for the address_family parameter defined correctly since it is not defined anywhere that I could find and also not provided as an example in the documentation.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_vrf_module.html#parameter-address_family

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.0]
  config file = /opt/netadmin/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/netadmin/ve/ansible7/lib/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/netadmin/ve/ansible7/bin/ansible
  python version = 3.9.15 (main, Oct 22 2022, 11:54:42) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] (/opt/netadmin/ve/ansible7/bin/python)
  jinja version = 3.1.2
  libyaml = True

# /opt/netadmin/ve/ansible7/lib/python3.9/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  4.0.0

# /home/user/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  6.0.0

```

**Comment by roverflow** [comment]
@dwebr The list of dicts would look something like this

```yml
- afi: ipv4
  mdt:
      overlay:
          use_bgp:
              enable: true
              spt_only: true
      auto_discovery:
          vxlan:
              enable: true
              inter_as: true
      default:
          vxlan_mcast_group: 239.1.1.1
      data:
          vxlan_mcast_group: 225.2.2.0 0.0.0.255
          threshold: "112"
```
