### ISSUE TITLE
Inconsistent results from ios_facts with l2_interfaces

### ISSUE THREAD

**Issue by bile0026** [ansible-collections/cisco.ios#106]
##### SUMMARY
when using gather_network_resources: l2_interfaces, results do not appear to be structured correctly when returned and makes accessing the data difficult.  Access and trunk ports should have the same format when exported, and key should be the interface name. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_facts

##### ANSIBLE VERSION
```
ansible-playbook 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
```

##### CONFIGURATION
```
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT
Centos7

##### STEPS TO REPRODUCE
Use ios_facts with gather_network_resources: l2_interfaces

```
- name: Gather switch interface information
  cisco.ios.ios_facts:
    gather_subset:
      - '!all'
      - '!min'
    gather_network_resources:
      - l2_interfaces
  register: ios_interfaces_result
```

##### EXPECTED RESULTS
Expect consistently formatted data like example below:

```
l2_interfaces:
      - name: GigabitEthernet0/1
        mode: access
          vlan: 666
        voice:
          vlan: 10
      - name: GigabitEthernet0/2
        mode: access
          vlan: 666
      - name: GigabitEthernet0/16
        mode: trunk
        trunk:
          allowed_vlans:
          - '10'
          - '49'
          - '105'
          - '4000'
          native_vlan: 4000
```

##### ACTUAL RESULTS
```
  ansible_facts:
    ansible_net_gather_network_resources:
    - l2_interfaces
    ansible_net_gather_subset: []
    ansible_network_resources:
      l2_interfaces:
      - access:
          vlan: 666
        mode: access
        name: GigabitEthernet0/1
        voice:
          vlan: 10
      - access:
          vlan: 666
        mode: access
        name: GigabitEthernet0/2
      - access:
          vlan: 105
        mode: access
        name: GigabitEthernet0/3
      - access:
          vlan: 49
        mode: access
        name: GigabitEthernet0/4
      - access:
          vlan: 666
        mode: access
        name: GigabitEthernet0/5
      - access:
          vlan: 666
        mode: access
        name: GigabitEthernet0/6
      - access:
          vlan: 666
        mode: access
        name: GigabitEthernet0/7
      - access:
          vlan: 666
        mode: access
        name: GigabitEthernet0/8
      - access:
          vlan: 666
        mode: access
        name: GigabitEthernet0/9
      - access:
          vlan: 666
        mode: access
        name: GigabitEthernet0/10
      - access:
          vlan: 666
        mode: access
        name: GigabitEthernet0/11
      - access:
          vlan: 666
        mode: access
        name: GigabitEthernet0/12
      - access:
          vlan: 666
        mode: access
        name: GigabitEthernet0/13
      - access:
          vlan: 100
        mode: access
        name: GigabitEthernet0/14
      - access:
          vlan: 666
        mode: access
        name: GigabitEthernet0/15
      - mode: trunk
        name: GigabitEthernet0/16
        trunk:
          allowed_vlans:
          - '10'
          - '49'
          - '105'
          - '4000'
          native_vlan: 4000
```
