### ISSUE TITLE
cisco.ios.ios_snmp_server module is NOT applying commands correctly, so causing errors.

### ISSUE THREAD

**Issue by JuanBH255** [ansible-collections/cisco.ios#1071]
##### SUMMARY

cisco.ios.ios_snmp_server module is NOT applying commands correctly, so causing errors.
The correct way this command should be applied is:
snmp-server host 10.1.1.1 vrf Mgmt-intf version 3 priv test_user

But every time I run the playbook it tries to run the command like this instead:
snmp-server host 10.1.1.1 version 3 priv vrf Mgmt-intf test_user
                                              ^
% Invalid input detected at '^' marker.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_snmp_server

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.6]
```

##### COLLECTION VERSION

```paste below
cisco.ios  5.3.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /projects/dmz_configuration_automation/ansible.cfg
DEFAULT_GATHERING(/projects/dmz_configuration_automation/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/projects/dmz_configuration_automation/ansible.cfg) = ['/projects/dmz_configuration_automation/inv.yml']
DEFAULT_STDOUT_CALLBACK(/projects/dmz_configuration_automation/ansible.cfg) = debug
DISPLAY_SKIPPED_HOSTS(/projects/dmz_configuration_automation/ansible.cfg) = False
HOST_KEY_CHECKING(/projects/dmz_configuration_automation/ansible.cfg) = False
RETRY_FILES_ENABLED(/projects/dmz_configuration_automation/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Cisco C8500-12X
Cisco IOS XE Software, Version 17.03.04a

##### STEPS TO REPRODUCE

```yaml
    - name: SNMP
      cisco.ios.ios_snmp_server:
        config:
          groups:
            - group: test_group_name
              version: v3
              version_option: auth
              read: v3read
              acl_v4: snmpv3-acl
            - group: test_group_name_two
              version: v3
              version_option: auth
              read: v3read
              write: v3write
              acl_v4: snmpv3-acl
          hosts:
            - host: 10.1.1.1
              version: 3
              vrf: Mgmt-intf
              version_option: priv
              community_string: test_user
          users:
            - group: test_group_name
              username: test_user
              version: v3
              authentication:
                algorithm: sha
                password: test_password
              encryption:
                priv: aes
                priv_option: 128
                password: test_password
        state: merged
      tags: snmp
```

##### EXPECTED RESULTS

Either No change: 
ok=1    changed=0

Or a change:
ok=0    changed=1

##### ACTUAL RESULTS

```paste below
TASK [SNMP] ***************************************************************************************************************************************************************************************************************************************************************************************************************************task path: /projects/dmz_configuration_automation/test/test.yml:26
fatal: [npdzart03]: FAILED! => {
    "changed": false
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

snmp-server host 10.1.1.1 version 3 priv vrf Mgmt-intf test_user
snmp-server host 10.1.1.1 version 3 priv vrf Mgmt-intf test_user
                                              ^
% Invalid input detected at '^' marker.

npdzart03(config)#

PLAY RECAP ****************************************************************************************************************************************************************************************************************************************************************************************************************************npdzart03                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
![2024-05-10_08-57-52](https://github.com/ansible-collections/cisco.ios/assets/90996024/86a54255-0432-48b6-9505-e4f9ba838df0)

```
