### ISSUE TITLE
Breaking Change with ansible.netcomm v6.1.3

### ISSUE THREAD

**Issue by comete-geek** [ansible-collections/cisco.ios#1088]
Same problem as reported here: https://github.com/ansible-collections/cisco.ios/issues/1079 but with cisco.ios.ios_service. A downgrade to 6.1.1 resolve the issue.

``` yaml
- name: Configure services
  cisco.ios.ios_service:
    config:
      timestamps:
        - msg: debug
          enable: true
          timestamp: uptime
        - msg: log
          enable: true
          timestamp: uptime
      pad: false
      password_encryption: true
```

```
fatal: [switch.test]: FAILED! => {"changed": false, "module_stderr": "Cliconf.edit_config() got an unexpected keyword argument 'err_responses'", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}
```

thanks for your help !

_Originally posted by @comete-geek in https://github.com/ansible-collections/cisco.ios/issues/1079#issuecomment-2174384789_
