### ISSUE TITLE
Unable to Merge a vlan to a Trunk Port

### ISSUE THREAD

**Issue by Kniickk** [ansible-collections/cisco.ios#1090]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_l2_interfaces

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below
ansible [core 2.15.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.11.5 (main, Oct 25 2023, 16:19:59) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 60

```

##### OS / ENVIRONMENT

OS: Rocky Linux 8 
Device: Cisco 3850 
IOS Version: 16.12.11

##### STEPS TO REPRODUCE

I created a Port-channel on the Switch, the Port-Channel should be a trunk Port with a VLAN 10.
After that i want to add the VLAN 15 on the same Trunk Port, but the config will be overridden, not merged.

```yaml
---
- name: adding_new_vlan
  hosts: Distribution_Switche
  vars_files:
    - /etc/ansible/vault/VAULT_FILE.yaml

  tasks:
  - name: Adding VLAN to Switch
    cisco.ios.ios_vlans:
      config:
        - name: VLAN0015
          vlan_id: 15
          state: active

  - name: Adding VLAN to Port-Channel ABM
    cisco.ios.ios_l2_interfaces:
      config:
       - name: Port-Channel30
         mode: trunk
         trunk: 
           allowed_vlans: 10
      state: merged
```

##### EXPECTED RESULTS

I was expecting that the playbook adds the VLAN to the already created via the "switchport trunk allowed vlan add" command.

##### ACTUAL RESULTS

But the VLAN config is always replaced with the VLANs i write in the "allowed_vlans:" part.

```paste below

```
