### ISSUE TITLE
ACL Sequence Numbers Missing in Rendered Config

### ISSUE THREAD

**Issue by David00** [ansible-collections/cisco.ios#1108]
##### SUMMARY
When building a playbook to deploy an ACL, the resulting rendered configuration is missing sequence numbers, even though sequence numbers are defined in the play.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
> cisco.ios version 8.0.0

##### ANSIBLE VERSION
```
ansible [core 2.17.1]
  config file = /home/david/ansible/ansible.cfg
  configured module search path = ['/home/david/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/david/venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/david/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/david/venv/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/home/david/venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True

```

##### COLLECTION VERSION

```
ansible-galaxy collection list cisco.ios

# /home/david/venv/lib/python3.10/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  8.0.0  

```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
CONFIG_FILE() = /home/david/ansible/ansible.cfg
HOST_KEY_CHECKING(/home/david/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Target OS is a Cisco Catalyst 9300-48UN running IOS 17.6.5.

##### STEPS TO REPRODUCE
Run the following playbook against a Cisco Catalyst 9300 switch:

```yaml
---

- name: Test deployment of ACL on Cisco Catalyst Switch
  hosts: test_catalyst
  remote_user: david
  vars:
    ACL_VERSION: v1.0.0
    ACL_DATE: Aug 15 - 2024  

  tasks:
  - name: Configure Test ACL
    vars: 
      ansible_command_timeout: 60
    register: output
    cisco.ios.ios_acls:
      # state: replaced
      state: rendered
      config:  
        - afi: ipv4  # Address Family
          acls:
            - name: Ansible-Test
              acl_type: standard
              aces: # Access Control Entries
                - remarks: 'Test statement 1'
                - sequence: 10
                - grant: permit   # Either permit or deny
                  source: 
                    address: 10.231.115.0
                    wildcard_bits: 0.0.0.255

                - remarks: 'Test statement 2'
                - sequence: 20
                - grant: permit
                  source:
                    address: 10.221.15.0
                    wildcard_bits: 0.0.0.255
                
                - remarks: 'Test statement 3'
                - sequence: 35
                - grant: permit
                  source:
                    host: 10.221.33.210

                - remarks: 'Log all attempts'
                - sequence: 999
                - grant: deny
                  source: 
                    any: true
                  log:
                    set: true


  - name: Print Rendered Config
    ansible.builtin.debug:
      msg: 
        - "{{ output.rendered }}"

```

##### EXPECTED RESULTS
I would expect to see the specific ACL creation commands **with** sequence numbers, as configured, like this: 

```
ip access-list standard Ansible-Test
  10 remark Test statement 1
  10 permit 10.231.115.0 0.0.0.255
  20 remark Test statement 2
  20 permit 10.221.15.0 0.0.0.255
  35 remark Test statement 3
  35 permit host 10.221.33.210
  999 remark Test statement 24
  999 deny any log
```

##### ACTUAL RESULTS

```
TASK [Print Rendered Config] *****************************************************************************************************************************************
ok: [10.0.0.10] => {
    "msg": [
        [
            "ip access-list standard Ansible-Test",
            "remark Test statement 1",
            "permit 10.231.115.0 0.0.0.255",
            "remark Test statement 2",
            "permit 10.221.15.0 0.0.0.255",
            "remark Test statement 3",
            "permit host 10.221.33.210",
            "remark Log all attempts",
            "deny any log"
        ]
    ]
}

```

When changing `state: ` to `replaced`  to actually deploy this to the switch, the switch of course creates its own sequence numbers because none were provided to it, and the ACL configuration ends up looking like:

```
Cat9300# show run | sec Ansible
ip access-list standard Ansible-Test
 10 remark Test statement 1
 10 permit 10.231.115.0 0.0.0.255
 20 remark Test statement 2
 20 permit 10.221.15.0 0.0.0.255
 30 remark Test statement 3
 30 permit 10.221.33.210
 40 remark Log all attempts
 40 deny   any log
```

**Comment by David00** [comment]
I've figured this out after studying the ACL examples more closely. It looks like this was due to me not fully grasping the YAML syntax and the list/dictionary relationship for the values in the ACL module configuration syntax.

Removing the new list definitions and making sure each ACL entry was a part of the same list fixed the issue. Here is the corrected play:

```yaml

  tasks:
  - name: Configure Test ACL
    vars: 
      ansible_command_timeout: 60
    register: output
    cisco.ios.ios_acls:
      # state: replaced
      state: rendered
      config:  
        - afi: ipv4  # Address Family
          acls:
            - name: Ansible-Test
              acl_type: standard
              aces: # Access Control Entries
                - sequence: 10 
                  remarks: 'Test statement 1'
                  grant: permit   # Either permit or deny
                  source: 
                    address: 10.231.115.0
                    wildcard_bits: 0.0.0.255

                - sequence: 20
                  remarks: 'Test statement 2'
                  grant: permit
                  source:
                    address: 10.221.15.0
                    wildcard_bits: 0.0.0.255
                
                - sequence: 35
                  remarks: 'Test statement 3'
                  grant: permit
                  source:
                    host: 10.221.33.210

                - sequence: 999
                  remarks: 'Log all attempts'
                  grant: deny
                  source: 
                    any: true
                  log:
                    set: true
```
