### ISSUE TITLE
Idempotence issue in ios_logging with host and facility

### ISSUE THREAD

**Issue by FloLaco** [ansible-collections/cisco.ios#111]
##### SUMMARY
If we want to add an host and set the facility, the idempotence is not working

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`ios_logging` module

##### ANSIBLE VERSION

```
ansible 2.9.10
  config file = /home/florian/logm/ansible-test/ansible.cfg
  configured module search path = ['/home/florian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/florian/.pyenv/versions/3.8.3/envs/ansible/lib/python3.8/site-packages/ansible
  executable location = /home/florian/.pyenv/versions/ansible/bin/ansible
  python version = 3.8.3 (default, Jun  5 2020, 11:41:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```
HOST_KEY_CHECKING(/home/user/logm/ansible-test/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
Switch Ports Model              SW Version            SW Image                 
------ ----- -----              ----------            ----------               
*    1 26    WS-C2960+24TC-L    15.0(2)SE6            C2960-LANBASEK9-M        
```

##### STEPS TO REPRODUCE

```yaml
$ cat configure_logging.yaml
---
- name: Get logging facts
  hosts: switch
  gather_facts: no
  tasks:

  - name: Configure logging
    ios_logging:
      dest: host
      name: 10.55.240.143
      facility: local6
      state: present
    register: output

  - name: Configure trap logging
    ios_logging:
      dest: trap
      level: notifications
      state: present
    register: output2

  - name: Show output
    debug: var=output

  - name: Show output
    debug: var=output2
```

##### EXPECTED RESULTS

Should not have any change after the first execution. Here is a example where we are running twice the same playbook.

##### ACTUAL RESULTS

```paste below
$ ansible-playbook -i hosts configure_logging.yaml -k 
SSH password: 

PLAY [Get logging facts] ****************************************************************************************************************************************************************************************************************

TASK [Configure logging] ****************************************************************************************************************************************************************************************************************
changed: [TB_BHD]

TASK [Configure trap logging] ***********************************************************************************************************************************************************************************************************
ok: [TB_BHD]

TASK [Show output] **********************************************************************************************************************************************************************************************************************
ok: [TB_BHD] => {
    "output": {
        "ansible_facts": {
            "discovered_interpreter_python": "/usr/bin/python"
        },
        "changed": true,
        "commands": [
            "logging facility local6",
            "logging host 10.55.240.143"
        ],
        "failed": false
    }
}

TASK [Show output] **********************************************************************************************************************************************************************************************************************
ok: [TB_BHD] => {
    "output2": {
        "changed": false,
        "commands": [],
        "failed": false
    }
}

PLAY RECAP ******************************************************************************************************************************************************************************************************************************
TB_BHD                     : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  





# second execution
$ ansible-playbook -i hosts configure_logging.yaml -k -C
SSH password: 

PLAY [Get logging facts] ****************************************************************************************************************************************************************************************************************

TASK [Configure logging] ****************************************************************************************************************************************************************************************************************
changed: [TB_BHD]

TASK [Configure trap logging] ***********************************************************************************************************************************************************************************************************
ok: [TB_BHD]

TASK [Show output] **********************************************************************************************************************************************************************************************************************
ok: [TB_BHD] => {
    "output": {
        "ansible_facts": {
            "discovered_interpreter_python": "/usr/bin/python"
        },
        "changed": true,
        "commands": [
            "logging host 10.55.240.143"
        ],
        "failed": false
    }
}

TASK [Show output] **********************************************************************************************************************************************************************************************************************
ok: [TB_BHD] => {
    "output2": {
        "changed": false,
        "commands": [],
        "failed": false
    }
}

PLAY RECAP ******************************************************************************************************************************************************************************************************************************
TB_BHD                     : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by KB-perByte** [comment]
Hi @FloLaco, as you see on the second execution of the same playbook the command is being executed is only for the ios host not for facility configuration, rather than putting all the configuration in a single task it is recommended to use _aggregate_ parameter instead when there are multiple commands involved

Doing the same task "_Configure logging_" using aggregate should solve the idempotency issue here,

```
- name: Configure logging
    ios_logging:
      aggregate:
        - { "dest": "host", "name": "10.55.240.143" }
        - { "facility": "local7" }
      state: present
    register: output
```
