### ISSUE TITLE
ios_vlans module: Incorrect command generated with state:purged ("no vlan configuration" instead of "no vlan") and MTU error with state:deleted on Cat9k

### ISSUE THREAD

**Issue by Girish5tri** [ansible-collections/cisco.ios#1143]
## Description:

When using cisco.ios.ios_vlans module with **_state:purged_** on Cisco Catalyst 9000 switch, the module generates incorrect command syntax("no vlan configuration 812" instead of "no vlan 812") and with **_state:deleted_** it fails with MTU error.

None of the methods I'd expect to delete a VLAN actually delete it from the switch. Using state:purged generates incorrect command and state:deleted fails with MTU error on Cat9k.

## Device Information:
- Platform: Cisco Catalyst 9000 (Cat9k)
- Software: IOS-XE 17.x

## ISSUE TYPE
Bug Report

## COMPONENT NAME
cisco.ios.ios_vlans

## ANSIBLE VERSION

```
ansible [core 2.18.0]
  config file = /home/hgirish/ospfv2_fix/ansible.cfg
  configured module search path = ['/home/hgirish/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/hgirish/virtualenv/ios_acl/lib64/python3.11/site-packages/ansible
  ansible collection location = /home/hgirish/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/hgirish/virtualenv/ios_acl/bin/ansible
  python version = 3.11.9 (main, Apr 17 2024, 00:00:00) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)] (/home/hgirish/virtualenv/ios_acl/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

## Steps to Reproduce:

1. First, create VLAN 812 without mtu:

```
- name: Configure VLAN 812 on Cisco Cat9K
  hosts: ios
  gather_facts: false
  tasks:
    - name: Create VLAN
      cisco.ios.ios_vlans:
        config:
          - vlan_id: 812
            name: TEST-VLAN-812
            state: active
        state: merged
```
Note: MTU is not explicitly configured in the VLAN creation as cat9k doesn't support direct MTU configuration in VLAN configuration mode. Default MTU of 1500 is automatically applied.

2. Try to delete with state:purged:

```
- name: Delete VLAN
  hosts: ios
  gather_facts: false
  tasks:
    - name: Delete VLAN
      cisco.ios.ios_vlans:
        config:
          - vlan_id: 812
        state: purged
```

3. Try to delete with state:deleted:

```
- name: Delete VLAN
  hosts: ios
  gather_facts: false
  tasks:
    - name: Delete VLAN
      cisco.ios.ios_vlans:
        config:
          - vlan_id: 812
        state: deleted
```

### EXPECTED RESULTS

2. state: purged should generate "no vlan 812" command and remove the VLAN
3. state: deleted should delete the VLAN along with its configuration such as name, state, mtu of the VLAN

### ACTUAL RESULTS

2. With state:purged (check mode output):

```
"changed": true,
"commands": [
    "no vlan configuration 812"
]

```

Its generating " no vlan configuration 812". This command neither removes the VLAN nor its configuration.

3. With state:deleted:

```
fatal: [54.190.208.146]: FAILED! => {
    "changed": false,
    "module_stderr": "no mtu 1500\r\nno mtu 1500\r\n    ^\r\n% Invalid input detected at '^' marker.\r\n\r\ncat9k(config-vlan)#",
    "module_stdout": "",
    "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error"
}
```
state: deleted fails with MTU configuration error 

## Manual CLI Testing on Cat9K:

1. Initial state (VLAN 812 exists):

```
cat9k#show vlan brief
VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
812  VLAN0812                         active    

```

2. Testing "no vlan configuration 812" (command used by module with state:purged):

```
cat9k#conf t
cat9k(config)#no vlan configuration 812
cat9k(config)#end
cat9k#show vlan 
VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
812  VLAN0812                         active    
```
Result: VLAN 812 still exists - command doesn't remove the VLAN 

3. Testing "no vlan 812" (correct command):

```
cat9k#conf t
cat9k(config)#no vlan 812
cat9k(config)#end
cat9k#show vlan brief
VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------

```

[VLAN 812 no longer appears in output]

Result: VLAN 812 successfully removed
