### ISSUE TITLE
Create User with Type 8 encryption with Plain text password.

### ISSUE THREAD

**Issue by Andyjb8** [ansible-collections/cisco.ios#1166]
##### SUMMARY
The ios_user module does not support creating a local user with type 8 encryption when providing a plaintext password.
It also does not support creating a user with a hashed password in my testing. However I would prefer support for configuring with a plaintext password as the process creating a cisco supported hashed password is unclear to me. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_user

##### ANSIBLE VERSION

```
ansible --version
ansible [core 2.15.12]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.18 (main, May 16 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION
```
ansible-galaxy collection list

# /usr/share/ansible/collections/ansible_collections
Collection            Version
--------------------- -------
cisco.ios             9.1.1  

```

##### CONFIGURATION

```
ansible-config dump --only-changed
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT
Target node, cisco CSR1000V Version 17.3.4a

##### STEPS TO REPRODUCE

The only way I am seeing to specify a type 8 password in the documentation is to provide a hashed password. I tested with a plain text password and it  did not work as it requires a hashed value.
```
      cisco.ios.ios_user:
        name: "{{ username }}"
        privilege: 15
        hashed_password:
          type: 8
          value: "{{ plaintex_password}}"
        update_password: always
        state: present

```

I tried using a hashed value from a temp user created to get my has value and that did not work either.

```
  - name: Create temporary user with type 8 encryption
      cisco.ios.ios_config:
        lines:
          - username temp_user algorithm-type sha256 secret {{ random_password }}

    - name: Get running config for temporary user
      cisco.ios.ios_command:
        commands:
          - show running-config | include username temp_user
        wait_for:
          - result[0] contains "username temp_user"
      register: hash_output

    - name: Extract hashed password
      set_fact:
        type8_hash: "{{ hash_output.stdout[0] | regex_search('secret 8 (.*)', '\\1') }}"
        
    - name: Set local user on Cisco IOS with type 8 encryption
      cisco.ios.ios_user:
        name: "{{ username }}"
        privilege: 15
        hashed_password:
          type: 8
          value: "{{ type8_hash }}"
        update_password: always
        state: present
```

here is the output I got with the above playbook that extracts a type 8 hash from a temp user and attempts to config a new user with that hashed value. It doesn't work either

```
TASK [Create temporary user with type 8 encryption] ****************************
task path: /home/admin/automation/playbooks/Config_Standards/local_account_compliance.yml:44
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
[WARNING]: To ensure idempotency and correct diff the input configuration lines
should be similar to how they appear if present in the running configuration on
device
changed: [rtr-01] => {
    "banners": {},
    "changed": true,
    "commands": [
        "username temp_user algorithm-type sha256 secret 3t0\"vx-t;D;1"
    ],
    "invocation": {
        "module_args": {
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "defaults": false,
            "diff_against": null,
            "diff_ignore_lines": null,
            "intended_config": null,
            "lines": [
                "username temp_user algorithm-type sha256 secret 3t0\"vx-t;D;1"
            ],
            "match": "line",
            "multiline_delimiter": "@",
            "parents": null,
            "replace": "line",
            "running_config": null,
            "save_when": "never",
            "src": null
        }
    },
    "updates": [
        "username temp_user algorithm-type sha256 secret 3t0\"vx-t;D;1"
    ]
}

TASK [Get running config for temporary user] ***********************************
task path: /home/admin/automation/playbooks/Config_Standards/local_account_compliance.yml:49
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
ok: [rtr-01] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "show running-config | include username temp_user"
            ],
            "interval": 1,
            "match": "all",
            "retries": 9,
            "wait_for": [
                "result[0] contains \"username temp_user\""
            ]
        }
    },
    "stdout": [
        "username temp_user secret 8 $8$oM.x6z9wip4r9k$o5VZff2kaOhNYCEKW7u7jSs5CsrpykoOHcL1Ihte.Ck"
    ],
    "stdout_lines": [
        [
            "username temp_user secret 8 $8$oM.x6z9wip4r9k$o5VZff2kaOhNYCEKW7u7jSs5CsrpykoOHcL1Ihte.Ck"
        ]
    ]
}

TASK [Extract hashed password] *************************************************
task path: /home/admin/automation/playbooks/Config_Standards/local_account_compliance.yml:57
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
ok: [rtr-01] => {
    "ansible_facts": {
        "type8_hash": [
            "$8$oM.x6z9wip4r9k$o5VZff2kaOhNYCEKW7u7jSs5CsrpykoOHcL1Ihte.Ck"
        ]
    },
    "changed": false
}
TASK [Set local user on Cisco IOS with type 8 encryption] **********************
task path: /home/admin/automation/playbooks/Config_Standards/local_account_compliance.yml:69
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
The full traceback is:
  File "/usr/share/ansible/collections/ansible_collections/cisco/ios/plugins/module_utils/network/ios/ios.py", line 114, in load_config
    resp = connection.edit_config(commands)
  File "/usr/lib/python3.9/site-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [rtr-01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "aggregate": null,
            "configured_password": null,
            "hashed_password": {
                "type": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "value": "['$********$oM.x6z9wip4r9k$o5VZff2kaOhNYCEKW7u7jSs5CsrpykoOHcL1Ihte.Ck']"
            },
            "name": "myuser ",
            "nopassword": null,
            "password_type": "secret",
            "privilege": 15,
            "purge": false,
            "sshkey": null,
            "state": "present",
            "update_password": "always",
            "view": null
        }
    },
    "msg": "username myuser secret ******** ['$********$oM.x6z9wip4r9k$o5VZff2kaOhNYCEKW7u7jSs5CsrpykoOHcL1Ihte.Ck']\r\nERROR: The secret you entered is not a valid encrypted secret.\r\nTo enter an UNENCRYPTED secret, do not specify type ******** encryption.\r\nWhen you properly enter an UNENCRYPTED secret, it will be encrypted.\r\n\r\nrtr-01(config)#"
}
```

Using the configured password option for plain text password does not allow setting type 8

```

      - name: Set local user on Cisco IOS
        cisco.ios.ios_user:
          name: "{{ username }}"
          privilege: 15
          configured_password: "{{ random_password }}"
          password_type: 8
          update_password: always
          state: present

```

Clearly this is not supported

```
fatal: [rtr-01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "aggregate": null,
            "configured_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "hashed_password": null,
            "name": "chadm",
            "nopassword": null,
            "password_type": "8",
            "privilege": 15,
            "purge": false,
            "sshkey": null,
            "state": "present",
            "update_password": "always",
            "view": null
        }
    },
    "msg": "value of password_type must be one of: secret, password, got: 8"
}

```

##### EXPECTED RESULTS

I would expect this module to be able to support configuring the user with a plain text password using type 8 encryption. 

Creating a user with a type 8 hash password appears to be supported but it did not work either. If it must be configured with a hashed_password, a method of hashing the password so it is supported on cisco IOS should be provided so I don't have to create a temp user.

Using the ios_config module this works, so I know my device supports type 8 passwords. However this solution is not idempotent.
`
    - name: Create User
      cisco.ios.ios_config:
        lines:
          - username {{ username }} algorithm-type sha256 secret {{ random_password }}

`
##### ACTUAL RESULTS

The ios_user module does not allow configuring users with type 8 with either plain text password or hashed password.
