### ISSUE TITLE
ios_command promt times out. | Cisco ASR920 software update

### ISSUE THREAD

**Issue by martinvenes** [ansible-collections/cisco.ios#1167]
##### SUMMARY

When upgrading Cisco ASR920 switches, you can remove all old system files with the command:  "request platform software package clean file bootflash:" it will then promt you for deleting the old files, and you have to answer with "y".

When i run my ansible playbook, the playbook times out. I takes about 1-2 minutes for the router to list the files to delete. I have tried setting the timeout to 10 minutes, but without any luck.

Below is an cutout from the routers shell when executing the command manually.

router#request platform software package clean file bootflash:
This operation may take several minutes...
  Cleaning up unnecessary package files
    Scanning boot directory for packages ... done.
    Preparing packages list to delete ...
    done.

Files that will be deleted:
    asr920-espbase.17.09.06.SPA.pkg
    asr920-rpaccess.17.09.06.SPA.pkg
    asr920-rpbase.17.09.06.SPA.pkg
    asr920-rpboot.17.09.06.SPA.pkg
    asr920-rpcontrol.17.09.06.SPA.pkg
    asr920-rpios-universalk9_npe.17.09.06.SPA.pkg
    asr920-sipbase.17.09.06.SPA.pkg
    asr920-sipspa.17.09.06.SPA.pkg
    packages.conf

Do you want to proceed? [y/n]y
    Deleting file bootflash:asr920-espbase.17.09.06.SPA.pkg ... done.
    Deleting file bootflash:asr920-rpaccess.17.09.06.SPA.pkg ... done.
    Deleting file bootflash:asr920-rpbase.17.09.06.SPA.pkg ... done.
    Deleting file bootflash:asr920-rpboot.17.09.06.SPA.pkg ... done.
    Deleting file bootflash:asr920-rpcontrol.17.09.06.SPA.pkg ... done.
    Deleting file bootflash:asr920-rpios-universalk9_npe.17.09.06.SPA.pkg ... done.
    Deleting file bootflash:asr920-sipbase.17.09.06.SPA.pkg ... done.
    Deleting file bootflash:asr920-sipspa.17.09.06.SPA.pkg ... done.
    Deleting file bootflash:packages.conf ... done.
  SUCCESS: Files deleted.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios.command

##### ANSIBLE VERSION

```paste below
ansible 2.10.17
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/martin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Dec  1 2024, 12:12:57) [GCC 10.2.1 20210110]

```

##### COLLECTION VERSION

```paste below
cisco.ios

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

cisco ios 16.9.5/17.09.6

##### STEPS TO REPRODUCE

```yaml
-  hosts: asr920
   gather_facts: no
   connection: network_cli

   vars:
    ansible_command_timeout: 2000
    ftp_path: "files/cisco/asr/920/current/"
    ios_file: "asr920-universalk9_npe.17.06.05.SPA.bin"

   tasks:

   
    - name: Clean up unused software packages in bootflash
      cisco.ios.ios_command:
        commands:
          - command: "request platform software package clean file bootflash:"
            prompt: "Do you want to proceed? \\[y/n\\]"
            answer: "y"



```

##### ACTUAL RESULTS

```paste below

```
