### ISSUE TITLE
dynamic bgp neighbor

### ISSUE THREAD

**Issue by altair74** [ansible-collections/cisco.ios#1173]
##### SUMMARY

When applying the bgp_global peer_group the module applies:
neighbor tag peer-group some-peer-group-name
however, when applying peer-groups the router is expecting:
neighbor some-peer-group peer-group

trying to apply the peer-group name to the end of the command results in the role failing to apply.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

bgp_global -> neighbors -> neighbor_address -> peer_group
##### ANSIBLE VERSION

```paste below
"ansible [core 2.17.9]
  config file = /home/cisco/ansible/ansible.cfg
  configured module search path = ['/home/cisco/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/cisco/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True"
```

##### COLLECTION VERSION

```paste below
"
# /home/cisco/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  9.1.2"
```

##### CONFIGURATION

```paste below
"CACHE_PLUGIN(/home/cisco/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/cisco/ansible/ansible.cfg) = /tmp/facts_cache
CACHE_PLUGIN_TIMEOUT(/home/cisco/ansible/ansible.cfg) = 7200
CONFIG_FILE() = /home/cisco/ansible/ansible.cfg
DEFAULT_BECOME(/home/cisco/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/home/cisco/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/cisco/ansible/ansible.cfg) = root
DEFAULT_GATHERING(/home/cisco/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/cisco/ansible/ansible.cfg) = ['/home/cisco/ansible/inventory']
DEFAULT_ROLES_PATH(/home/cisco/ansible/ansible.cfg) = ['/home/cisco/ansible/roles']
HOST_KEY_CHECKING(/home/cisco/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/cisco/ansible/ansible.cfg) = False"
```

##### OS / ENVIRONMENT

router= catalyst 8kv 
Cisco IOS XE Software, Version 17.13.01a
Cisco IOS Software [IOSXE], Virtual XE Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 17.13.1a, RELEASE SOFTWARE (fc3)

License Level: network-advantage
License Type: Perpetual
Next reload license Level: network-advantage

Addon License Level: dna-advantage
Addon License Type: Subscription
Next reload addon license Level: dna-advantage

##### STEPS TO REPRODUCE

setup a bgp listen range with some peer-group and and attempt to apply the neighbor tasks to associate the peer group to the neighbor

```yaml
"- name: Configure BGP global settings on hub devices
  cisco.ios.ios_bgp_global:
    config:
      as_number: "{{ bgp_as }}"
      bgp:
        log_neighbor_changes: "{{ bgp_log_neighbor_changes }}"
        listen:
          range:
            host_with_subnet: "{{ bgp_listen_range }}"
            peer_group: "{{ bgp_peer_group }}"
      networks: #"{{ bgp_networks }}"
        - address: 0.0.0.0
          #- netmask: 0.0.0.0
      neighbors:
        - activate: true
          peer_group: dmvpn_spokes
          remote_as: 65023
          neighbor_address: dmvpn_spokes
    state: merged
  when: "'hub' in group_names""
```

##### EXPECTED RESULTS

router bgp 65001
 bgp log-neighbor-changes
 bgp listen range 172.16.0.0/20 peer-group dmvpn_spokes
 neighbor dmvpn_spokes peer-group
 neighbor dmvpn_spokes remote-as 65023

##### ACTUAL RESULTS

fatal: [cat8kv-1]: FAILED! => {"changed": false, "module_stderr": "neighbor tag1 peer-group dmvpn_spokes\r\nneighbor tag1 peer-group dmvpn_spokes\r\n

```paste below

```
