### ISSUE TITLE
Allow empty lines in ios_banner module

### ISSUE THREAD

**Issue by ZachHoiberg** [ansible-collections/cisco.ios#1178]
##### SUMMARY
Allow leading empty lines (simply \n in a string) to be processed in the banner.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ios_banner

##### ADDITIONAL INFORMATION
Sometimes when formatting ASCII art banners, empty lines are needed for clean spacing and formatting. Currently, I cannot pass a newline character as the first character in the ios_banner module without it being stripped as empty and left out from the banner.

```
  - name: Create the lists
      set_fact: 
        banner: |+
          
              _   _   _                                             _   _   _
             | |_| |_| |          Network Test              | |_| |_| |

    - name: Setting Banner
      ios_banner:
        banner: login
        text: "{{banner}}"

  - name: Create the lists
      set_fact: 
        banner: |+
          f 
              _   _   _                                             _   _   _
             | |_| |_| |          Network Test              | |_| |_| |

    - name: Setting Banner
      ios_banner:
        banner: login
        text: "{{banner[1:]}}"

```

1st result is no preceding newline character
2nd result is preceding newline character but ugly empty space character after the trimmed f
