### ISSUE TITLE
Bug Report: cisco.ios.ios_bgp_address_family Idempotency Issues with state: merged / replaced / overridden

### ISSUE THREAD

**Issue by yanivr78** [ansible-collections/cisco.ios#1190]
##### SUMMARY
The cisco.ios.ios_bgp_address_family module exhibits idempotency issues when using state: replaced. The module repeatedly applies configuration changes even when the current state matches the desired state. This behavior leads to unnecessary reconfiguration and potential disruption in production environments.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_bgp_address_family

##### ANSIBLE VERSION
ansible [core 2.15.0]
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.8/site-packages/ansible
python version = 3.8.10
jinja version = 3.1.2
libyaml = True

##### COLLECTION VERSION
cisco.ios 4.2.0

##### CONFIGURATION
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

```

##### OS / ENVIRONMENT
Target Device: Cisco Catalyst 9300
IOS Version: 17.3.3
Control Node OS: Ubuntu 22.04


##### STEPS TO REPRODUCE
1. Use the cisco.ios.ios_bgp_address_family module to configure a BGP neighbor and networks.
2. Run the playbook multiple times with the same configuration.
3. Observe that the module repeatedly applies configuration changes even when the current state matches the desired state.

---
- hosts: group1
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: "ios"

  tasks:
  - name: Manage BGP address family config
    cisco.ios.ios_bgp_address_family:
      config:
        as_number: 65555
        address_family:
        - afi: ipv4
          networks:
            - address: 192.0.2.3
            - address: 192.0.2.2
          neighbors:
            - neighbor_address: 192.0.2.1
              description: test1
              remote_as: 100
              route_maps:
                - name: test_rm
                  out: true
            - neighbor_address: 192.0.3.1
              description: test2
              remote_as: 100
              route_maps:
                - name: test_rm
                  in: true
      state: replaced


<!--- Paste example playbooks or commands between quotes below -->


##### EXPECTED RESULTS
The module should detect that the current configuration matches the desired state and report no changes (changed: false).


##### ACTUAL RESULTS
The module repeatedly applies configuration changes, resulting in unnecessary commands being issued to the device.

```
TASK [Manage BGP address family config] ********************************************************************************************************************************************************************************************
changed: [lab_9300] => {
    "changed": true,
    "commands": [
        "router bgp 65555",
        "address-family ipv4",
        "neighbor 192.0.2.1 remote-as 100",
        "no neighbor 192.0.2.1 activate",
        "neighbor 192.0.2.1 description test1",
        "neighbor 192.0.2.1 route-map test_rm out",
        "neighbor 192.0.3.1 remote-as 100",
        "no neighbor 192.0.3.1 activate",
        "neighbor 192.0.3.1 description test2",
        "neighbor 192.0.3.1 route-map test_rm in",
        "network 192.0.2.2"
    ]
}

```

Analysis

Root Cause

The idempotency issue arises due to incomplete or flawed comparison logic in the module. Specifically:

Nested Attributes:
Attributes like route_maps, description, and activate are not being compared deeply, causing the module to interpret the current state as different from the desired state.

Default Values:
Null or default values for attributes are not being handled correctly, leading to unnecessary changes.
State Enforcement:

The state: replaced option should enforce strict idempotency, but the module applies changes incrementally instead of enforcing a strict match.
Please note that I also tried merge and overridden, and in all cases it fails.

Impact
This bug causes:

Unnecessary Configuration Changes:
Commands are repeatedly issued even when the current state matches the desired state.
Disruption in Production Environments:
Reapplying configuration can cause temporary disruptions in BGP sessions or routing.
Loss of Idempotency:
The behavior breaks the fundamental principle of idempotency in Ansible playbooks.

Suggested Fix
Code Fix
The module's comparison logic should be updated to:

Perform a deep comparison of nested attributes like route_maps, description, and activate.
Handle null values and defaults properly to avoid interpreting the current state as incomplete.
Enforce strict idempotency for state: replaced.


`
def compare_neighbors(desired_neighbors, current_neighbors):
    commands = []
    for neighbor in desired_neighbors:
        current_neighbor = next((n for n in current_neighbors if n['neighbor_address'] == neighbor['neighbor_address']), {})
        
        # Compare 'activate'
        if neighbor.get('activate') is not None and neighbor['activate'] != current_neighbor.get('activate'):
            commands.append(f"neighbor {neighbor['neighbor_address']} {'activate' if neighbor['activate'] else 'no activate'}")
        
        # Compare 'route_maps'
        if 'route_maps' in neighbor:
            for route_map in neighbor['route_maps']:
                current_route_map = next((rm for rm in current_neighbor.get('route_maps', []) if rm['name'] == route_map['name']), None)
                if not current_route_map or current_route_map != route_map:
                    if route_map.get('in'):
                        commands.append(f"neighbor {neighbor['neighbor_address']} route-map {route_map['name']} in")
                    if route_map.get('out'):
                        commands.append(f"neighbor {neighbor['neighbor_address']} route-map {route_map['name']} out")
        
        # Compare 'description'
        if neighbor.get('description') and neighbor['description'] != current_neighbor.get('description'):
            commands.append(f"neighbor {neighbor['neighbor_address']} description {neighbor['description']}")
    
    return commands
`
