### ISSUE TITLE
Cisco BGP l2vpn address-family issue

### ISSUE THREAD

**Issue by ir12345-ed** [ansible-collections/cisco.ios#1202]
##### SUMMARY

The module ios_bgp_address_family returns error when trying to create l2vpn address family. 
If "safi" option is specified as "evpn" the play works. With any other option or none at all it returns error:
"msg": "value of safi must be one of: flowspec, mdt, multicast, mvpn, evpn, unicast, got: vpls found in config -> address_family"
While playbook returns error the config is written to device fine without "safi" option or option value of "vpls".
Like this:
router bgp 12345
 bgp router-id 192.168.1.1
 bgp log-neighbor-changes
 bgp graceful-restart
 no bgp default ipv4-unicast
 !
 address-family ipv4
 exit-address-family
 !
 address-family l2vpn vpls
  neighbor 192.168.2.1 activate
 exit-address-family

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module > ios_bgp_address_family

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/<user>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/<user>/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection Version
---------- -------
cisco.ios  10.1.0 
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/home/<user>/Ansible']

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT

System image file is "bootflash:asr920-universalk9_npe.17.09.07.SPA.bin"
cisco ASR-920-24SZ-M (Freescale P2020) processor (revision 1.2 GHz) with 853132K/6147K bytes of memory.

##### STEPS TO REPRODUCE

Running below playbook against inventory of cisco ios hosts.

```yaml
- name: Configure BGP vpls neighbors
  hosts: cisco_hosts
  gather_facts: false
  connection: network_cli

  vars:
    local_asn: 12345
    peer_ip: 192.168.2.1

  tasks:
    - name: Configure BGP vpnv4 neighbors
        cisco.ios.ios_bgp_address_family:
          config: 
            as_number: "{{ local_asn }}"
            address_family:
              - afi: l2vpn
                safi: vpls
                neighbors:
                - activate: true
                  neighbor_address: "{{ peer_ip }}"
          state: merged
        register: bgp_vpnv4_neighbors_config_output
```

##### EXPECTED RESULTS

Address family is created and playbook returns either "ok" or "changed"

##### ACTUAL RESULTS

The playbook ran into error on task "Configure BGP vpnv4 neighbors" although the task result on device was as expected.

```paste below
"msg": "value of safi must be one of: flowspec, mdt, multicast, mvpn, evpn, unicast, got: vpls found in config -> address_family"
```
