### ISSUE TITLE
IOS ACL resource module traceback error

### ISSUE THREAD

**Issue by justjais** [ansible-collections/cisco.ios#13]
##### SUMMARY

IOS ACL resource module throws a traceback when tried to configure protocol_options other than `icmp`, `igmp` and `tcp`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_acls
##### ANSIBLE VERSION

```paste below
devel
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

mac os

##### STEPS TO REPRODUCE

```yaml
- name: Replace provided configuration
    cisco.ios.ios_acls:
      config:
        - afi: ipv4
          acls:
            - name: 123
              aces:
                - grant: deny
                  protocol: eigrp
                  protocol_options:
                    eigrp: true
                  source:
                    address: 192.0.2.0
                    wildcard_bits: 0.0.0.255
                  destination:
                    address: 192.0.3.0
                    wildcard_bits: 0.0.0.255
                  dscp: ef
                  ttl:
                    eq: 10
      state: replaced
```

##### EXPECTED RESULTS

ACE with igrp should be configured

##### ACTUAL RESULTS

Fails with a traceback

```paste below

```
