### ISSUE TITLE
ios_ospfv2 multiple networks per process

### ISSUE THREAD

**Issue by maxrainer** [ansible-collections/cisco.ios#135]
##### SUMMARY
When configuring OSPF on Cisco device it is valid to have mutliple "network" statements per process.
But the datamodel of the RM has a dict instead of a list. So it is not possible to define more than one network.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_ospfv2
cisco.ios.ios_facts

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/mrainer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mrainer/venv/latest/lib/python3.7/site-packages/ansible
  executable location = /Users/mrainer/venv/latest/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:26) [Clang 11.0.0 (clang-1100.0.33.16)]
```
Collection version: cisco.ios:1.0.3

##### CONFIGURATION

```paste below
ospfv2:
        processes:
        -   network:
                address: 10.10.100.0
                area: '0'
                wildcard_bits: 0.0.0.255
            process_id: 10
```

##### OS / ENVIRONMENT

Cisco IOS 15

##### STEPS TO REPRODUCE

configure more than one network statement in one ospf process
and collect the network_resource with ios_facts module

```yaml

```

##### EXPECTED RESULTS

-   network:
                - address: 10.10.100.0
                   area: '0'
                   wildcard_bits: 0.0.0.255
                - address: 9.9.9.2
                   area: '2'
                   wildcard_bits: 0.0.0.0
            process_id: 10

##### ACTUAL RESULTS

```paste below

```

**Comment by maxrainer** [comment]
same behavior with OSPF neighbors:

```
    ospfv2:
        processes:
        -   areas:
            -   area_id: '1'
                ranges:
                -   address: 9.9.9.1
                    cost: 100
                    netmask: 255.255.255.255
                -   address: 9.9.9.0
                    cost: 100
                    netmask: 255.255.255.0
            neighbor:
                address: 9.9.9.2
                cost: 10
                priority: 10
            network:
                address: 10.10.100.0
                area: '0'
                wildcard_bits: 0.0.0.255
            process_id: 10
```
IOS config:
```
router ospf 10
 network 10.10.100.0 0.0.0.255 area 0
 neighbor 10.10.100.102 priority 10
 neighbor 9.9.9.3 cost 20
 neighbor 9.9.9.2 cost 10
```
