### ISSUE TITLE
cisco.ios.ios_command issue vs ios_command

### ISSUE THREAD

**Issue by feisa** [ansible-collections/cisco.ios#140]
##### SUMMARY
cisco.ios.ios_command throws errors vs the legacy ios_command

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_command 

##### ANSIBLE VERSION
ansible 2.9.13
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = ['/home/feisa/ansible-network/library']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### STEPS TO REPRODUCE
Orignal Task 
```
- name: Reload IOS Device 
  ios_command:
    commands:
      - command: "reload"
        prompt: "[confirm]"
        answer: "\r"
  vars:  
    ansible_command_timeout: 60
  when:
    - ansible_sysuptime|int > 0
  tags:
    - ios-reboot  
```

Collection task 
```
- name: Reload IOS Device 
  cisco.ios.ios_command:
    commands:
      - command: "reload"
        prompt: "[confirm]"
        answer: "\r"
  vars:  
    ansible_command_timeout: 60
  when:
    - ansible_sysuptime|int > 0
  tags:
    - ios-reboot  
```

##### EXPECTED RESULTS
```
   "changed": false,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": null,
            "commands": [
                {
                    "answer": "\r",
                    "check_all": false,
                    "command": "reload",
                    "newline": true,
                    "output": null,
                    "prompt": "[confirm]",
                    "sendonly": false
                }
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": null,
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null,
            "wait_for": null
        }
    },
    "stdout": [
        "None"
    ],
    "stdout_lines": [
        [
            "None"
        ]
    ]
```

##### ACTUAL RESULTS
```
  File "/tmp/ansible_cisco.ios.ios_command_payload_88jfs_ty/ansible_cisco.ios.ios_command_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/ios.py", line 139, in run_commands
    return connection.run_commands(commands=commands, check_rc=check_rc)
  File "/tmp/ansible_cisco.ios.ios_command_payload_88jfs_ty/ansible_cisco.ios.ios_command_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
[WARNING]: The value {'command': 'reload', 'prompt': '[confirm]', 'answer': '\r'} (type dict) in a string field was converted to "{'command': 'reload', 'prompt': '[confirm]', 'answer': '\\r'}" (type
string). If this does not look like what you expect, quote the entire value to ensure it does not change.
fatal: [tc1-leafc006]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "{'command': 'reload', 'prompt': '[confirm]', 'answer': '\\r'}"
            ],
            "interval": 1,
            "match": "all",
            "provider": null,
            "retries": 10,
            "wait_for": null
        }
    },
    "msg": "{'command': 'reload', 'prompt': '[confirm]', 'answer': '\\r'}\r\n{'command': 'reload', 'prompt': '[confirm]', 'answer': '\\r'}\r\n^\r\n% Invalid input detected at '^' marker.\r\n\r\ntc1-leafc006#"
}
```
