### ISSUE TITLE
IOS Virtual-* interfaces are being ignored with ios_l3_interfaces module

### ISSUE THREAD

**Issue by benjdudas** [ansible-collections/cisco.ios#141]
##### SUMMARY

Configurations are not being added to interface type Virtual-Template with the ios_l3_interfaces module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_l3_interfaces

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/bdudas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]

```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_RETRIES(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = 2
DEFAULT_HOST_LIST(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = ['/home/bdudas/dev-net/inventory/hosts']
DEFAULT_KEEP_REMOTE_FILES(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = True
DEFAULT_LOG_PATH(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = /home/bdudas/dev-net/ec2_cisco_xe/debug_log.txt
DEFAULT_ROLES_PATH(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = ['/home/bdudas/dev-net/ec2_cisco_xe/roles']
DEPRECATION_WARNINGS(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = False
HOST_KEY_CHECKING(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = 30
RETRY_FILES_ENABLED(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = False

```

##### OS / ENVIRONMENT

Cisco IOS XE Software, Version 16.09.01",

##### STEPS TO REPRODUCE

```yaml
---
- hosts: ec2_cisco_xe
  gather_facts: false
  vars:
    inet_tunnel_out_intf: "Virtual-Template1"

  collections:
    - cisco.ios

  tasks:
    - name: Add ipv4 to {{ inet_tunnel_out_intf }}
      ios_l3_interfaces:
        config:
          - name: "{{ inet_tunnel_out_intf }}"
            ipv4: 
              - address: 1.1.1.1/30
        state: merged

```

##### EXPECTED RESULTS

The configuration change is applied for interface Virtual-Template1

##### ACTUAL RESULTS

Task is succesfull but no configuration is being applied to the running config of the managed node.

```paste below
ok: [ec2-52-89-82-88.us-west-2.compute.amazonaws.com] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "before": [
        {
            "name": "loopback0"
        },
        {
            "name": "loopback1"
        },
        {
            "name": "loopback2"
        },
        {
            "name": "loopback4"
        },
        {
            "ipv4": [
                {
                    "address": "dhcp"
                }
            ],
            "name": "GigabitEthernet1"
        }
    ],
    "changed": false,
    "commands": [],
    "invocation": {
        "module_args": {
            "config": [
                {
                    "ipv4": [
                        {
                            "address": "1.1.1.1/30",
                            "dhcp_client": null,
                            "dhcp_hostname": null,
                            "secondary": null
                        }
                    ],
                    "ipv6": null,
                    "name": "Virtual-Template1"
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    }
}

```
