### ISSUE TITLE
IOS Tunnel interfaces are being ignored with ios_l3_interfaces module

### ISSUE THREAD

**Issue by benjdudas** [ansible-collections/cisco.ios#144]
##### SUMMARY

Configurations are not being added to interface type Tunnel with the ios_l3_interfaces module.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_l3_interfaces
##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/bdudas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]

```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_RETRIES(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = 2
DEFAULT_HOST_LIST(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = ['/home/bdudas/dev-net/inventory/hosts']
DEFAULT_KEEP_REMOTE_FILES(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = True
DEFAULT_LOG_PATH(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = /home/bdudas/dev-net/ec2_cisco_xe/debug_log.txt
DEFAULT_ROLES_PATH(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = ['/home/bdudas/dev-net/ec2_cisco_xe/roles']
DEPRECATION_WARNINGS(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = False
HOST_KEY_CHECKING(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = 30
RETRY_FILES_ENABLED(/home/bdudas/dev-net/ec2_cisco_xe/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Cisco IOS XE Software, Version 16.09.01",
##### STEPS TO REPRODUCE

```yaml
- hosts: ec2_cisco_xe
  gather_facts: false

  collections:
    - cisco.ios

  tasks:
    - name: Test ios_interfaces
      ios_interfaces:
        config:
          - name: Tunnel1
            enabled: true
        state: merged

    - name: Test ios_l3_interfaces
      ios_l3_interfaces:
        config:
          - name: Tunnel1
            ipv4:
              - address: 1.1.1.1/30
        state: merged
...

```

##### EXPECTED RESULTS

The configuration change is applied for interface Tunnel1

##### ACTUAL RESULTS

Task is succesfull but no configuration is being applied to the running config of the managed node.

```paste below
ok: [ec2-52-89-82-88.us-west-2.compute.amazonaws.com] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "before": [
        {
            "description": "Behold a pale horse",
            "enabled": true,
            "name": "loopback0"
        },
        {
            "description": "Test from Yang Explorer",
            "enabled": true,
            "name": "loopback1"
        },
        {
            "enabled": true,
            "name": "loopback2"
        },
        {
            "enabled": true,
            "name": "loopback4"
        },
        {
            "enabled": true,
            "name": "Tunnel1"
        },
        {
            "enabled": true,
            "name": "GigabitEthernet1"
        },
        {
            "description": "test from Ansible",
            "enabled": true,
            "name": "Virtual-Template1"
        }
    ],
    "changed": false,
    "commands": [],
    "invocation": {
        "module_args": {
            "config": [
                {
                    "description": null,
                    "duplex": null,
                    "enabled": true,
                    "mtu": null,
                    "name": "Tunnel1",
                    "speed": null
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    }
}

```
