### ISSUE TITLE
Return VRF data in ios_facts module

### ISSUE THREAD

**Issue by brandomando** [ansible-collections/cisco.ios#153]
##### SUMMARY

- Create a VRFs model in the returned facts to list the configured VRFs on a device
- Include VRF forwarding in `ios_facts` interfaces model

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ios_facts

##### ADDITIONAL INFORMATION

In the ios_facts module, it does not currently collect the forwarding vrf of the interfaces. In our environment, we leverage VRF heavily, so we have to gather vrf information from the configuration returned by the module, because it is not available within the JSON interface models.

```yaml
- name: "GATHER IOS FACTS"
  ios_facts:
    gather_subset:
      - !all
      - !min
    gather_network_resources:
      - interfaces
```
