### ISSUE TITLE
Setting password for new user fail because of wrong condition

### ISSUE THREAD

**Issue by lduck** [ansible-collections/cisco.ios#167]
##### SUMMARY

It is not possible to set password to user, that was created without password. 
When user exists on ios, but no password was set to him for now (`username testuser privilege 3`), then the module returns msg "Can not have both a user password and a user secret. Please choose one or the other."

By my opinion, there is wrong condition in the file ios_user.py, at line 402:
`if have and password_type != have["password_type"]:`
Because if there is line `username testuser privilege 3` in config, then the have dict is` {'privilege': 3, 'state': 'present', 'configured_password': None, 'name': u'testuser', 'view': None, 'nopassword': False, 'password_type': None, 'hashed_password': None, 'sshkey': []}`.
I think, that the condition should be something like:
`if have and have['password_type'] and password_type != have['password_type']:`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_user

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
```

##### OS / ENVIRONMENT

Switch Ports Model              SW Version            SW Image
------ ----- -----              ----------            ----------
*    1 50    WS-C2960S-48TS-S   12.2(55)SE7           C2960S-UNIVERSALK9-M

##### STEPS TO REPRODUCE

```
- hosts: all
  gather_facts: False
  tasks:
    - name: 'create user'
      ios_user:
        name: "testuser"
        privilege: "3"
        state: "present"

    - name: 'Set users password'
      ios_user:
        name: "testuser"
        state: "present"
        configured_password: $encrypted$
        update_password: always
```

##### EXPECTED RESULTS
create user and set password.

##### ACTUAL RESULTS
```
PLAY [all] *********************************************************************

TASK [create user] *************************************************************
[WARNING]: Module did not set no_log for update_password
[WARNING]: Module did not set no_log for password_type
changed: [IOS_SW]

TASK [Set users password] ******************************************************
fatal: [IOS_SW]: FAILED! => {"changed": false, "msg": "Can not have both a user password and a user secret. Please choose one or the other."}

PLAY RECAP *********************************************************************
IOS_SW        : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
