### ISSUE TITLE
ios_l3_interfaces with state:replaced does not remove unwanted IPs

### ISSUE THREAD

**Issue by eleksis** [ansible-collections/cisco.ios#168]
##### SUMMARY

If there are multiple IP addresses configured on interface and we run ios_l3_interfaces module with only **subset** of these IPs as input and state: `replaced`, module should remove/purge other IPs that we did not pass in input data. At least that is what it says in docs (`Replaces device configuration of listed interfaces with provided configuration`). Unexpected behavior is true for IPv4 and IPv6 addresses.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_l3_interfaces.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
python version = 3.7.3
cisco.ios = 1.1.0
```

##### CONFIGURATION

```paste below
default
```

##### OS / ENVIRONMENT

Tested on Cisco IOS Software, IOS-XE Software, Catalyst 4500 L3 Switch  Software (cat4500e-UNIVERSALK9-M), Version 03.10.01.E RELEASE SOFTWARE (fc4)

##### STEPS TO REPRODUCE

Before state on switch:
```
interface Vlan4
 ip address 192.168.2.1 255.255.255.0 secondary
 ip address 192.168.1.1 255.255.255.0 secondary
 ip address 192.168.0.1 255.255.255.0
 ipv6 address 2001:db8:a0b:12f0::1/64
 ipv6 address 2001:db8:a0b:12f0::2/64
 ipv6 enable
```

```yaml
    - name: Configure IPs on L3 interfaces
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Vlan4
            ipv4:
              - address: 192.168.0.1/24
              - address: 192.168.1.1/24
                secondary: true
            ipv6:
              - address: 2001:db8:a0b:12f0::1/64
        state: replaced
```

##### EXPECTED RESULTS

Should remove 192.168.2.1 and 2001:db8:a0b:12f0::2
Expected after state:
```
interface Vlan4
 ip address 192.168.1.1 255.255.255.0 secondary
 ip address 192.168.0.1 255.255.255.0
 ipv6 address 2001:db8:a0b:12f0::1/64
 ipv6 enable
```

##### ACTUAL RESULTS

Module gets correct state from device, but does not generate any commands (diff between have&want is apparently empty).

Debug output:
```
{
    "result": {
        "before": [
            {
                "ipv4": [
                    {
                        "address": "192.168.1.1 255.255.255.0",
                        "secondary": true
                    },
                    {
                        "address": "192.168.2.1 255.255.255.0",
                        "secondary": true
                    },
                    {
                        "address": "192.168.0.1 255.255.255.0"
                    }
                ],
                "ipv6": [
                    {
                        "address": "2001:db8:a0b:12f0::1/64"
                    },
                    {
                        "address": "2001:db8:a0b:12f0::1/64"
                    }
                ],
                "name": "Vlan4"
            }
        ],
        "changed": false,
        "commands": [],
        "failed": false
    }
}
```
Actual after state on device (no change):
```paste below
interface Vlan4
 ip address 192.168.2.1 255.255.255.0 secondary
 ip address 192.168.1.1 255.255.255.0 secondary
 ip address 192.168.0.1 255.255.255.0
 ipv6 address 2001:db8:a0b:12f0::1/64
 ipv6 address 2001:db8:a0b:12f0::2/64
 ipv6 enable
```

**Comment by eleksis** [comment]
One more issue. If we are setting more than one secondary IPv4 addresses (total 3 or more), module always generates commands and reports `changed`, even if the correct stare is already on device.

Example:
```
    - name: Configure IPs on L3 interfaces
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Vlan4
            ipv4:
              - address: 192.168.0.1/24
              - address: 192.168.1.1/24
                secondary: true
              - address: 192.168.2.1/24
                secondary: true
        state: replaced
```
