### ISSUE TITLE
BGP Module Doesnt Set Password

### ISSUE THREAD

**Issue by feisa** [ansible-collections/cisco.ios#186]
##### SUMMARY
The bgp module is now applying the password, looks like it might be ignored 

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
ansible 2.10.2
  config file = /home/user/ansible-network/ansible.cfg
  configured module search path = ['/home/user/ansible-network/library']
  ansible python module location = /home/user/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### CONFIGURATION
COLLECTIONS_PATHS(/home/user/ansible-network/ansible.cfg) = ['/home/user/ansible-network/collections']
DEFAULT_FORKS(/home/user/ansible-network/ansible.cfg) = 100
DEFAULT_HOST_LIST(/home/user/ansible-network/ansible.cfg) = ['/home/user/ansible-network/inventories']
DEFAULT_MODULE_PATH(/home/user/ansible-network/ansible.cfg) = ['/home/user/ansible-network/library']
DEFAULT_ROLES_PATH(/home/user/ansible-network/ansible.cfg) = ['/home/user/ansible-network/roles']
DEFAULT_SCP_IF_SSH(/home/user/ansible-network/ansible.cfg) = True
GALAXY_SERVER_LIST(/home/user/ansible-network/ansible.cfg) = ['automation_hub', 'release_galaxy']
HOST_KEY_CHECKING(/home/user/ansible-network/ansible.cfg) = False
INTERPRETER_PYTHON(/home/user/ansible-network/ansible.cfg) = auto
PERSISTENT_COMMAND_TIMEOUT(/home/user/ansible-network/ansible.cfg) = 60000000
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/user/ansible-network/ansible.cfg) = 100
PERSISTENT_CONNECT_TIMEOUT(/home/user/ansible-network/ansible.cfg) = 6000

##### OS / ENVIRONMENT
Cisco IOS XE Software, Version 16.12.04
Cisco IOS Software [Gibraltar], ASR1000 Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 16.12.4, RELEASE SOFTWARE (fc5)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2020 by Cisco Systems, Inc.
Compiled Thu 09-Jul-20 21:59 by mcpre

##### STEPS TO REPRODUCE
```
- name: Configure Edge BGP Neighbors
  cisco.ios.ios_bgp:
    config:
      bgp_as: "{{ as_number }}"
      log_neighbor_changes: true
      neighbors:
      - neighbor: "{{ item[0].remote_ipv4 }}"
        remote_as: "{{ item[0].remote_as }}"
        password: "{{ item[0].passwd | default(omit) }}"
        description: "{{ item[0].des | default(omit) }}"
        prefix_list_in: "{{ item[0].prefix_in | default(omit) }}"
        prefix_list_out: "{{ item[0].prefix_out| default(omit) }}"
      networks: 
      - prefix: "{{ item[1].route | default(omit) }}" 
        masklen: "{{ item[1].prefix | default(omit) }}"
  when:
    - bgp_neighbors is defined
    - inventory_hostname in groups["ios_routers_edge"]
  with_nested:
    - "{{ bgp_neighbors }}"
    - "{{ bgp_advertisement }}"
  tags:
    - ios-bgp

bgp_neighbors:
  - { remote_as: "18683", remote_ipv4: "66.85.63.241",   des: TO_ISP, route_map_out: TO_EXTERNAL, passwd: password, pwtype: 3des }

```
##### EXPECTED RESULTS
Password applies 

##### ACTUAL RESULTS
: 27}]) => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "ansible_loop_var": "item",
    "changed": true,
    "commands": [
        "router bgp 65000",
        "neighbor 66.85.63.241 password ********",
        "exit"
    ],
    "invocation": {
        "module_args": {
            "config": {
                "address_family": null,
                "bgp_as": 65000,
                "log_neighbor_changes": true,
                "neighbors": [
                    {
                        "description": "TO_ISP",
                        "ebgp_multihop": null,
                        "enabled": null,
                        "local_as": null,
                        "neighbor": "66.85.63.241",
                        "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                        "peer_group": null,
                        "remote_as": 18683,
                        "timers": null,
                        "update_source": null
                    }
                ],
                "networks": [
                    {
                        "masklen": 27,
                        "prefix": "67.199.249.0",
                        "route_map": null
                    }
                ],
                "router_id": null
            },
            "operation": "merge"
        }
    },
    "item": [
        {
            "des": "TO_ISP",
            "passwd": "password",
            "pwtype": "3des",
            "remote_as": "18683",
            "remote_ipv4": "66.85.63.241",
            "route_map_out": "TO_EXTERNAL"
        },
        {
            "null_route": true,
            "prefix": 27,
            "route": "67.199.249.0"
        }
    ]
}

```
