### ISSUE TITLE
New network resource modules always return changed=true

### ISSUE THREAD

**Issue by mchlrv** [ansible-collections/cisco.ios#19]
##### SUMMARY
Whenever I use the new Ansible 2.9 network resource modules they always seem to return `changed=true` even when the `before` and `after` are identical and nothing has changed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Tested with:
ios_interfaces
ios_vlans
eos_interfaces
eos_vlans

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /Users/mchlrv/ansible/ansible.cfg
  configured module search path = [u'/Users/mchlrv/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']

  ansible python module location = /Users/mchlrv/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /Users/mchlrv/Library/Python/2.7/bin/ansible
  python version = 2.7.16 (default, Dec 13 2019, 18:00:32) [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s
```

##### CONFIGURATION
```
ACTION_WARNINGS(/Users/mchlrv/ansible/ansible.cfg) = False
COMMAND_WARNINGS(/Users/mchlrv/ansible/ansible.cfg) = False
DEFAULT_GATHERING(/Users/mchlrv/ansible/ansible.cfg) = explicit
DEFAULT_GATHER_TIMEOUT(/Users/mchlrv/ansible/ansible.cfg) = 0
DEFAULT_HOST_LIST(/Users/mchlrv/ansible/ansible.cfg) = [u'/Users/mchlrv/ansible/hosts']
DEPRECATION_WARNINGS(/Users/mchlrv/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/Users/mchlrv/ansible/ansible.cfg) = /usr/bin/python
RETRY_FILES_ENABLED(/Users/mchlrv/ansible/ansible.cfg) = False
SYSTEM_WARNINGS(/Users/mchlrv/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Cisco Nexus9000 7.0(3)I7(8)
Arista EOS 4.18.10M

##### STEPS TO REPRODUCE
```
- nxos_vlans:
    config: 
      - vlan_id: 20
        name: RED
        state: active
      - vlan_id: 30
        name: BLUE
        state: active
    state: replaced
```

##### EXPECTED RESULTS
When nothing has changed, so `before` and `after` are identical, changed result should be false.

##### ACTUAL RESULTS
`"changed": true`

**Comment by bile0026** [comment]
I have this same issue, even when I tried to use a loop to not actually change anything if a VLAN exists. I'm specifically using the ios_vlans, and ios_l2_interfaces module. 

```
ansible 2.9.7
  config file = /home/osboxes/network_ops/ansible.cfg
  configured module search path = ['/home/osboxes/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/osboxes/network_ops/.venv/lib64/python3.6/site-packages/ansible
  executable location = /home/osboxes/network_ops/.venv/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

Here's part of my tasks. The when statement should keep the rest of the code block from running when it evaluates to true if I'm not mistaken. It unfortunately causes a wrong handler call to save ios in my instance that causes the config to be saved even when no changes are made. Not the end of the world, but unexpected behavior. 

```
  - name: Create VLAN target_vlan
    when: "not target_vlan in (vlan_parsed | json_query('*.*.vlan_id'))"
    ios_vlans:
      config:
	- name: "{{ target_vlan_name }}"
          vlan_id: "{{ target_vlan }}"
          state: active
          shutdown: disabled
      state: merged
    notify: save ios
```
