### ISSUE TITLE
email address in MOTD not working.

### ISSUE THREAD

**Issue by TmyWu** [ansible-collections/cisco.ios#206]
##### SUMMARY

Using the cisco.ios.ios_banner module to configure motd on router bugs out while using the '@' symbol in mail.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_banner
##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /home/tmy30/Ansible-Infopact-Test1/ansible.cfg
  configured module search path = ['/home/tmy30/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/tmy30/Ansible-Infopact-Test1/ansible.cfg) = ['/home/tmy30/Ansible-Infopact-Test1/inventory']
HOST_KEY_CHECKING(/home/tmy30/Ansible-Infopact-Test1/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

---
```
- hosts: ios_devices
  gather_facts: false
  
  tasks:
    - name: Set MOTD
      cisco.ios.ios_banner:
        banner: motd
        text: |
          *                                                         support@example.com *
          *                                                    https://www.example.com/ *
          *******************************************************************************
        state: present
```
...

```yaml

```

##### ACTUAL RESULTS

```paste below
tmy30@INT-PF1YPCCP:~/Ansible-Infopact-Test1$ ansible-playbook test.yml 

PLAY [ios_devices] **************************************************************************************************************************************************************************************************************

TASK [Set MOTD] *****************************************************************************************************************************************************************************************************************
fatal: [ios_device1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "msg": "ct_KL_Router(config)#*                                                    https://www.example.com/ *\r\n*                                                    https://www.example.com/ *\r\n^\r\n% Invalid input detected at '^' marker.\r\n\r\nInfopact_KL_Router(config)#"}

PLAY RECAP **********************************************************************************************************************************************************************************************************************
ios_device1                : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
