### ISSUE TITLE
IOS ospf interfaces RM not setting authentication param as expected

### ISSUE THREAD

**Issue by justjais** [ansible-collections/cisco.ios#209]
##### SUMMARY

IOS ospf interfaces RM not setting authentication param as expected

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_ospf_interfaces

##### ANSIBLE VERSION

```paste below
2.10
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Mac os

##### STEPS TO REPRODUCE

```yaml
- name: Merge provided ios_ospf_interfaces configuration
  cisco.ios.ios_ospf_interfaces:
      config:
        - name: GigabitEthernet0/1
          address_family:
            - afi: ipv4
              authentication:
                key_chain: ine
              cost:
                interface_cost: 99
      state: merged
```

##### EXPECTED RESULTS

```
command expected:
 - interface GigabitEthernet0/1
 - ip ospf authentication key-chain ine
 - ip ospf cost 99
```

##### ACTUAL RESULTS

```paste below
command fired:
 - interface GigabitEthernet0/1
 - ip ospf cost 99
```
