### ISSUE TITLE
Command failed to run but reported success

### ISSUE THREAD

**Issue by seeravinder** [ansible-collections/cisco.ios#213]
##### SUMMARY
I am testing static route addition, On the Cisco router but the command fails on the router but Ansible reports that 1 Change is completed. It is not catching and reporting the errors produced by IOS CLI.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_static_routes

##### ANSIBLE VERSION

```ansible 2.9.6
  config file = /home/ravinder/automate/ansible.cfg
  configured module search path = ['/home/ravinder/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_TIMEOUT(/home/ravinder/automate/ansible.cfg) = 5
DEFAULT_TRANSPORT(/home/ravinder/automate/ansible.cfg) = paramiko
HOST_KEY_CHECKING(/home/ravinder/automate/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Cisco IOS Version 15.5(2)T

##### STEPS TO REPRODUCE

Either use a wrong VRF management name
Or use Next-hop as router self IP
I am sure there will be other cases where the command fails for some reason by the router but Ansible is not reporting it.
In short, it is not catching and reporting the errors produced by IOS CLI.
It will fail on the router but Ansible will report success.
 

```yaml
- name: Merge provided configuration with device configuration
          cisco.ios.ios_static_routes:
            config:
            - vrf: Management
              address_families:
              - afi: ipv4
                routes:
                - dest: 192.0.2.0/24
                  next_hops:
                  - forward_router_address: 10.1.255.6
                    name: Test_Static_Route
                    tag: 50
            - address_families:
              - afi: ipv4
                routes:
                - dest: 198.51.100.0/24
                  next_hops:
                  - forward_router_address: 10.1.255.13
                    name: merged_route_1
                    distance_metric: 110
                    tag: 40
                    multicast: true
                  - forward_router_address: 10.1.255.13
                    name: merged_route_2
                    distance_metric: 30
                  - forward_router_address: 10.1.255.13
                    name: merged_route_3
            state: merged
```

##### EXPECTED RESULTS

Expecting an error thrown by Cisco IOS reported back.

##### ACTUAL RESULTS

```paste below

PLAY [Network Route Change Playbook] ********************************************************************************

TASK [Gathering Facts] **********************************************************************************************
ok: [R1]

TASK [OBTAIN LOGIN INFORMATION] *************************************************************************************
ok: [R1]

TASK [Create change dir] ********************************************************************************************
ok: [R1]

TASK [Merge provided configuration with device configuration] *******************************************************
changed: [R1]

TASK [SAVE & BACKUP CONFIGURATION] **********************************************************************************
ok: [R1]

PLAY RECAP **********************************************************************************************************
R1                         : ok=5    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0


```
