### ISSUE TITLE
cisco.ios.ios_command timeout not working within task in a role

### ISSUE THREAD

**Issue by rudimocnik** [ansible-collections/cisco.ios#214]
##### SUMMARY
Hi
I have a playbook using my role with tasks using cisco.ios.ios_command to upgrade cisco devices. The playbook before the upgrade from 2.9.x and now with a newer version a single task is breaking with error: "timeout value 30 seconds reached while trying to send command". 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_command in combination with var section in a task

##### ANSIBLE VERSION

```
ansible 2.10.3
```

##### CONFIGURATION

```paste below
ACTION_WARNINGS(/home/test/ansible/dvp/ansible.cfg) = False
DEFAULT_FORKS(/home/test/ansible/dvp/ansible.cfg) = 20
DEFAULT_HOST_LIST(/home/test/ansible/dvp/ansible.cfg) = ['/home/test/ansible/dvp/inv.yml']
DEPRECATION_WARNINGS(/home/test/ansible/dvp/ansible.cfg) = False
HOST_KEY_CHECKING(/home/test/ansible/dvp/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/test/ansible/dvp/ansible.cfg) = 30
PERSISTENT_CONNECT_TIMEOUT(/home/test/ansible/dvp/ansible.cfg) = 60
```

##### OS / ENVIRONMENT

target system is running Cisco switch is running IOS-XE 16.12.3a

##### STEPS TO REPRODUCE

run the above tasks (see below) on a cisco switch with config settings specified above. One should succeed and the other should timeout with an error described.

```yaml
TASK1
---
# Transfer file to Cisco device

- name: Copy image to target device
  cisco.ios.ios_command:
    commands:
    - command: "copy {{ c9300_file_source }}:{{ c9300_file_name }} flash:"
      prompt: "Destination filename [{{ c9300_file_name }}]?"
      answer: "\r"
  vars:
    ansible_command_timeout: 200

TASK2
---
# Install image file to Cisco device

- name: Install new image
  cisco.ios.ios_command:
    commands: "request platform software package install switch all file flash:{{ c9300_file_name }} auto-copy"
  vars:
    ansible_command_timeout: 600
```

##### EXPECTED RESULTS

I expect for the timeout value to be respected.

##### ACTUAL RESULTS

TASK1 runs for about 90 seconds with no issues. 
TASK2 times out with  error: "timeout value 30 seconds reached while trying to send command" despite the timeout value of 600. Note, both tasks are using the same module. I cannot explain this. -vvvv didn't give me any hints. It seems that timeout is not in scope but then, why is TASK1 succeeding if the default command_timeout is 30 seconds.

Hint: TASK1 is copying a file from a USB to switchee's flash which results in continuous output to the console, while TASK2 for a bit before any output is given. Is that the caveat?

```paste below

```
