### ISSUE TITLE
ios_config excludes interface vrf assignments when complete config is submitted

### ISSUE THREAD

**Issue by hovisms** [ansible-collections/cisco.ios#224]
##### SUMMARY

Our use case requires us to submit a complete router configuration as it involves spin-up/tear-down of cisco CSR VMs in a lab environment. With a complete configuration (saved from a router, so syntactically correct) submitted through the ios_config module some commands are not issued to the device. A specific example in the debug below is the "ip vrf forwarding C1" command under the gigabitEthernet2 interface.
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /nfs/share/dev/shovis/cyber-range-automation-framework/playbook/ansible.cfg
  configured module search path = ['/home/ncrc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.6 (default, Mar 29 2019, 00:03:27) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
ALLOW_WORLD_READABLE_TMPFILES(/nfs/share/dev/shovis/cyber-range-automation-framework/playbook/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/nfs/share/dev/shovis/cyber-range-automation-framework/playbook/ansible.cfg) = -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ControlMaster=
DEFAULT_CALLBACK_WHITELIST(/nfs/share/dev/shovis/cyber-range-automation-framework/playbook/ansible.cfg) = ['timer', 'profile_tasks', 'profile_roles']
DEFAULT_FORKS(/nfs/share/dev/shovis/cyber-range-automation-framework/playbook/ansible.cfg) = 30
DEFAULT_ROLES_PATH(/nfs/share/dev/shovis/cyber-range-automation-framework/playbook/ansible.cfg) = ['/etc/ansible/roles', '/usr/share/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/nfs/share/dev/shovis/cyber-range-automation-framework/playbook/ansible.cfg) = skippy
DEFAULT_VAULT_PASSWORD_FILE(/nfs/share/dev/shovis/cyber-range-automation-framework/playbook/ansible.cfg) = /home/ncrc/.vault
DUPLICATE_YAML_DICT_KEY(/nfs/share/dev/shovis/cyber-range-automation-framework/playbook/ansible.cfg) = ignore
HOST_KEY_CHECKING(/nfs/share/dev/shovis/cyber-range-automation-framework/playbook/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Cisco CSR1000v
IOS XE 16.06.05

##### STEPS TO REPRODUCE

```
ConfigLines:
  - "!"
  - "! Last configuration change at 19:15:36 UTC Mon Nov 23 2020 by cisco"
  - "!"
  - "version 16.6"
  - "service timestamps debug datetime msec"
  - "service timestamps log datetime msec"
  - "service call-home"
  - "platform qfp utilization monitor load 80"
  - "no platform punt-keepalive disable-kernel-core"
  - "platform console virtual"
  - "platform hardware throughput level MB 10000"
  - "!"
  - "hostname inet-rtr3"
  - "!"
  - "boot-start-marker"
  - "boot-end-marker"
  - "!"
  - "!"
  - "!"
  - "no aaa new-model"
  - "!"
  - "ip vrf C2"
  - "!"
  - "ip vrf LR10"
  - " rd 10:10"
  - " route-target export 10:10"
  - " route-target import 10:10"
  - "!"
  - "ip vrf mgmt"
  - " rd 1:1"
  - " route-target export 1:1"
  - " route-target import 1:1"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "subscriber templating"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "mpls label mode all-vrfs protocol bgp-vpnv4 per-vrf"
  - "mpls ldp loop-detection"
  - "!"
  - "!"
  - "multilink bundle-name authenticated"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "crypto pki trustpoint TP-self-signed-1875639387"
  - " enrollment selfsigned"
  - " subject-name cn=IOS-Self-Signed-Certificate-1875639387"
  - " revocation-check none"
  - " rsakeypair TP-self-signed-1875639387"
  - "!"
  - "crypto pki trustpoint SLA-TrustPoint"
  - " enrollment pkcs12"
  - " revocation-check crl"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "license udi pid CSR1000V sn 9R4TRPJNNUT"
  - "license boot level ax"
  - "license smart enable"
  - "license smart reservation"
  - "diagnostic bootup level minimal"
  - "file prompt quiet"
  - "spanning-tree extend system-id"
  - "!"
  - "!"
  - "!"
  - "username cisco privilege 15 secret 5 $1$F1xa$qAC1FBQE/XXq8e4pbE.fr1"
  - "!"
  - "redundancy"
  - "!"
  - "!"
  - "!"
  - "crypto ikev2 keyring KR"
  - " peer All"
  - "  address 0.0.0.0 0.0.0.0"
  - "  pre-shared-key Cisco123"
  - " !"
  - "!"
  - "!"
  - "crypto ikev2 profile default"
  - " match identity remote any"
  - " authentication remote pre-share"
  - " authentication local pre-share"
  - " keyring local KR"
  - "!"
  - "crypto ikev2 profile default2"
  - " match fvrf C2"
  - " match identity remote any"
  - " authentication remote pre-share"
  - " authentication local pre-share"
  - " keyring local KR"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "crypto ipsec profile LR210"
  - " set ikev2-profile default2"
  - "!"
  - "crypto ipsec profile default"
  - " set ikev2-profile default"
  - "!"
  - "crypto ipsec profile default2"
  - " set ikev2-profile default2"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "interface Loopback2"
  - " ip vrf forwarding C2"
  - " ip address 172.24.3.1 255.255.255.255"
  - "!"
  - "interface Loopback210"
  - " ip vrf forwarding C2"
  - " ip address 172.24.3.10 255.255.255.255"
  - "!"
  - "interface Tunnel2"
  - " ip vrf forwarding mgmt"
  - " ip address 172.26.1.3 255.255.255.0"
  - " no ip redirects"
  - " ip nhrp authentication cisco123"
  - " ip nhrp map multicast 172.24.230.1"
  - " ip nhrp network-id 1"
  - " ip nhrp nhs 172.26.1.230 nbma 172.24.230.1"
  - " tunnel source Loopback2"
  - " tunnel mode gre multipoint"
  - " tunnel vrf C2"
  - " tunnel protection ipsec profile default2"
  - "!"
  - "interface Tunnel210"
  - " ip vrf forwarding LR10"
  - " ip address 172.26.10.3 255.255.255.0"
  - " no ip redirects"
  - " ip nhrp authentication cisco123"
  - " ip nhrp map multicast 172.24.230.10"
  - " ip nhrp network-id 1"
  - " ip nhrp nhs 172.26.10.230 nbma 172.24.230.10"
  - " mpls nhrp"
  - " tunnel source Loopback210"
  - " tunnel mode gre multipoint"
  - " tunnel vrf C2"
  - " tunnel protection ipsec profile LR210"
  - "!"
  - "interface GigabitEthernet1"
  - " ip address dhcp"
  - " negotiation auto"
  - " no mop enabled"
  - " no mop sysid"
  - "!"
  - "interface GigabitEthernet2"
  - " ip vrf forwarding C2"
  - " ip address 172.34.3.1 255.255.0.0"
  - " ip ospf lls disable"
  - " negotiation auto"
  - " no mop enabled"
  - " no mop sysid"
  - "!"
  - "interface GigabitEthernet3"
  - " ip vrf forwarding mgmt"
  - " ip address 192.168.3.1 255.255.255.0"
  - " ip ospf lls disable"
  - " negotiation auto"
  - " no mop enabled"
  - " no mop sysid"
  - "!"
  - "interface GigabitEthernet4"
  - " no ip address"
  - " shutdown"
  - " negotiation auto"
  - " no mop enabled"
  - " no mop sysid"
  - "!"
  - "interface GigabitEthernet5"
  - " no ip address"
  - " shutdown"
  - " negotiation auto"
  - " no mop enabled"
  - " no mop sysid"
  - "!"
  - "interface GigabitEthernet6"
  - " no ip address"
  - " shutdown"
  - " negotiation auto"
  - " no mop enabled"
  - " no mop sysid"
  - "!"
  - "interface GigabitEthernet7"
  - " no ip address"
  - " shutdown"
  - " negotiation auto"
  - " no mop enabled"
  - " no mop sysid"
  - "!"
  - "interface GigabitEthernet8"
  - " no ip address"
  - " shutdown"
  - " negotiation auto"
  - " no mop enabled"
  - " no mop sysid"
  - "!"
  - "interface GigabitEthernet9"
  - " no ip address"
  - " shutdown"
  - " negotiation auto"
  - " no mop enabled"
  - " no mop sysid"
  - "!"
  - "interface GigabitEthernet10"
  - " no ip address"
  - " shutdown"
  - " negotiation auto"
  - " no mop enabled"
  - " no mop sysid"
  - "!"
  - "!"
  - "router eigrp 1"
  - " !"
  - " address-family ipv4 vrf mgmt autonomous-system 1"
  - "  network 0.0.0.0"
  - " exit-address-family"
  - " !"
  - " address-family ipv4 vrf LR10 autonomous-system 10"
  - "  network 0.0.0.0"
  - " exit-address-family"
  - "!"
  - "router bgp 100"
  - " bgp log-neighbor-changes"
  - " !"
  - " address-family ipv4 vrf LR10"
  - "  redistribute connected"
  - "  neighbor 172.25.10.230 remote-as 100"
  - "  neighbor 172.25.10.230 activate"
  - " exit-address-family"
  - "!"
  - "!"
  - "virtual-service csr_mgmt"
  - " ip shared host-interface GigabitEthernet1"
  - " activate"
  - "!"
  - "ip forward-protocol nd"
  - "ip http server"
  - "ip http authentication local"
  - "ip http secure-server"
  - "ip route vrf C2 172.24.230.0 255.255.255.0 172.34.0.1"
  - "!"
  - "ip ssh rsa keypair-name ssh-key"
  - "ip ssh version 2"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "control-plane"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "line con 0"
  - " stopbits 1"
  - "line vty 0 4"
  - " exec-timeout 0 0"
  - " login local"
  - " transport input ssh"
  - "line vty 5 15"
  - " exec-timeout 0 0"
  - " login"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "!"
  - "end"
  
- name: misc_config_lines
  cisco.ios.ios_config:
    multiline_delimiter: ','
    match: none
    lines: "{{ ConfigLines }}"
    replace: block
```

```yaml

```

##### EXPECTED RESULTS

All commands from ConfigLines applied.

##### ACTUAL RESULTS

ip vrf forwarding C2 is missing from interface GigabitEthernet2 

```paste below
TASK [d2.csr : misc_config_lines] *******************************************************************************************************************************************
task path: /nfs/share/dev/shovis/cyber-range-automation-framework/playbook/roles/d2.csr/tasks/main.yml:81
Monday 11 January 2021  16:40:17 +0000 (0:00:00.234)       0:00:00.234 ********
Monday 11 January 2021  16:40:17 +0000 (0:00:00.231)       0:00:00.231 ********
<11.49.0.4> using connection plugin network_cli (was local)
<11.49.0.4> starting connection from persistent connection plugin
<11.49.0.4> local domain socket does not exist, starting it
<11.49.0.4> control socket path is /home/ncrc/.ansible/pc/2ae3f6ac14
<11.49.0.4> local domain socket listeners started successfully
<11.49.0.4> loaded cliconf plugin ios from path /usr/local/lib/python3.6/site-packages/ansible/plugins/cliconf/ios.py for network_os ios
<11.49.0.4>
<11.49.0.4> local domain socket path is /home/ncrc/.ansible/pc/2ae3f6ac14
<11.49.0.4> socket_path: /home/ncrc/.ansible/pc/2ae3f6ac14
<11.49.0.4> ESTABLISH LOCAL CONNECTION FOR USER: ncrc
<11.49.0.4> EXEC /bin/sh -c 'echo ~ncrc && sleep 0'
<11.49.0.4> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ncrc/.ansible/tmp/ansible-tmp-1610383220.2416267-273140475403906 `" && echo ansible-tmp-1610383220.2416267-273140475403906="` echo /home/ncrc/.ansible/tmp/ansible-tmp-1610383220.2416267-273140475403906 `" ) && sleep 0'
<inet-rtr3> Attempting python interpreter discovery
<11.49.0.4> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<11.49.0.4> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /nfs/share/dev/shovis/cyber-range-automation-framework/playbook/collections/ansible_collections/cisco/ios/plugins/modules/ios_config.py
<11.49.0.4> PUT /home/ncrc/.ansible/tmp/ansible-local-14166ioewsjeo/tmpzswl0l9s TO /home/ncrc/.ansible/tmp/ansible-tmp-1610383220.2416267-273140475403906/AnsiballZ_ios_config.py
<11.49.0.4> EXEC /bin/sh -c 'chmod u+x /home/ncrc/.ansible/tmp/ansible-tmp-1610383220.2416267-273140475403906/ /home/ncrc/.ansible/tmp/ansible-tmp-1610383220.2416267-273140475403906/AnsiballZ_ios_config.py && sleep 0'
<11.49.0.4> EXEC /bin/sh -c '/usr/bin/python /home/ncrc/.ansible/tmp/ansible-tmp-1610383220.2416267-273140475403906/AnsiballZ_ios_config.py && sleep 0'
<11.49.0.4> EXEC /bin/sh -c 'rm -f -r /home/ncrc/.ansible/tmp/ansible-tmp-1610383220.2416267-273140475403906/ > /dev/null 2>&1 && sleep 0'
changed: [inet-rtr3] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "banners": {},
    "changed": true,
    "commands": [
        "version 16.6",
        "service timestamps debug datetime msec",
        "service timestamps log datetime msec",
        "service call-home",
        "platform qfp utilization monitor load 80",
        "no platform punt-keepalive disable-kernel-core",
        "platform console virtual",
        "platform hardware throughput level MB 10000",
        "hostname inet-rtr3",
        "boot-start-marker",
        "boot-end-marker",
        "no aaa new-model",
        "ip vrf C2",
        "ip vrf LR10",
        "rd 10:10",
        "route-target export 10:10",
        "route-target import 10:10",
        "ip vrf mgmt",
        "rd 1:1",
        "route-target export 1:1",
        "route-target import 1:1",
        "subscriber templating",
        "mpls label mode all-vrfs protocol bgp-vpnv4 per-vrf",
        "mpls ldp loop-detection",
        "multilink bundle-name authenticated",
        "crypto pki trustpoint TP-self-signed-1875639387",
        "enrollment selfsigned",
        "subject-name cn=IOS-Self-Signed-Certificate-1875639387",
        "revocation-check none",
        "rsakeypair TP-self-signed-1875639387",
        "crypto pki trustpoint SLA-TrustPoint",
        "enrollment pkcs12",
        "revocation-check crl",
        "license udi pid CSR1000V sn 9R4TRPJNNUT",
        "license boot level ax",
        "license smart enable",
        "license smart reservation",
        "diagnostic bootup level minimal",
        "file prompt quiet",
        "spanning-tree extend system-id",
        "username cisco privilege 15 secret 5 $1$F1xa$qAC1FBQE/XXq8e4pbE.fr1",
        "redundancy",
        "crypto ikev2 keyring KR",
        "peer All",
        "address 0.0.0.0 0.0.0.0",
        "pre-shared-key Cisco123",
        "crypto ikev2 profile default",
        "match identity remote any",
        "authentication remote pre-share",
        "authentication local pre-share",
        "keyring local KR",
        "crypto ikev2 profile default2",
        "match fvrf C2",
        "crypto ipsec profile LR210",
        "set ikev2-profile default2",
        "crypto ipsec profile default",
        "set ikev2-profile default",
        "crypto ipsec profile default2",
        "interface Loopback2",
        "ip vrf forwarding C2",
        "ip address 172.24.3.1 255.255.255.255",
        "interface Loopback210",
        "ip address 172.24.3.10 255.255.255.255",
        "interface Tunnel2",
        "ip vrf forwarding mgmt",
        "ip address 172.26.1.3 255.255.255.0",
        "no ip redirects",
        "ip nhrp authentication cisco123",
        "ip nhrp map multicast 172.24.230.1",
        "ip nhrp network-id 1",
        "ip nhrp nhs 172.26.1.230 nbma 172.24.230.1",
        "tunnel source Loopback2",
        "tunnel mode gre multipoint",
        "tunnel vrf C2",
        "tunnel protection ipsec profile default2",
        "interface Tunnel210",
        "ip vrf forwarding LR10",
        "ip address 172.26.10.3 255.255.255.0",
        "ip nhrp map multicast 172.24.230.10",
        "ip nhrp nhs 172.26.10.230 nbma 172.24.230.10",
        "mpls nhrp",
        "tunnel source Loopback210",
        "tunnel protection ipsec profile LR210",
        "interface GigabitEthernet1",
        "ip address dhcp",
        "negotiation auto",
        "no mop enabled",
        "no mop sysid",
        "interface GigabitEthernet2",
        "ip address 172.34.3.1 255.255.0.0",
        "ip ospf lls disable",
        "interface GigabitEthernet3",
        "ip address 192.168.3.1 255.255.255.0",
        "interface GigabitEthernet4",
        "no ip address",
        "shutdown",
        "interface GigabitEthernet5",
        "interface GigabitEthernet6",
        "interface GigabitEthernet7",
        "interface GigabitEthernet8",
        "interface GigabitEthernet9",
        "interface GigabitEthernet10",
        "router eigrp 1",
        "address-family ipv4 vrf mgmt autonomous-system 1",
        "network 0.0.0.0",
        "exit-address-family",
        "address-family ipv4 vrf LR10 autonomous-system 10",
        "router bgp 100",
        "bgp log-neighbor-changes",
        "address-family ipv4 vrf LR10",
        "redistribute connected",
        "neighbor 172.25.10.230 remote-as 100",
        "neighbor 172.25.10.230 activate",
        "virtual-service csr_mgmt",
        "ip shared host-interface GigabitEthernet1",
        "activate",
        "ip forward-protocol nd",
        "ip http server",
        "ip http authentication local",
        "ip http secure-server",
        "ip route vrf C2 172.24.230.0 255.255.255.0 172.34.0.1",
        "ip ssh rsa keypair-name ssh-key",
        "ip ssh version 2",
        "control-plane",
        "line con 0",
        "stopbits 1",
        "line vty 0 4",
        "exec-timeout 0 0",
        "login local",
        "transport input ssh",
        "line vty 5 15",
        "login",
        "end"
    ],
    "invocation": {
        "module_args": {
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "defaults": false,
            "diff_against": null,
            "diff_ignore_lines": null,
            "intended_config": null,
            "lines": [
                "!",
                "! Last configuration change at 19:15:36 UTC Mon Nov 23 2020 by cisco",
                "!",
                "version 16.6",
                "service timestamps debug datetime msec",
                "service timestamps log datetime msec",
                "service call-home",
                "platform qfp utilization monitor load 80",
                "no platform punt-keepalive disable-kernel-core",
                "platform console virtual",
                "platform hardware throughput level MB 10000",
                "!",
                "hostname inet-rtr3",
                "!",
                "boot-start-marker",
                "boot-end-marker",
                "!",
                "!",
                "!",
                "no aaa new-model",
                "!",
                "ip vrf C2",
                "!",
                "ip vrf LR10",
                " rd 10:10",
                " route-target export 10:10",
                " route-target import 10:10",
                "!",
                "ip vrf mgmt",
                " rd 1:1",
                " route-target export 1:1",
                " route-target import 1:1",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "subscriber templating",
                "!",
                "!",
                "!",
                "!",
                "!",
                "mpls label mode all-vrfs protocol bgp-vpnv4 per-vrf",
                "mpls ldp loop-detection",
                "!",
                "!",
                "multilink bundle-name authenticated",
                "!",
                "!",
                "!",
                "!",
                "!",
                "crypto pki trustpoint TP-self-signed-1875639387",
                " enrollment selfsigned",
                " subject-name cn=IOS-Self-Signed-Certificate-1875639387",
                " revocation-check none",
                " rsakeypair TP-self-signed-1875639387",
                "!",
                "crypto pki trustpoint SLA-TrustPoint",
                " enrollment pkcs12",
                " revocation-check crl",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "license udi pid CSR1000V sn 9R4TRPJNNUT",
                "license boot level ax",
                "license smart enable",
                "license smart reservation",
                "diagnostic bootup level minimal",
                "file prompt quiet",
                "spanning-tree extend system-id",
                "!",
                "!",
                "!",
                "username cisco privilege 15 secret 5 $1$F1xa$qAC1FBQE/XXq8e4pbE.fr1",
                "!",
                "redundancy",
                "!",
                "!",
                "!",
                "crypto ikev2 keyring KR",
                " peer All",
                "  address 0.0.0.0 0.0.0.0",
                "  pre-shared-key Cisco123",
                " !",
                "!",
                "!",
                "crypto ikev2 profile default",
                " match identity remote any",
                " authentication remote pre-share",
                " authentication local pre-share",
                " keyring local KR",
                "!",
                "crypto ikev2 profile default2",
                " match fvrf C2",
                " match identity remote any",
                " authentication remote pre-share",
                " authentication local pre-share",
                " keyring local KR",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "crypto ipsec profile LR210",
                " set ikev2-profile default2",
                "!",
                "crypto ipsec profile default",
                " set ikev2-profile default",
                "!",
                "crypto ipsec profile default2",
                " set ikev2-profile default2",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "interface Loopback2",
                " ip vrf forwarding C2",
                " ip address 172.24.3.1 255.255.255.255",
                "!",
                "interface Loopback210",
                " ip vrf forwarding C2",
                " ip address 172.24.3.10 255.255.255.255",
                "!",
                "interface Tunnel2",
                " ip vrf forwarding mgmt",
                " ip address 172.26.1.3 255.255.255.0",
                " no ip redirects",
                " ip nhrp authentication cisco123",
                " ip nhrp map multicast 172.24.230.1",
                " ip nhrp network-id 1",
                " ip nhrp nhs 172.26.1.230 nbma 172.24.230.1",
                " tunnel source Loopback2",
                " tunnel mode gre multipoint",
                " tunnel vrf C2",
                " tunnel protection ipsec profile default2",
                "!",
                "interface Tunnel210",
                " ip vrf forwarding LR10",
                " ip address 172.26.10.3 255.255.255.0",
                " no ip redirects",
                " ip nhrp authentication cisco123",
                " ip nhrp map multicast 172.24.230.10",
                " ip nhrp network-id 1",
                " ip nhrp nhs 172.26.10.230 nbma 172.24.230.10",
                " mpls nhrp",
                " tunnel source Loopback210",
                " tunnel mode gre multipoint",
                " tunnel vrf C2",
                " tunnel protection ipsec profile LR210",
                "!",
                "interface GigabitEthernet1",
                " ip address dhcp",
                " negotiation auto",
                " no mop enabled",
                " no mop sysid",
                "!",
                "interface GigabitEthernet2",
                " ip vrf forwarding C2",
                " ip address 172.34.3.1 255.255.0.0",
                " ip ospf lls disable",
                " negotiation auto",
                " no mop enabled",
                " no mop sysid",
                "!",
                "interface GigabitEthernet3",
                " ip vrf forwarding mgmt",
                " ip address 192.168.3.1 255.255.255.0",
                " ip ospf lls disable",
                " negotiation auto",
                " no mop enabled",
                " no mop sysid",
                "!",
                "interface GigabitEthernet4",
                " no ip address",
                " shutdown",
                " negotiation auto",
                " no mop enabled",
                " no mop sysid",
                "!",
                "interface GigabitEthernet5",
                " no ip address",
                " shutdown",
                " negotiation auto",
                " no mop enabled",
                " no mop sysid",
                "!",
                "interface GigabitEthernet6",
                " no ip address",
                " shutdown",
                " negotiation auto",
                " no mop enabled",
                " no mop sysid",
                "!",
                "interface GigabitEthernet7",
                " no ip address",
                " shutdown",
                " negotiation auto",
                " no mop enabled",
                " no mop sysid",
                "!",
                "interface GigabitEthernet8",
                " no ip address",
                " shutdown",
                " negotiation auto",
                " no mop enabled",
                " no mop sysid",
                "!",
                "interface GigabitEthernet9",
                " no ip address",
                " shutdown",
                " negotiation auto",
                " no mop enabled",
                " no mop sysid",
                "!",
                "interface GigabitEthernet10",
                " no ip address",
                " shutdown",
                " negotiation auto",
                " no mop enabled",
                " no mop sysid",
                "!",
                "!",
                "router eigrp 1",
                " !",
                " address-family ipv4 vrf mgmt autonomous-system 1",
                "  network 0.0.0.0",
                " exit-address-family",
                " !",
                " address-family ipv4 vrf LR10 autonomous-system 10",
                "  network 0.0.0.0",
                " exit-address-family",
                "!",
                "router bgp 100",
                " bgp log-neighbor-changes",
                " !",
                " address-family ipv4 vrf LR10",
                "  redistribute connected",
                "  neighbor 172.25.10.230 remote-as 100",
                "  neighbor 172.25.10.230 activate",
                " exit-address-family",
                "!",
                "!",
                "virtual-service csr_mgmt",
                " ip shared host-interface GigabitEthernet1",
                " activate",
                "!",
                "ip forward-protocol nd",
                "ip http server",
                "ip http authentication local",
                "ip http secure-server",
                "ip route vrf C2 172.24.230.0 255.255.255.0 172.34.0.1",
                "!",
                "ip ssh rsa keypair-name ssh-key",
                "ip ssh version 2",
                "!",
                "!",
                "!",
                "!",
                "!",
                "control-plane",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "line con 0",
                " stopbits 1",
                "line vty 0 4",
                " exec-timeout 0 0",
                " login local",
                " transport input ssh",
                "line vty 5 15",
                " exec-timeout 0 0",
                " login",
                "!",
                "!",
                "!",
                "!",
                "!",
                "!",
                "end"
            ],
            "match": "none",
            "multiline_delimiter": ",",
            "parents": null,
            "provider": {
                "auth_pass": null,
                "authorize": false,
                "host": null,
                "password": null,
                "port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "username": null
            },
            "replace": "block",
            "running_config": null,
            "save_when": "never",
            "src": null
        }
    },
    "updates": [
        "version 16.6",
        "service timestamps debug datetime msec",
        "service timestamps log datetime msec",
        "service call-home",
        "platform qfp utilization monitor load 80",
        "no platform punt-keepalive disable-kernel-core",
        "platform console virtual",
        "platform hardware throughput level MB 10000",
        "hostname inet-rtr3",
        "boot-start-marker",
        "boot-end-marker",
        "no aaa new-model",
        "ip vrf C2",
        "ip vrf LR10",
        "rd 10:10",
        "route-target export 10:10",
        "route-target import 10:10",
        "ip vrf mgmt",
        "rd 1:1",
        "route-target export 1:1",
        "route-target import 1:1",
        "subscriber templating",
        "mpls label mode all-vrfs protocol bgp-vpnv4 per-vrf",
        "mpls ldp loop-detection",
        "multilink bundle-name authenticated",
        "crypto pki trustpoint TP-self-signed-1875639387",
        "enrollment selfsigned",
        "subject-name cn=IOS-Self-Signed-Certificate-1875639387",
        "revocation-check none",
        "rsakeypair TP-self-signed-1875639387",
        "crypto pki trustpoint SLA-TrustPoint",
        "enrollment pkcs12",
        "revocation-check crl",
        "license udi pid CSR1000V sn 9R4TRPJNNUT",
        "license boot level ax",
        "license smart enable",
        "license smart reservation",
        "diagnostic bootup level minimal",
        "file prompt quiet",
        "spanning-tree extend system-id",
        "username cisco privilege 15 secret 5 $1$F1xa$qAC1FBQE/XXq8e4pbE.fr1",
        "redundancy",
        "crypto ikev2 keyring KR",
        "peer All",
        "address 0.0.0.0 0.0.0.0",
        "pre-shared-key Cisco123",
        "crypto ikev2 profile default",
        "match identity remote any",
        "authentication remote pre-share",
        "authentication local pre-share",
        "keyring local KR",
        "crypto ikev2 profile default2",
        "match fvrf C2",
        "crypto ipsec profile LR210",
        "set ikev2-profile default2",
        "crypto ipsec profile default",
        "set ikev2-profile default",
        "crypto ipsec profile default2",
        "interface Loopback2",
        "ip vrf forwarding C2",
        "ip address 172.24.3.1 255.255.255.255",
        "interface Loopback210",
        "ip address 172.24.3.10 255.255.255.255",
        "interface Tunnel2",
        "ip vrf forwarding mgmt",
        "ip address 172.26.1.3 255.255.255.0",
        "no ip redirects",
        "ip nhrp authentication cisco123",
        "ip nhrp map multicast 172.24.230.1",
        "ip nhrp network-id 1",
        "ip nhrp nhs 172.26.1.230 nbma 172.24.230.1",
        "tunnel source Loopback2",
        "tunnel mode gre multipoint",
        "tunnel vrf C2",
        "tunnel protection ipsec profile default2",
        "interface Tunnel210",
        "ip vrf forwarding LR10",
        "ip address 172.26.10.3 255.255.255.0",
        "ip nhrp map multicast 172.24.230.10",
        "ip nhrp nhs 172.26.10.230 nbma 172.24.230.10",
        "mpls nhrp",
        "tunnel source Loopback210",
        "tunnel protection ipsec profile LR210",
        "interface GigabitEthernet1",
        "ip address dhcp",
        "negotiation auto",
        "no mop enabled",
        "no mop sysid",
        "interface GigabitEthernet2",
        "ip address 172.34.3.1 255.255.0.0",
        "ip ospf lls disable",
        "interface GigabitEthernet3",
        "ip address 192.168.3.1 255.255.255.0",
        "interface GigabitEthernet4",
        "no ip address",
        "shutdown",
        "interface GigabitEthernet5",
        "interface GigabitEthernet6",
        "interface GigabitEthernet7",
        "interface GigabitEthernet8",
        "interface GigabitEthernet9",
        "interface GigabitEthernet10",
        "router eigrp 1",
        "address-family ipv4 vrf mgmt autonomous-system 1",
        "network 0.0.0.0",
        "exit-address-family",
        "address-family ipv4 vrf LR10 autonomous-system 10",
        "router bgp 100",
        "bgp log-neighbor-changes",
        "address-family ipv4 vrf LR10",
        "redistribute connected",
        "neighbor 172.25.10.230 remote-as 100",
        "neighbor 172.25.10.230 activate",
        "virtual-service csr_mgmt",
        "ip shared host-interface GigabitEthernet1",
        "activate",
        "ip forward-protocol nd",
        "ip http server",
        "ip http authentication local",
        "ip http secure-server",
        "ip route vrf C2 172.24.230.0 255.255.255.0 172.34.0.1",
        "ip ssh rsa keypair-name ssh-key",
        "ip ssh version 2",
        "control-plane",
        "line con 0",
        "stopbits 1",
        "line vty 0 4",
        "exec-timeout 0 0",
        "login local",
        "transport input ssh",
        "line vty 5 15",
        "login",
        "end"
    ]
}

```
