### ISSUE TITLE
Add users with hash and not password should be idempotent.

### ISSUE THREAD

**Issue by ollylawrence** [ansible-collections/cisco.ios#239]
##### SUMMARY

I understand why adding users in the cisco.ios.ios_user module specify a password isn't idempotent given the resulting hash.

However if you don't specify a password but a has then this should be an idempotent operation.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

cisco.ios.ios_user 

##### ADDITIONAL INFORMATION

The following currently will always cause the configuration to be modified but it doesn't really have to as it has enough information to be idempotent.

Switch config before:

```
username testuser privilege 15 secret 9 $9$hyA2JjazT3Pzga$LRVlszn2uYujX40cpVbrGtzwsFTaMcfeCScDYttfSr2
```

```yaml

  - name: Create testuser
    cisco.ios.ios_user:
      name: testuser
      hashed_password:
        type: 9
        value: $9$hyA2JjazT3Pzga$LRVlszn2uYujX40cpVbrGtzwsFTaMcfeCScDYttfSr2
      privilege: 15
      state: present

```
