### ISSUE TITLE
Inconsistent naming of Loopback interfaces within facts module

### ISSUE THREAD

**Issue by ryanmerolle** [ansible-collections/cisco.ios#241]
##### SUMMARY

Loopback interfaces are presented as loopback<#> or Loopback<3> depending on the fact gathered.  For example l3_interfaces reports the interface as "loopback0", but ansible_net_interfaces reports the interface as "Loopback0".  Its not a massive deal, but because of the inconsistencies, the user has to keep massaging the output so that interface names match exactly if you intend to correlate anything.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_facts

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/test-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/test-user/.local/lib/python3.8/site-packages/ansible
  executable location = /home/test-user/.local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

Ansible runner Ubuntu 20.04.
Target IOS device: ISR 4331 IOS XE 16.12.04 

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

```
ok: [ISR-Test] =>
  ansible_net_interfaces:
    Loopback0:
      bandwidth: 8000000
      description: null
      duplex: null
      ipv4:
      - address: 1.1.1.19
        subnet: '32'
      lineprotocol: up
      macaddress: null
      mediatype: null
      mtu: 1514
      operstatus: up
      type: null
 
TASK [debug] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [ISR-Test] =>
  ansible_network_resources['l3_interfaces']:
  - ipv4:
    - address: 1.1.1.19 255.255.255.255
    name: Loopback0
```

##### ACTUAL RESULTS

```paste below
ok: [ISR-Test] =>
    Loopback0:
      bandwidth: 8000000
      description: null
      duplex: null
      ipv4:
      - address: 1.1.1.19
        subnet: '32'
      lineprotocol: up
      macaddress: null
      mediatype: null
      mtu: 1514
      operstatus: up
      type: null
 
TASK [debug] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [ISR-Test] =>
  ansible_network_resources['l3_interfaces']:
  - ipv4:
    - address: 1.1.1.19 255.255.255.255
    name: loopback0
```
