### ISSUE TITLE
ios_l2_interfaces does not read range of vlans

### ISSUE THREAD

**Issue by BenOoi** [ansible-collections/cisco.ios#245]
##### SUMMARY
I applied allowed_vlans: [ 1,21,231,232,233,234,312 ] and run my playbook.
When looking at the config on my device it shows:

```
interface TenGigabitEthernet1/1/1
 switchport trunk allowed vlan 1,21,231-234,312
 switchport mode trunk
```

Which is correct. When running my playbook again it will send these commands:
```
switchport trunk allowed vlan add 231,232,233,234
```

##### ISSUE TYPE
- A range of vlans is not read correct.

##### COMPONENT NAME
cisco.ios.ios_l2_interfaces

##### ANSIBLE VERSION

```paste below
ansible-2.9.17-2.fc32.noarch
ciscio.ios 1.3.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Fedora 32
Cisio IOS 16.12.4

##### STEPS TO REPRODUCE

Run your playbook twice with successive vlan. For instance 231,232,233,234

```yaml
- name: Merge provided configuration with device configuration
  cisco.ios.ios_l2_interfaces:
    config: "{{ ports }}"
    state: merged
  register: interface
  ignore_errors: yes


vars.yaml
ports:
  - { name: GigabitEthernet1/0/1, mode: trunk, trunk: { native_vlan: 312, allowed_vlans: [ 1,21,231,232,233,234,312 ] } }
```

##### EXPECTED RESULTS

only add the vlan once

##### ACTUAL RESULTS

The same vlans are added multiple times

```paste below

```
