### ISSUE TITLE
State parsed does not add the acl_type field although it's a mandatory field for named ACLs

### ISSUE THREAD

**Issue by ugarix** [ansible-collections/cisco.ios#246]
##### SUMMARY

State parsed does not add the acl_type field although it's a mandatory field for named ACLs
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_acls module, collection version 1.2.1
##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = /home/vagrant/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/ansible/env/lib/python3.8/site-packages/ansible
  executable location = /home/vagrant/ansible/env/bin/ansible
  python version = 3.8.7 (default, Dec 27 2020, 09:01:11) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/vagrant/ansible/ansible.cfg) = ['/home/vagrant/ansible/hosts']
DEFAULT_STDOUT_CALLBACK(/home/vagrant/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/vagrant/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/vagrant/ansible/ansible.cfg) = /home/vagrant/ansible/env/bin/python3.8
```

##### OS / ENVIRONMENT

Centos 7 controller

##### STEPS TO REPRODUCE

Playbook:
```
---
- hosts: ios1
  gather_facts: no
  collections:
  - cisco.ios
  tasks:
  - name: parse configuration
    ios_acls:
      running_config: "{{ lookup('file', 'acl_to_parse.cfg') }}"
      state: parsed
    register: output
  - name: save config to file
    copy:
      content: "{{ {'new_acls' : output.parsed} | to_nice_yaml }}"
      dest: "host_vars/{{ inventory_hostname }}/new_acls.yml"
```
```
(env) [vagrant@server1 ansible]$ more acl_to_parse.cfg 
"ip access-list extended RED
 permit tcp any any eq www
 deny ip any any"
```
```
(env) [vagrant@server1 ansible]$ more host_vars/ios1/new_acls.yml 
new_acls:
-   acls:
    -   aces:
        -   destination:
                any: true
                port_protocol:
                    eq: www
            grant: permit
            protocol: tcp
            source:
                any: true
        -   destination:
                any: true
            grant: deny
            protocol: ip
            protocol_options:
                ip: true
            source:
                any: true
        name: RED
    afi: ipv4
```

This is how I generated the structured data for ACL configuration. 

When I use the render the structured data with this playbook, I get an error saying:
 ACL type value is required for Named ACL!

And indeed module documentation (https://docs.ansible.com/ansible/2.10/collections/cisco/ios/ios_acls_module.html) says that acl_type parameter is mandatory for named ACLs.
```
(env) [vagrant@server1 ansible]$ more resource_rendered.yml 
---
- hosts: ios1
  gather_facts: no
  collections:
  - cisco.ios
  tasks:
  - name: render configuration
    ios_acls:
      config: "{{ new_acls }}"
      state: rendered
    register: output
  - name: save config to file
    copy:
      content: "{{ {'rendered_acls' : output.rendered} | to_nice_yaml }}"
      dest: "host_vars/{{ inventory_hostname }}/rendered_acls.yml"

TASK [render configuration] *********************************************************************************************
fatal: [ios1]: FAILED! => changed=false 
  msg: ACL type value is required for Named ACL!
```

```yaml

```

##### ACTUAL RESULTS

```paste below

```
