### ISSUE TITLE
help with cisco.ios.ios_bgp_address_family module

### ISSUE THREAD

**Issue by IPvSean** [ansible-collections/cisco.ios#302]
##### SUMMARY
error when running base use-case with `cisco.ios.ios_bgp-address_family` 

```
  - name: Use the bgp_global resource module to gather the current config
    cisco.ios.ios_bgp_address_family:
      state: gathered
    register: bgp_address_family
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`cisco.ios.ios_bgp_address_family`

##### ANSIBLE VERSION

```paste below
ansible 2.9.18
  config file = /home/student1/.ansible.cfg
  configured module search path = ['/home/student1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/student1/.ansible.cfg) = ['/home/student1/lab_inventory/hosts']
DEFAULT_STDOUT_CALLBACK(/home/student1/.ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/student1/.ansible.cfg) = 60
DEPRECATION_WARNINGS(/home/student1/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/student1/.ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/student1/.ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/home/student1/.ansible.cfg) = 200
RETRY_FILES_ENABLED(/home/student1/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
```
PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"
```

##### STEPS TO REPRODUCE

```yaml
---
- name: convert configured BGP resource to structured data
  hosts: all
  gather_facts: false
  tasks:
  - name: Use the bgp_global resource module to gather the current config
    cisco.ios.ios_bgp_global:
      state: gathered
    register: bgp_global

  - name: Use the bgp_global resource module to gather the current config
    cisco.ios.ios_bgp_address_family:
      state: gathered
    register: bgp_address_family
```

##### EXPECTED RESULTS
OK OK OK (runs without errors) 

##### ACTUAL RESULTS

```paste below
PLAY [convert configured BGP resource to structured data] **************************************************************************************************************************************
ERROR! failed to combine variables, expected dicts but got a 'dict' and a 'AnsibleUnicode':
{}
"{'bgp_address_family': bgp_address_family['gathered']}"
```
