### ISSUE TITLE
cisco.ios.ios_l2_interfaces - Port templates

### ISSUE THREAD

**Issue by rudimocnik** [ansible-collections/cisco.ios#335]
##### SUMMARY
I would love to have a parameter to choose a port template. The way it would work is to push a port template via jinja2 template and then use it as suggested.
Currently I am using jinja2 template for all my L2 and L3 interface configurations, however this is not optimal as it doesn't give me idempotency. Every push is a change even tho there is no change and the speed is suboptimal. For example, I am always doing "no shutdown" on interface that is marked as "enabled: true"

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Addition to this module cisco.ios.ios_l2_interfaces

##### ADDITIONAL INFORMATION

The feature would enable me to add config lines as defined in the port template without needing a special parameter within the module. I also believe it would improve speed compared to jinja2 templating. 

```yaml

Something like this:

- name: Add port template
  cisco.ios.ios_l2_interfaces:
    config:
    - name: GigabitEthernet0/1
      **template: MY-NAME**  
      mode: access
        vlan: 10


### The template will be defined in the jinja2 template.
template MY-NAME
 storm-control broadcast level 10.00
 storm-control multicast level 10.00
 storm-control unicast level 30.00
 storm-control action trap
 switchport nonegotiate
```
