### ISSUE TITLE
msg": "timeout value 60 seconds reached while trying to send command:

### ISSUE THREAD

**Issue by AK4life** [ansible-collections/cisco.ios#338]
##### SUMMARY
"msg": "timeout value 60 seconds reached while trying to send command: b'install add file flash:/cat3k_caa-universalk9.16.12.04.SPA.bin activate commit'"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
  ansible/module_utils/connection.py

module 
cisco.ios.ios_config

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.1] 
python version = 3.8.5
jinja version = 3.0.1

```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(env: ANSIBLE_PERSISTENT_COMMAND_TIMEOUT) = 2700
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 2700
```

##### OS / ENVIRONMENT

Control node: ubuntu 18.04
Target OS: Cisco IOS_XE

##### STEPS TO REPRODUCE

1- Loading a new IOS file on the switch
2- run the playbook / install IOS using install mode

```yaml
  - name: Install new image 
     ios_command: 
       commands: 
       - command: 'install add file flash:/cat3k_caa-universalk9.16.12.04.SPA.bin activate commit'
         prompt: "This operation may require a reload of the system. Do you want to proceed?"
         answer: 'y'
     vars: 
       ansible_command_timeout: 2699   

   
## Wait for the switch to auto-reboot 

   - name: Wait for device to come back online - This could take up to 10 minutes
     wait_for:
       host: "{{ inventory_hostname }}"
       port: 22
       delay: 60
       timeout: 600
     delegate_to: localhost

```

##### EXPECTED RESULTS

The script waits until the switch installs the ios and Ansible respond to the prompt after the installation takes place

##### ACTUAL RESULTS

fatal: [10.200.140.18]: FAILED! 

```paste below
The full traceback is:
  File "/tmp/ansible_ios_command_payload_vpo1ahtf/ansible_ios_command_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/ios.py", line 141, in run_commands
    return connection.run_commands(commands=commands, check_rc=check_rc)
  File "/tmp/ansible_ios_command_payload_vpo1ahtf/ansible_ios_command_payload.zip/ansible/module_utils/connection.py", line 195, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [10.200.140.18]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                {
                    "answer": "y",
                    "check_all": false,
                    "command": "install add file flash:/cat3k_caa-universalk9.16.12.04.SPA.bin activate commit",
                    "newline": true,
                    "output": null,
                    "prompt": "This operation may require a reload of the system. Do you want to proceed?",
                    "sendonly": false
                }
            ],
            "interval": 1,
            "match": "all",
            "provider": null,
            "retries": 10,
            "wait_for": null
        }
    },
    "msg": "timeout value 60 seconds reached while trying to send command: b'install add file flash:/cat3k_caa-universalk9.16.12.04.SPA.bin activate commit'"
```

**Comment by justjais** [comment]
@AK4life Can you plz try the following play to upgrade instead of the 1 you're trying to use currently and check if it works for you as expected:
Upgrade switch play:
```
---
- hosts: SWITCHES
  gather_facts: no
  connection: network_cli

  tasks:
    - name: IOS CHECKING
      block:

      - name: GATHER ROUTER FACTS
        ios_facts:

      - name: CHECK IF {{ IOS }} ALREADY INSTALLED
        cisco.ios.ios_command:
          commands: "show flash: | inc bin"
        register: showflash

      - name: Print if ios found
        when: "showflash is search(IOS)"
        meta: end_play

      - name: UPGRADE IOS IMAGE IF NOT COMPLIANT
        cisco.ios.ios_command:
          commands:
          - command: "copy {{ FTP }} flash:"
            prompt: '[confirm]' #update the prompt msg you want to check for
            answer: '' #update the expected answer
        register: ftp
```
ref: [Cisco devnet Ansible IOS updater](https://github.com/vipersnews/Ansible-IOS-Updater)
