### ISSUE TITLE
cisco.ios.ios_acls - state replaced not replacing whole acl

### ISSUE THREAD

**Issue by gitouche-sur-osm** [ansible-collections/cisco.ios#344]
##### SUMMARY
After the https://github.com/ansible-collections/cisco.ios/issues/250 fix, I was finally able to use ios_acls without runtime error. However, the `state: replaced` is not behaving as expected. If an ACL is to be modified, it should first be removed `no ip access-list ...`. Instead the ACL is modified in a similar fashion (line by line) to `state: merged`, althought not exactly identical.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_acls 2.2.0
##### ANSIBLE VERSION

```paste below
ansible 2.10.8
  config file = None
  configured module search path = ['/home/cassonne/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cassonne/.local/lib/python3.9/site-packages/ansible
  executable location = /home/cassonne/.local/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
```

##### CONFIGURATION

```paste below
(empty)
```

##### OS / ENVIRONMENT

Fedora release 33 (Thirty Three)
All ansible packages are installed through pip3
ansible-base 2.10.8
ncclient 0.6.10
ansible.netcommon version: 2.0.1
cisco.ios version: 2.2.0
cisco.nxos version: 2.1.1
junipernetworks.junos version: 2.0.1

Target is  WS-C2960S-48FPS-L with IOS 15.0(2a)SE9 . Other versions were tested with similar behaviour.

##### STEPS TO REPRODUCE

access-list standard "demo" on switch is configured as such
```
#show ip access-lists demo
Standard IP access list demo
    20 permit 6.7.8.9
    10 permit 5.6.7.8
```

Playbook:
```yaml
---
- name: demo ACL mixup
  hosts: ios
  gather_facts: false
  tasks:
  - name : Configure acl standard demo
    cisco.ios.ios_acls:
      config:
      - afi: ipv4
        acls:
        - name : demo
          acl_type: standard
          aces :
          - grant: permit
            sequence: 10
            source:
              address: 1.2.3.4
          - grant: permit
            sequence: 20
            source:
              address: 2.3.4.5
      state: replaced
```

##### EXPECTED RESULTS

Expected result with `state: replaced` is for the acl to be removed first then re-written:
```
no ip access-list standard demo
ip access-list standard demo
10 permit 1.2.3.4
20 permit 2.3.4.5
```

##### ACTUAL RESULTS

Each line is replaced individually, leading in unexpected results with more complex ACL.
Full gist : https://gist.github.com/gitouche-sur-osm/aa4ee0a6f0f9e6e6d86de8a189d5556d

```paste below
    "commands": [
        "ip access-list standard demo",
        "no 10 permit 5.6.7.8",
        "10 permit 1.2.3.4",
        "no 20 permit 6.7.8.9",
        "20 permit 2.3.4.5"
    ],

```

**Comment by justjais** [comment]
@gitouche-sur-osm Thanks for logging the issue, and the issue you've talked about WRT to replace is the way replaced state is designed for all of the resource modules where it'll not delete the parent configuration but will negate all of the child attributes of respective ACL as ACL is a critical resource and if the module deletes the entire ACL it might result in to issue at other levels. 

That's why for replace state negation will be done at the child level but not at the parent level and the same goes for the overridden state where if you're trying to override the pre-existing ACL only the child attributes will be negated and new changes will be applied based on want config but the parent attribute will not be negated.

Also, as you've mentioned that with the above run you're getting unexpected out but I've tested the scenario and for me, it's working as expected and have tested it multiple times, ref:
```
"after": [
        {
            "acls": [
                {
                    "aces": [
                        {
                            "grant": "permit",
                            "sequence": 20,
                            "source": {
                                "address": "2.3.4.5"
                            }
                        },
                        {
                            "grant": "permit",
                            "sequence": 10,
                            "source": {
                                "address": "1.2.3.4"
                            }
                        }
                    ],
                    "acl_type": "standard",
                    "name": "demo"
                }
            ],
            "afi": "ipv4"
        }
    ],
    "before": [
        {
            "acls": [
                {
                    "aces": [
                        {
                            "grant": "permit",
                            "sequence": 20,
                            "source": {
                                "address": "6.7.8.9"
                            }
                        },
                        {
                            "grant": "permit",
                            "sequence": 10,
                            "source": {
                                "address": "5.6.7.8"
                            }
                        }
                    ],
                    "acl_type": "standard",
                    "name": "demo"
                }
            ],
            "afi": "ipv4"
        }
    ],
    "changed": true,
    "commands": [
        "ip access-list standard demo",
        "no 10 permit 5.6.7.8",
        "10 permit 1.2.3.4",
        "no 20 permit 6.7.8.9",
        "20 permit 2.3.4.5"
    ],
    "invocation": {
        "module_args": {
            "config": [
                {
                    "acls": [
                        {
                            "aces": [
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "evaluate": null,
                                    "fragments": null,
                                    "grant": "permit",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": null,
                                    "sequence": 10,
                                    "source": {
                                        "address": "1.2.3.4",
                                        "any": null,
                                        "host": null,
                                        "port_protocol": null,
                                        "wildcard_bits": null
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                },
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "evaluate": null,
                                    "fragments": null,
                                    "grant": "permit",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": null,
                                    "sequence": 20,
                                    "source": {
                                        "address": "2.3.4.5",
                                        "any": null,
                                        "host": null,
                                        "port_protocol": null,
                                        "wildcard_bits": null
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                }
                            ],
                            "acl_type": "standard",
                            "name": "demo"
                        }
                    ],
                    "afi": "ipv4"
                }
            ],
            "running_config": null,
            "state": "replaced"
        }
    }
}
```
Although if you still see the issue, I can make the changes for all negate cmd to be fired first and then the config cmd.

**Comment by gitouche-sur-osm** [comment]
Thank you for the explanation. That makes sense.
There must be a subtility I never understood with Cisco (standard?) ACL, here is a more complex example 

Initial state on switch
```
#show ip access-lists demo 
Standard IP access list demo
    10 permit 1.1.1.1
    20 permit 2.2.2.2
    100 deny   any log
```
Playbook
```yaml
---
- name: demo ACL mixup
  hosts: ios
  gather_facts: false
  tasks:
  - name : Configure acl standard demo
    cisco.ios.ios_acls:
      config:
      - afi: ipv4
        acls:
        - name : demo
          acl_type: standard
          aces :
          - grant: permit
            sequence: 10
            source:
              address: 1.1.1.1
          - grant: permit
            sequence: 20
            source:
              address: 2.2.2.2
          - grant: permit
            sequence: 30
            source:
              address: 3.3.3.3
          - grant: deny
            sequence: 990
            source:
              any: true
            log:
              set: true
      state: replaced
```
Commands used (this makes perfect sense with your explanation
```
    "commands": [
        "ip access-list standard demo",
        "30 permit 3.3.3.3",
        "990 deny any log",
        "no 100 deny any log"
    ],
```
Expected result would be the ACL as defined in the playbook
```
    10 permit 1.1.1.1
    20 permit 2.2.2.2
    30 permit 3.3.3.3
   990 deny any log
```
Actual result is 
```
#show ip access-lists demo
Standard IP access list demo
    10 permit 1.1.1.1
    20 permit 2.2.2.2
    30 permit 3.3.3.3
```
If I run the commands step-by-step on the switch, I notice the `990 deny any log` does not add line to the ACL (maybe because `100` is the exact same ace? I never undestood some parts of Cisco ACL logics..). And then 100 gets deleted.

So I don't get the playbook content as result for `state: replaced`
Possible fix would be to execute every `no ...` aces commands before the permit/deny. That works in my use case of standard ACL but will it always works as expected?
