### ISSUE TITLE
ios_static_routes not idempotent with state replaced

### ISSUE THREAD

**Issue by NilashishC** [ansible-collections/cisco.ios#351]
##### SUMMARY
- ios_static_routes not idempotent with state replaced when round tripping gathered facts.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_static_routes

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.1]
  config file = /Users/nchakrab/telstra_demo/ansible.cfg
  configured module search path = ['/Users/nchakrab/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nchakrab/venvs/core/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/nchakrab/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/nchakrab/venvs/core/bin/ansible
  python version = 3.8.7 (default, Mar  4 2021, 19:58:36) [Clang 11.0.3 (clang-1103.0.32.29)]
  jinja version = 2.11.3
  libyaml = True
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Cisco IOS XE Software, Version 17.03.03 on CSR1000v

##### STEPS TO REPRODUCE

On-box config:
```
ip-172-31-32-213#show running-config | section ^ip route
ip route 0.0.0.0 0.0.0.0 GigabitEthernet1 172.31.32.1
ip route 192.0.2.0 255.255.255.0 Null0 200
ip route 192.0.3.0 255.255.255.0 GigabitEthernet3 200
ip route 192.0.4.0 255.255.255.0 GigabitEthernet3 200
ip route vrf GS 0.0.0.0 0.0.0.0 GigabitEthernet1 172.31.32.1 global
```
```yaml
---
- hosts: ios
  gather_facts: no
  tasks:
    - include_tasks: pre.yaml

    - name: "CSRv - Gather existing facts from a Brownfield Environment"
      cisco.ios.ios_facts:
        gather_subset: ['!all', '!min']
        gather_network_resources: ["static_routes"]
    
    - name: "CSRv - Store gathered facts in a flat file - SoT"
      copy:
        content: "{{ ansible_network_resources | to_nice_yaml }}"
        dest: "{{ playbook_dir }}/host_vars/{{ inventory_hostname }}"
    
    - name: Round trip gathered facts
      cisco.ios.ios_static_routes:
        config: "{{ static_routes }}"
        state: replaced
```

##### EXPECTED RESULTS
No changes are made.

##### ACTUAL RESULTS

```paste below
"commands": [
        "no ip route vrf GS 0.0.0.0 0.0.0.0 GigabitEthernet1 172.31.32.1 global",
        "ip route 0.0.0.0 0.0.0.0 GigabitEthernet1 172.31.32.1"
    ],
```
