### ISSUE TITLE
Round trip failures with bgp_global and bgp_address_family

### ISSUE THREAD

**Issue by NilashishC** [ansible-collections/cisco.ios#353]
##### SUMMARY
- Round tripping gathered facts for `bgp_global` and `bgp_address_family` does not work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_bgp_global.py
ios_bgp_address_family.py

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.1]
  config file = /Users/nchakrab/telstra_demo/ansible.cfg
  configured module search path = ['/Users/nchakrab/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nchakrab/venvs/core/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/nchakrab/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/nchakrab/venvs/core/bin/ansible
  python version = 3.8.7 (default, Mar  4 2021, 19:58:36) [Clang 11.0.3 (clang-1103.0.32.29)]
  jinja version = 2.11.3
  libyaml = True
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Cisco IOS XE Software, Version 17.03.03 on CSR1000v

##### STEPS TO REPRODUCE

On-box config:
```
csrv-1#show running-config | section ^router bgp
router bgp 65536
 bgp log-neighbor-changes
 neighbor 172.31.34.28 remote-as 65536
 neighbor 172.31.35.140 remote-as 65536
 !
 address-family ipv4
  network 192.0.2.0
  network 192.0.3.0
  network 192.0.4.0
  neighbor 172.31.34.28 activate
  neighbor 172.31.35.140 activate
 exit-address-family
```

```yaml
---
- hosts: all
  gather_facts: no
  tasks:
    - name: "CSRv - Gather existing facts from a Brownfield Environment"
      cisco.ios.ios_facts:
        gather_network_resources: 
          - bgp_global
          - bgp_address_family
 
    - name: "CSRv - Store gathered facts in a flat file - SoT"
      copy:
        content: "{{ ansible_network_resources | to_nice_yaml }}"
        dest: "{{ playbook_dir }}/host_vars/{{ inventory_hostname }}.yaml"
    
     - name: Remove all BGP config
       cisco.ios.ios_config:
          lines: no router bgp 65536
      
     - name: "CSRv - Configure BGP"
        cisco.ios.ios_bgp_global:
          config: "{{ bgp_global }}"
          state: replaced
      
      - name: "CSRv - Configure BGP Address Family"
        cisco.ios.ios_bgp_address_family:
          config: "{{ bgp_address_family }}"
          state: overridden
```

##### EXPECTED RESULTS

Initial config on the box to be pushed via both the tasks. As in, device should go back to its previous state.

##### ACTUAL RESULTS
"CSRv - Configure BGP" task doesn't configure neighbor remote-as.
"CSRv - Configure BGP Address Family" throws a traceback.
```
 line 601, in iteritems\nAttributeError: 'NoneType' object has no attribute 'items'\n",
```

**Comment by justjais** [comment]
@NilashishC for me `bgp_global` seems to be working as expected and `bgp_af` does have the said issue, but as you've said `activate` is part of AF but that's being rendered under `bgp_global` is correct and an issue. I'll fix that and also the `bgp_af` RT issue.

Play run log: http://paste.openstack.org/show/aGtx6awnbWgW06BPuFuN/

**Comment by NilashishC** [comment]
@justjais The following playbook should help you reproduce the issue.

First run `ansible-playbook test.yaml --tags=gather` then run `ansible-playbook test.yaml --tags=rtt`

The second run will:
(a) Not push `remote-as` commands for neighbors.
(b) Traceback for the bgp_address_family.

As a user, I should be able to restore all my BGP configuration via the modules using round trip.

```yaml
---
- hosts: csr
  gather_facts: no
  tasks:
    - name: Pre-configure
      cisco.ios.ios_config:
        lines:
        - "router bgp 65536"
        - " bgp log-neighbor-changes"
        - " neighbor 172.31.34.28 remote-as 65536"
        - " neighbor 172.31.35.140 remote-as 65536"
        - " !"
        - " address-family ipv4"
        - "  network 192.0.2.0"
        - "  network 192.0.3.0"
        - "  network 192.0.4.0"
        - "  neighbor 172.31.34.28 activate"
        - "  neighbor 172.31.35.140 activate"
        - " exit-address-family"
      tags: gather

    - name: "CSRv - Gather existing facts from a Brownfield Environment"
      cisco.ios.ios_facts:
        gather_subset: ["!all", "!min"]
        gather_network_resources: 
          - bgp_global
          - bgp_address_family
      when: ansible_network_os == "cisco.ios.ios"
      tags: gather
    
    - name: "CSRv - Store gathered facts in a flat file - SoT"
      copy:
        content: "{{ ansible_network_resources | to_nice_yaml }}"
        dest: "{{ playbook_dir }}/host_vars/{{ inventory_hostname }}.yaml"
      tags: gather

    - name: "CSRv - Configure BGP"
      cisco.ios.ios_bgp_global:
        config: "{{ bgp_global }}"
        state: replaced
      when: ansible_network_os == "cisco.ios.ios"
      tags: rtt
    
    - name: "CSRv - Configure BGP Address Family"
      cisco.ios.ios_bgp_address_family:
        config: "{{ bgp_address_family }}"
        state: overridden
      when: ansible_network_os == "cisco.ios.ios"
      tags: rtt
```
