### ISSUE TITLE
cisco.ios.ios_bgp_address_family passes mistyped command to router

### ISSUE THREAD

**Issue by zlojadmin** [ansible-collections/cisco.ios#366]
##### SUMMARY
cisco.ios.ios_bgp_address_family passes mistyped command to router

neighbor 1.1.1.1 prefix_list NAT_ONLY out

Command, router is expecting is 

neighbor 1.1.1.1 prefix-list NAT_ONLY out

With -, not _

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_bgp_address_family

##### ANSIBLE VERSION

```
ansible [core 2.11.1]
```

##### COLLECTION VERSION

```paste below
version 2.2.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: Add PL to peers
        cisco.ios.ios_bgp_address_family:
          config:
            as_number: 65001
            address_family:
              - afi: ipv4
                safi: unicast
                vrf: amad
                neighbor:
                - address: 1.1.1.1
                  prefix_list: 
                    name: NAT_ONLY
                    out: yes
          state: replaced
```

##### ACTUAL RESULTS

```paste below
nsible.module_utils.connection.ConnectionError: neighbor 10.100.23.253 prefix_list NAT_ONLY out
neighbor 10.100.23.253 prefix_list NAT_ONLY out
                             ^
% Invalid input detected at '^' marker.
```
