### ISSUE TITLE
ios_static_routes and ios_facts fails with 'index out of range'

### ISSUE THREAD

**Issue by robindan** [ansible-collections/cisco.ios#367]
##### SUMMARY
When trying to fetch the static routes from a device or when trying to add a new static route on a device that has around 460 static route entries, we always get a *list index out of range* error.

```
    - name: Gather existing routes
      cisco.ios.ios_facts:
        gather_subset: min
        gather_network_resources:
          - static_routes
      register: reg_ios_config
```

Or

```
    - name: Add the requested route
      cisco.ios.ios_static_routes:
        state: merged
        config:
          - address_families:
              - afi: ipv4
                routes:
                  - dest: "{{ ip_prefix }}"
                    next_hops:
                      - forward_router_address: "{{ next_hop }}"
```

Both work fine when using the legacy code (gather_subset config) or legacy module (ios_static_route).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_static_routes
ios_facts with gather_network_resources

##### ANSIBLE VERSION

```
ansible 2.10.6
  config file = /mnt/c/Users/user/Documents/Gitlab/ansible-icon/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/share/virtualenvs/ansible-icon-aZqOzgTG/lib/python3.8/site-packages/ansible
  executable location = /home/user/.local/share/virtualenvs/ansible-icon-aZqOzgTG/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

##### COLLECTION VERSION

```
# /home/user/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  2.3.0  
```

##### EXPECTED RESULTS
Routes to be fetched or added

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_cisco.ios.ios_facts_payload_cfuhu04x/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 133, in get_network_resources_facts
    inst.populate_facts(
  File "/tmp/ansible_cisco.ios.ios_facts_payload_cfuhu04x/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py", line 75, in populate_facts
    obj = self.render_config(
  File "/tmp/ansible_cisco.ios.ios_facts_payload_cfuhu04x/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py", line 224, in render_config
    if is_valid_ip(route[2]):
fatal: [192.0.2.26]: FAILED! => changed=false 
  invocation:
    module_args:
      available_network_resources: false
      gather_network_resources:
      - static_routes
      gather_subset:
      - min
      provider: null
  msg: list index out of range
```
