### ISSUE TITLE
cisco.ios.ios_config does not leave config mode on invalid command

### ISSUE THREAD

**Issue by AliArfan** [ansible-collections/cisco.ios#374]
### Summary

Hi, 

I stumbled upon this thread  while looking for a solution, and thought it perhaps might be a bug or potential feature request: https://github.com/ansible/ansible/issues/32416. When  an invalid command is issued via the  `cisco.ios.ios_config` module   the playbook will fail, but the device remain in configuration mode. Desired outcome is that the playbook leaves the configuration mode, so the next run of the playbook does not fail when setting the terminal parameters.  

### Issue Type

Bug Report

### Component Name

cisco.ios.ios_config

### Ansible Version

```console
$ ansible --version
ansible 2.10.7
  config file = None
  configured module search path = ['/home/ali/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ali/.cache/pypoetry/virtualenvs/nsansible-playbooks-1psT55Hb-py3.9/lib/python3.9/site-packages/ansible
  executable location = /home/ali/.cache/pypoetry/virtualenvs/nsansible-playbooks-1psT55Hb-py3.9/bin/ansible
  python version = 3.9.4 (default, Apr  9 2021, 01:03:21) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
Empty, no output
```

### OS / Environment

Ubuntu 20.04 (Windows 10 WSL)

### Steps to Reproduce

Playbook to reproduce the problem, where invalid configuration is pushed
```yaml (paste below)
- name: Validate configuration after push
  hosts: "{{ DEVICE }}"
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Push new configuration
      cisco.ios.ios_config:
          lines:
            vrf definition Test description 'Failingcommand'"

```

### Expected Results

Playbook leaves the configuration mode, so the next run does not fail to set terminal parameters.

### Actual Results

```console
Results in the device staying in the configuration mode:

Test-Device(config)#vrf definition Test description 'Failingcommand'"
vrf definition Test description 'Failingcommand'"
                    ^
% Invalid input detected at '^' marker.

Test-Device(config)#
```

**Comment by KB-perByte** [comment]
Hi @AliArfan,
In any given case the prompt is expected to reset and reach config mode on using the config module which resets the prompt.
We are unable to reproduce the issue you reported, at our end. Can you please specify what you mean by **'so the next run does not fail to set terminal parameters'** in _Expected_ result? Or help us with an example with its verbose output.

**Comment by AliArfan** [comment]
Hi, 

Thank you for your reply.  

We  have a playbook which changes the configuration on the device, and the commands are provided trough a variable. We are running this playbook towards virtual nodes in Cisco Modeling Labs.  

My Test inventory: 
```yaml (paste below)
all:
  hosts:
    test_device:
      ansible_network_os: ios
      ansible_user: user@a1234/n4/0
      ansible_host: 127.0.0.1
      ansible_port: 3000
      ansible_become: yes
      ansible_become_method: enable
```
Test-playbook:
```yaml (paste below)
- name: Example to showcase playbook not leaving configuration mode
  hosts: test_device
  gather_facts: no
  connection: network_cli

  tasks:
  - name: Push new configuration
    cisco.ios.ios_config:
      lines:
        vrf definition Test description 'Failingcommand'"
    register: config_before
```

After this run, the terminal on the device will show the following:
```console
Test-Device(config)#vrf definition Test description 'Failingcommand'"
vrf definition Test description 'Failingcommand'"
                    ^
% Invalid input detected at '^' marker.

Test-Device(config)#
```
I have attached the traceback from the verbose output as a file, due to it being a large output. Filename: failed_command.txt
 
### Running playbook again with corret Syntax
We have now fixed the  syntax error, and are running the playbook again.

```yaml (paste below)
  - name: Push new configuration
    cisco.ios.ios_config:
      lines:
        - vrf definition Test
        - description "Failingcommand"
    register: config_before
```

It will result in the following console error:
```console
Test-DeviceE(config)#
Test-Device(config)#terminal length 0
terminal length 0
         ^
% Invalid input detected at '^' marker.

Test-Device(config)#
```

I have also attached the verbose output as a file, with filename: failed_to_set_terminal.txt
[failed_command.txt](https://github.com/ansible-collections/cisco.ios/files/6828779/failed_command.txt)
[failed_to_set_terminal.txt](https://github.com/ansible-collections/cisco.ios/files/6828781/failed_to_set_terminal.txt)
