### ISSUE TITLE
ios_facts can not parse vlan names with spaces / #375 erronously closed

### ISSUE THREAD

**Issue by donnerhacke** [ansible-collections/cisco.ios#376]
Please reopen #375 or handle this ticket here.

**Comment by donnerhacke** [comment]
```yaml
- name: Test VLAN Bug
  hosts: switch
  gather_facts: no
  vars:
    vlan_name: "test vlan"
    vlan_id: 109

  tasks:
    - name: Create VLAN
      ios_vlans:
        config:
         - name: "{{ vlan_name }}"
           vlan_id: "{{ vlan_id }}"
           state: active
        state: merged

    - name: Validate VLAN
      ios_command:
        commands:
          - "show vlan brief | include _{{ vlan_id }}_"
      register: res

    - name: Show output
      debug:
         var: res.stdout

    - name: Gather facts
      ios_facts:
        gather_network_resources:
          - vlans

    - name: Show facts
      debug:
         var: ansible_facts.network_resources.vlans |
           selectattr('vlan_id', '==', vlan_id)

    - fail:
      when: ansible_facts.network_resources.vlans |
           selectattr('vlan_id', '==', vlan_id) |
           map(attribute = 'name') != [ vlan_name ]

    - name: Remove VLAN
      ios_vlans:
        config:
          - vlan_id: "{{ vlan_id }}"
        state: deleted
```

should return:
```
PLAY [Test VLAN Bug] ***********************************************************

TASK [Create VLAN] *************************************************************
changed: [switch]

TASK [Validate VLAN] ***********************************************************
ok: [switch]

TASK [Show output] *************************************************************
ok: [switch] => {
    "res.stdout": [
        "109  test vlan                        active"
    ]
}

TASK [Gather facts] ************************************************************
ok: [switch]

TASK [Show facts] **************************************************************
ok: [switch] => {
    "ansible_facts.network_resources.vlans | selectattr('vlan_id', '==', vlan_id)": [
        {
            "mtu": 1500,
            "name": "test vlan",
            "shutdown": "disabled",
            "state": "active",
            "vlan_id": 109
        }
    ]
}

TASK [fail] ********************************************************************
skipping: [switch]

TASK [Remove VLAN] *************************************************************
changed: [switch]

PLAY RECAP *********************************************************************
switch    : ok=6    changed=2    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
```

but it actually does return:
```
PLAY [Test VLAN Bug] ***********************************************************

TASK [Create VLAN] *************************************************************
changed: [switch]

TASK [Validate VLAN] ***********************************************************
ok: [switch]

TASK [Show output] *************************************************************
ok: [switch] => {
    "res.stdout": [
        "109  test vlan                        active"
    ]
}

TASK [Gather facts] ************************************************************
ok: [switch]

TASK [Show facts] **************************************************************
ok: [switch] => {
    "ansible_facts.network_resources.vlans | selectattr('vlan_id', '==', vlan_id)": [
        {
            "mtu": 1500,
            "name": "test",
            "shutdown": "disabled",
            "vlan_id": 109
        }
    ]
}

TASK [fail] ********************************************************************
fatal: [switch]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
switch    : ok=5    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
