### ISSUE TITLE
Improve IOS_NTP to manage multiple NTP Peers

### ISSUE THREAD

**Issue by MasonDobbins** [ansible-collections/cisco.ios#403]
##### SUMMARY

Should be able to add multiple peers ("server") to IOS configuration and remove any peers that are not in the list.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ios_ntp

##### ADDITIONAL INFORMATION
The module should work in the same way name-servers are managed in ios_system. You give the module a list of servers and only those servers remain in the IOS running-config of the device.

##### Example
```yaml
# Set new NTP server and source interface
- ios_ntp:
    server: 
      - 10.0.255.10
      - 10.1.254.20

```
If 10.1.255.15 exist in the ios config of the device, it would be removed and only the listed servers would remain.
