### ISSUE TITLE
cisco.ios.ios_command_module example and parameter sections are contradictory.

### ISSUE THREAD

**Issue by ollylawrence** [ansible-collections/cisco.ios#410]
##### SUMMARY

In the parameters for command:

"Common answers are 'y' or "\r" (carriage return, must be double quotes). See examples"

Though in the example single quotes are used:

- name: run commands that require answering a prompt
  cisco.ios.ios_command:
    commands:
    - command: 'clear counters GigabitEthernet0/1'
      prompt: 'Clear "show interface" counters on this interface \[confirm\]'
      answer: 'y'
    - command: 'clear counters GigabitEthernet0/2'
      prompt: '[confirm]'
      answer: '\r'

This is contradicting and the single quote example doesn't work.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
https://github.com/ansible-collections/cisco.ios/blob/main/docs/cisco.ios.ios_config_module.rst

##### ANSIBLE VERSION

```
ansible 2.9.23
  config file = /home/ol2355/.ansible.cfg
  configured module search path = [u'/home/ol2355/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Feb 27 2021, 15:10:58) [GCC 7.5.0]

```

**Comment by KB-perByte** [comment]
Hey @ollylawrence I am not able to reproduce the exact issue at my end, can you please share the error that you get on 
```
    - name: run commands that require answering a prompt
      cisco.ios.ios_command:
        commands:
        - command: 'clear counters GigabitEthernet0/1'
          prompt: 'Clear "show interface" counters on this interface \[confirm\]'
          answer: y
```
as it works as expected for me.
Thanks
