### ISSUE TITLE
cisco.ios.ios_ospfv2 not working as intended when using replaced or overridden states

### ISSUE THREAD

**Issue by bxijyoo** [ansible-collections/cisco.ios#412]
##### SUMMARY
Using the replaced and overridden states - resource does a good job of adding new configs, configs do not get removed/readded properly.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_ospfv2

##### ANSIBLE VERSION
```
ansible 2.10.6
  config file = /home/bxadmin/scripts/bx-network-configs/ansible.cfg
  configured module search path = ['/home/bxadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bxadmin/venvp3_ansible2.10/lib/python3.6/site-packages/ansible
  executable location = /home/bxadmin/venvp3_ansible2.10/bin/ansible
  python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
```

##### COLLECTION VERSION
```
Collection Version
---------- -------
cisco.ios  2.3.1  
```

##### CONFIGURATION
```
DEFAULT_GATHER_TIMEOUT(/home/bxadmin/scripts/bx-network-configs/ansible.cfg) = 30
DEPRECATION_WARNINGS(/home/bxadmin/scripts/bx-network-configs/ansible.cfg) = False
HOST_KEY_CHECKING(/home/bxadmin/scripts/bx-network-configs/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/bxadmin/scripts/bx-network-configs/ansible.cfg) = 60
```

##### OS / ENVIRONMENT
Virtual - Cisco virtual IOS in CML-P (VIRL 2.0)
Cisco IOS Software, vios_l2 Software (vios_l2-ADVENTERPRISEK9-M), Experimental Version 15.2(20200924:215240) [sweickge-sep24-2020-l2iol-release 135]

Physical - Cisco IOS XE Software, Version 17.03.03

##### STEPS TO REPRODUCE
1. Apply configuration with two passive interfaces
```
  - name: configure ospf
    cisco.ios.ios_ospfv2:
      config:
        processes:
        - areas:
          - area_id: '51'
          network:
          - address: 10.1.0.0
            area: '51'
            wildcard_bits: 0.0.255.255
          passive_interfaces:
            default: true
            interface:
              name:
              - TenGigabitEthernet5/0/1
              - TenGigabitEthernet6/0/1
              set_interface: false
          process_id: 1
      state: overridden  
```

2. Adjust one of the two interfaces by renaming one (TenGigabitEthernet5/0/1 -> 5/0/2) (test case 1)
```
  - name: configure ospf
    cisco.ios.ios_ospfv2:
      config:
        processes:
        - areas:
          - area_id: '51'
          network:
          - address: 10.1.0.0
            area: '51'
            wildcard_bits: 0.0.255.255
          passive_interfaces:
            default: true
            interface:
              name:
              - TenGigabitEthernet5/0/2
              - TenGigabitEthernet6/0/1
              set_interface: false
          process_id: 1
      state: overridden  
```

3. Run playbook and observe result using -vvvv
4. Readjust passive interface back to 5/0/1 (test case 2)
```
  - name: configure ospf
    cisco.ios.ios_ospfv2:
      config:
        processes:
        - areas:
          - area_id: '51'
          network:
          - address: 10.1.0.0
            area: '51'
            wildcard_bits: 0.0.255.255
          passive_interfaces:
            default: true
            interface:
              name:
              - TenGigabitEthernet5/0/1
              - TenGigabitEthernet6/0/1
              set_interface: false
          process_id: 1
      state: overridden  
```

5. Run playbook and observe result

##### EXPECTED RESULTS
Expect resource to remove 5/0/1 and add 5/0/2 as shown below (test case 1)
```
"commands": [
        "router ospf 1",
        "no passive-interface TenGigabitEthernet5/0/1",
        "passive-interface TenGigabitEthernet5/0/2"
    ],
```

Expect resource to remove 5/0/1 and add 5/0/2 as shown below (test case 2)
```
"commands": [
        "router ospf 1",
        "passive-interface TenGigabitEthernet5/0/2",
        "no passive-interface TenGigabitEthernet5/0/1"
    ],
```

##### ACTUAL RESULTS
Actual shows that it's trying to remove 5/0/2 (test case 1) and applies config shown below
```
    "commands": [
        "router ospf 1",
        "no passive-interface TenGigabitEthernet5/0/2"
    ],
```

Actual shows that there are no changes to be made (test case 2)
```
    "commands": [
        "router ospf 1"
    ]
```
