### ISSUE TITLE
ios_l2_interfaces: does not set switchport mode correctly

### ISSUE THREAD

**Issue by eleksis** [ansible-collections/cisco.ios#413]
##### SUMMARY

In certain scenario module does not add command to set switchport mode from access to trunk.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_l2_interfaces.py

##### VERSIONS

```paste below
ansible 2.9.13
cisco.ios collection 2.3.1
switch C2960CX, 15.2(5)E1
```

##### STEPS TO REPRODUCE

Initial state on device:
```
interface GigabitEthernet0/9
 switchport access vlan 3
 switchport trunk allowed vlan 1,3
 switchport mode access
```
Task:
```yaml
  - cisco.ios.ios_l2_interfaces:
      config:
        - name: GigabitEthernet0/9
          mode: trunk
          trunk:
            allowed_vlans: 1,3
            native_vlan: 1
      state: merged
```
Commands generated by this module (verbose output):
```
"commands": ["interface GigabitEthernet0/9", "switchport trunk native vlan 1"]
```

##### EXPECTED RESULTS

Change mode from access to trunk.
Missing command: `"switchport mode trunk"`

##### ACTUAL RESULTS

Nothing changed.
State on device after playbook execution:
```
interface GigabitEthernet0/9
 switchport access vlan 3
 switchport trunk allowed vlan 1,3
 switchport mode access
```
