### ISSUE TITLE
ios_ntp_global rendering asterisk instead of integer values when defining server or peer key

### ISSUE THREAD

**Issue by ledgley** [ansible-collections/cisco.ios#435]
##### SUMMARY
When defining a server or peer key as either an integer or a string, the module output is rendering asterisk's in place of all values in the output that match that integer value.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_ntp_global

##### ANSIBLE VERSION
```
ansible 2.9.22
  config file = /Users/edgleyl/.ansible.cfg
  configured module search path = ['/Users/edgleyl/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/edgleyl/venv/two-nine/lib/python3.7/site-packages/ansible
  executable location = /Users/edgleyl/venv/two-nine/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:03) [Clang 11.0.0 (clang-1100.0.33.17)]
```
and
```
ansible 2.10.12
  config file = /Users/edgleyl/.ansible.cfg
  configured module search path = ['/Users/edgleyl/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/edgleyl/venv/two-ten/lib/python3.7/site-packages/ansible
  executable location = /Users/edgleyl/venv/two-ten/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:03) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### COLLECTION VERSION
```
# /Users/edgleyl/venv/two-ten/lib/python3.7/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  2.5.0

# /Users/edgleyl/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  2.5.0
```

##### CONFIGURATION
```
(two-ten) edgleyl@edgleyl-JSS1242 compliance % ansible-config dump --only-changed
DEFAULT_CALLBACK_WHITELIST(/Users/edgleyl/.ansible.cfg) = ['timer']
HOST_KEY_CHECKING(/Users/edgleyl/.ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/edgleyl/.ansible.cfg) = 180
```

##### OS / ENVIRONMENT
MacOS 11.6
Using `state: rendered` so I don't think device firmware is relevant.

##### STEPS TO REPRODUCE
Use ios_ntp_global module to render device specific configuration

```yaml
  tasks:

    - name: CONFIGURE NTP
      cisco.ios.ios_ntp_global:
        config:
          authenticate: True
          authentication_keys:
            - algorithm: md5
              id: 1
              key: secretkey
          trusted_keys:
            - range_start: 1
          master:
            stratum: 5
          peers:
            - peer: 10.10.99.99
              key: 1
            - peer: 20.20.99.99
              key: 1
          source: Loopback1
          update_calendar: True
        state: rendered
      register: output

    - debug: var=output.rendered
```

##### EXPECTED RESULTS
```
TASK [debug] ***********************************************************************************************************************************************
ok: [mw-prii-s01] => {
    "output.rendered": [
        "ntp authenticate",
        "ntp master 5",
        "ntp source Loopback1",
        "ntp update-calendar",
        "ntp peer 10.10.99.99 key 1",
        "ntp peer 20.20.99.99 key 1",
        "ntp trusted-key 1
```

##### ACTUAL RESULTS
all instances of `1` are replaced with `********`

This happens regardless of the integer value given at the `key` parameter (ie. 1, 2, 5 etc).

It happens for both servers and peers params.

It also happens regardless of whether you provide a quoted integer (as a string) or just an integer

```
TASK [debug] ***********************************************************************************************************************************************
ok: [mw-prii-s01] => {
    "output.rendered": [
        "ntp authenticate",
        "ntp master 5",
        "ntp source Loopback********",
        "ntp update-calendar",
        "ntp peer ********0.********0.99.99 key ********",
        "ntp peer 20.20.99.99 key ********",
        "ntp trusted-key ********"
    ]
}
```

**Comment by ledgley** [comment]
This is happening with `state: gathered` also.

```json
            "peers": [
                {
                    "key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "peer": "204.20.240.********"
                },
                {
                    "key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "peer": "204.20.240.2"
                },
                {
                    "key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "peer": "204.2********.240.2"
                }
            ],
```

**Comment by ledgley** [comment]
I guess this has to do with the module thinking that the value given as the ID parameter is the actual key, not the key ID, and is obfuscating the value.

**Comment by KB-perByte** [comment]
hey @ledgley this is not a bug, if the value in the context is similar to the attribute in which `no_log` parameter is specified in the argspec, it will mask it in all the logs. That is expected behavior. Ref [argspec](https://github.com/ansible-collections/cisco.ios/blob/195233ddbbe982aafaffe83f37cee085db98a92c/plugins/module_utils/network/ios/argspec/ntp_global/ntp_global.py#L101).

**Comment by ledgley** [comment]
Thank you @KB-perByte though this does seem to make the gathered and rendered functions of this module completely unusable.

In the example provided above, the value that is being hidden by the asterisk is the **ID** of the secret key value, not the secret key value itself. Perhaps I don't have a full understanding, but why are the ID values considered to be secret? They are not hashed/encrypted in the actual device configuration.

In the example above, I have not even specified a secret value in my variables and I can't even render the configuration because the ID value is being replaced with the asterisks.

In fact, if I were to configure two separate keys, say key ID 1 and key ID 2 as such
```yaml
    - name: CONFIGURE NTP
      cisco.ios.ios_ntp_global:
        config:
          authenticate: True
          authentication_keys:
            - algorithm: md5
              encryption: 7
              id: 1
              key: supersecret1
            - algorithm: md5
              encryption: 7
              id: 2
              key: supersecret2
          trusted_keys:
            - range_start: 1
              range_end: 2
          access_group:
            peer:
              - access_list: '90'
                ipv4: True
            serve_only:
              - access_list: '91'
          master:
            stratum: 5
          peers:
            - peer: 204.20.240.1
              prefer: True
              key: 1
            - peer: 204.20.240.2
              key: 2
          source: Loopback1
        state: rendered
      register: output
```

The output would be so butchered that I can't even use any kind of search and replace to fix the obfuscated characters because I don't know which asterisk string should be a 1 and which should be a 2:
```
TASK [debug] *************************************************************************************************************************************************
ok: [mw-prii-s01] => {
    "output": {
        "changed": false,
        "failed": false,
        "rendered": [
            "ntp authenticate",
            "ntp master 5",
            "ntp source Loopback********",
            "ntp access-group ipv4 peer 90",
            "ntp access-group serve-only 9********",
            "ntp authentication-key ******** md5 ******** 7",
            "ntp authentication-key ******** md5 ******** 7",
            "ntp peer ********04.********0.********40.******** key ******** prefer",
            "ntp peer ********04.********0.********40.******** key ********",
            "ntp trusted-key ******** - ********"
        ]
    }
}
```
