### ISSUE TITLE
ios_bgp_address_family takes longer than expected to run

### ISSUE THREAD

**Issue by dstogsdill** [ansible-collections/cisco.ios#451]
##### SUMMARY
The ios_bgp_address_family module takes ~40s to complete a task using state 'gathered'.  I'm unsure if other states (merged, replace, etc) are affected at the moment. 

Other modules such as ios_command & ios_facts seem to process in normal times (~1s).  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_bgp_address_family 

##### ANSIBLE VERSION
```
ansible [core 2.11.6] 
  config file = /Users/dastogsdill/GHE/ansible-test/lab/failover_testing/ansible.cfg
  configured module search path = ['/Users/dastogsdill/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dastogsdill/GHE/ansible-test/venv38/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/dastogsdill/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/dastogsdill/GHE/ansible-test/venv38/bin/ansible
  python version = 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) [Clang 6.0 (clang-600.0.57)]
  jinja version = 3.0.2
  libyaml = True

```

##### COLLECTION VERSION
```
# /Users/dastogsdill/GHE/ansible-test/venv38/lib/python3.8/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  2.5.0  

# /Users/dastogsdill/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  2.5.0  

```

##### CONFIGURATION

```
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names to new standard, use callbacks_enabled instead. This feature will be removed from ansible-core in version 2.15. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
CALLBACKS_ENABLED(/Users/dastogsdill/GHE/ansible-test/lab/failover_testing/ansible.cfg) = ['profile_tasks']

```

##### OS / ENVIRONMENT
MacOS BIgSur 11.6
Python 3.8

##### STEPS TO REPRODUCE

```yaml
- name: Get Primary ISP BGP Config Before Change
  ios_bgp_address_family:
    config:
    state: gathered
  register: primaryconfigbefore
  no_log: False
  connection: network_cli
  when:
    - inventory_hostname in groups[primary_isp.router]

- name: Get Secondary ISP BGP Config Before Change
  ios_bgp_address_family:
    config:
    state: gathered
  register: secondaryconfigbefore
  no_log: False
  connection: network_cli
  when:
    - inventory_hostname in groups[secondary_isp.router]

- name: Get Tertiary ISP BGP Config Before Change
  ios_bgp_address_family:
    config:
    state: gathered
  register: tertiaryconfigbefore
  no_log: False
  connection: network_cli
  when:
    - inventory_hostname in groups[tertiary_isp.router]
```

##### EXPECTED RESULTS
Each task should take 1-2s to complete

##### ACTUAL RESULTS
Tasks take ~40s each to complete

```
Wednesday 03 November 2021  10:58:26 -0400 (0:00:00.057)       0:02:17.382 **** 
=============================================================================== 
Get Tertiary ISP BGP Config Before Change ------------------------------------------------------------- 42.50s
Get Secondary ISP BGP Config Before Change ---------------------------------------------------------- 39.41s
Get Primary ISP BGP Config Before Change ------------------------------------------------------------- 39.37s

```
