### ISSUE TITLE
logging_global not rendering ipv6 host commands from config

### ISSUE THREAD

**Issue by KB-perByte** [ansible-collections/cisco.ios#454]
##### SUMMARY

logging_global skips a few commands on IOS while the host is configured with ipv6 address and transport section is defined
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_logging_global

##### ANSIBLE VERSION

```paste below
2.11
```

##### COLLECTION VERSION

```paste below
2.4.+
```

##### CONFIGURATION

```paste below
logging host 172.16.1.1
logging host 172.16.1.11 xml
logging host 172.16.1.25 filtered
logging host 172.16.1.10 filtered stream 10
logging host 172.16.1.13 transport tcp port 514
logging host ipv6 2001:DB8:00:04:00:00:00:32 transport udp port 23 filtered session-id string 10.0.2.1
```

##### OS / ENVIRONMENT

fedora

##### STEPS TO REPRODUCE

```yaml
---
- name: logging PARSED state
  hosts: selfxe
  gather_facts: no
  tasks:
  - name: parsed play
    cisco.ios.ios_logging_global:
      running_config: "{{ lookup('file', 'logging.cfg') }}"
      state: parsed
    register: some_data
    # check_mode: yes
```

##### EXPECTED RESULTS

ipv6 entry to be rendered

##### ACTUAL RESULTS

ipv6 entry not getting rendered

```paste below
        "hosts": [
            {
                "hostname": "172.16.1.1"
            },
            {
                "filtered": true,
                "hostname": "172.16.1.10",
                "stream": 10
            },
            {
                "hostname": "172.16.1.11",
                "xml": true
            },
            {
                "hostname": "172.16.1.13",
                "transport": {
                    "tcp": {
                        "port": 514
                    }
                }
            },
            {
                "filtered": true,
                "hostname": "172.16.1.25"
            }
        ],
```
