### ISSUE TITLE
ios_facts does not retrieve line protocol information for physical interfaces using ansible core 2.11.1

### ISSUE THREAD

**Issue by zaskan** [ansible-collections/cisco.ios#489]
##### SUMMARY

ios_facts does not retrieve line protocol information for physical interfaces using ansible core 2.11.1
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

IOS_FACTS
##### ANSIBLE VERSION

```paste below
2.11.1
```

```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below
ansible [core 2.11.1] 
  config file = /home/xxxxxxxx/environments/ansible_core_2.11/ansible.cfg
  configured module search path = ['/usr/share/my_modules']
  ansible python module location = /srv/share/ansible-core-2.11-venv-1/lib64/python3.6/site-packages/ansible
  ansible collection location = /home/xxxxxxxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /srv/share/ansible-core-2.11-venv-1/bin/ansible
  python version = 3.6.8 (default, Aug 13 2020, 07:46:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
  jinja version = 3.0.1
```

##### OS / ENVIRONMENT

IOS: Version 15.5(1)SY4, hardware is C6800 Series
IOS XE: Version 16.09.05, hardware is WS-C3850-48P
IOS XE: Version 16.12.3s, hardware is C9300-48UXM/ C9500-48Y4C

##### STEPS TO REPRODUCE

```yaml

Playbook
---
# Gather facts from switches
- name: Gather facts from switches
  hosts:
    - c6880-x-le
    - c9300
    - c9500
    - ws-c3850
  serial: 1   # https://github.com/ansible/ansible/issues/40140
  connection: network_cli

  vars:
    playbook_name: gather_facts_office.yml

  vars_files:
    - ../credentials.yml

  roles:
    - roles/gather_facts_localhost
    - roles/gather_facts_office


roles/gather_facts_office/tasks/main.yml
---
# tasks file for roles/gather_facts_office

# Gather interfaces facts
- name: Gather interfaces facts
  ios_facts:
    gather_subset: interfaces


Debug ansible_net_interfaces
ok: [REDACTED] => {
    "ansible_net_interfaces": {
        "TenGigabitEthernet2/5/5": {
            "bandwidth": 1000000,
            "description": "free",
            "duplex": null,
            "ipv4": [],
            "lineprotocol": null,
            "macaddress": "REDACTED",
            "mediatype": "1000BaseLH",
            "mtu": 1500,
            "operstatus": "down",
            "type": "C6k 10000Mb 802.3"
        }

```
It is not retrieving the line protocol information for the physical interfaces anymore like it did in version 2.4.2.0. We are running this playbook against both IOS and IOS XE devices.

##### EXPECTED RESULTS

It should return lineprotocol as before.

##### ACTUAL RESULTS

It is not returning lineprotocol information.
