### ISSUE TITLE
ios_interfaces and ios_banner - register: in check mode does not work

### ISSUE THREAD

**Issue by gdykeman** [ansible-collections/cisco.ios#52]
##### SUMMARY
ios_interfaces and ios_banner shows a change in check mode.  However, when registering that variable, it's showing up as empty.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_interfaces
ios_banner

##### ANSIBLE VERSION
```
ansible 2.9.9
  config file = /Users/gdykeman/Documents/Ansible/ansible_locker/ansible.cfg
  configured module search path = ['/Users/gdykeman/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/gdykeman/Documents/Ansible/environments/network/lib/python3.7/site-packages/ansible
  executable location = /Users/gdykeman/Documents/Ansible/environments/network/bin/ansible
  python version = 3.7.5 (default, Nov  1 2019, 02:16:32) [Clang 11.0.0 (clang-1100.0.33.8)]
```

##### CONFIGURATION
```
DEFAULT_CALLBACK_WHITELIST(/Users/gdykeman/Documents/Ansible/ansible_locker/ansible.cfg) = ['time']
DEFAULT_FORKS(/Users/gdykeman/Documents/Ansible/ansible_locker/ansible.cfg) = 50
DEFAULT_HOST_LIST(/Users/gdykeman/Documents/Ansible/ansible_locker/ansible.cfg) = ['/Users/gdykeman/Documents/Ansible/ansible_locker/inventory/dev/dev_hosts.yaml']
DEFAULT_NO_TARGET_SYSLOG(/Users/gdykeman/Documents/Ansible/ansible_locker/ansible.cfg) = False
DEFAULT_PRIVATE_KEY_FILE(/Users/gdykeman/Documents/Ansible/ansible_locker/ansible.cfg) = /Users/gdykeman/.ssh/gdykeman-dev-network.pem
DEFAULT_SCP_IF_SSH(/Users/gdykeman/Documents/Ansible/ansible_locker/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/Users/gdykeman/Documents/Ansible/ansible_locker/ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(/Users/gdykeman/Documents/Ansible/ansible_locker/ansible.cfg) = /Users/gdykeman/Documents/Ansible/z_misc/vault.txt
HOST_KEY_CHECKING(/Users/gdykeman/Documents/Ansible/ansible_locker/ansible.cfg) = False
INTERPRETER_PYTHON(/Users/gdykeman/Documents/Ansible/ansible_locker/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/Users/gdykeman/Documents/Ansible/ansible_locker/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/Users/gdykeman/Documents/Ansible/ansible_locker/ansible.cfg) = 200
RETRY_FILES_ENABLED(/Users/gdykeman/Documents/Ansible/ansible_locker/ansible.cfg) = False
```

##### OS / ENVIRONMENT
MacOS Mojave 10.14.6

##### STEPS TO REPRODUCE
```
  - name: Configure interfaces with provided data model
    ios_interfaces:
      config: "{{ interfaces }}"
      state: replaced
    register: net_interfaces
    check_mode: yes
```
```
    ios_banner:
      banner: motd
      text: "{{ lookup('template', 'motd.j2') }}"
      state: present
    register: net_motd
    check_mode: yes
```
```
interfaces:
-   enabled: true
    name: loopback0
-   enabled: true
    name: GigabitEthernet1
-   enabled: true
    name: loopback5
```
```
Hostname: {{ inventory_hostname }}
Model: {{ ansible_net_model }}
Serial Number: {{ ansible_net_serialnum }}
Version: {{ ansible_net_version }}
```
##### EXPECTED RESULTS
Registered variable to contain "commands"

##### ACTUAL RESULTS
```
TASK [network_banner : Configure the MOTD] ***********************************************************************************
changed: [cisco1] => changed=true
  commands:
  - |-
    banner motd @
    Hostname: cisco1
    Model: CSR1000V
    Serial Number: 9N74GJXNW2N
    Version: 16.09.02
    @
```
```
TASK [debug] *****************************************************************************************************************
ok: [cisco1] =>
  net_motd:
    changed: false
    skip_reason: Conditional result was False
    skipped: true
```
```
TASK [network_interfaces : Configure interfaces with provided data model] ****************************************************
changed: [cisco1] => changed=true
  after:
  - enabled: true
    name: loopback0
  - enabled: true
    name: GigabitEthernet1
  before:
  - enabled: true
    name: loopback0
  - enabled: true
    name: GigabitEthernet1
  commands:
  - interface loopback5
  - no shutdown
```
```
TASK [debug] *****************************************************************************************************************
ok: [cisco1] =>
  net_interfaces:
    changed: false
    skip_reason: Conditional result was False
    skipped: true
```
