### ISSUE TITLE
ios_command module failing Task if one of the command in list of commands not working

### ISSUE THREAD

**Issue by alihyder-s** [ansible-collections/cisco.ios#525]
##### SUMMARY
ios_command module failing Task if one of the command in list of commands not working

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_command

##### ANSIBLE VERSION

```
2.9.27
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- name: Backup Activity
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Execute Commands on the device    
      ios_command:
        commands:
          - show run
          - show version
          - show inventory
          - show ip bgp summary
          - show switch
      #ignore_errors: true
      #ignore_warning: true
      register: config
      #no_log: True

    - name: Print output
      debug:
        var: config
```

##### EXPECTED RESULTS

All the outputs of commands above should be displayed, if any command failes it has to go to next command instead of failing task. 

##### ACTUAL RESULTS

```TASK [Execute Commands on the device] ******************************************************************************
task path: /etc/ansible/playbooks/cisco-backups.yml:52
<10.10.10.10> ESTABLISH LOCAL CONNECTION FOR USER: USER_01
<10.10.10.10> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/USER_01/.ansible/tmp/ansible-local-41623x0uVMe `"&& mkdir "` echo /home/USER_01/.ansible/tmp/ansible-local-41623x0uVMe/ansible-tmp-1646763296.11-41647-77851938127368 `" && echo ansible-tmp-1646763296.11-41647-77851938127368="` echo /home/USER_01/.ansible/tmp/ansible-local-41623x0uVMe/ansible-tmp-1646763296.11-41647-77851938127368 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/ios/ios_command.py
<10.10.10.10> PUT /home/USER_01/.ansible/tmp/ansible-local-41623x0uVMe/tmpRWSb77 TO /home/USER_01/.ansible/tmp/ansible-local-41623x0uVMe/ansible-tmp-1646763296.11-41647-77851938127368/AnsiballZ_ios_command.py
<10.10.10.10> EXEC /bin/sh -c 'chmod u+x /home/USER_01/.ansible/tmp/ansible-local-41623x0uVMe/ansible-tmp-1646763296.11-41647-77851938127368/ /home/USER_01/.ansible/tmp/ansible-local-41623x0uVMe/ansible-tmp-1646763296.11-41647-77851938127368/AnsiballZ_ios_command.py && sleep 0'
<10.10.10.10> EXEC /bin/sh -c '/usr/bin/python3 /home/USER_01/.ansible/tmp/ansible-local-41623x0uVMe/ansible-tmp-1646763296.11-41647-77851938127368/AnsiballZ_ios_command.py && sleep 0'
<10.10.10.10> EXEC /bin/sh -c 'rm -f -r /home/USER_01/.ansible/tmp/ansible-local-41623x0uVMe/ansible-tmp-1646763296.11-41647-77851938127368/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_ios_command_payload_ki21t7xq/ansible_ios_command_payload.zip/ansible/module_utils/network/ios/ios.py", line 135, in run_commands
    return connection.run_commands(commands=commands, check_rc=check_rc)
  File "/tmp/ansible_ios_command_payload_ki21t7xq/ansible_ios_command_payload.zip/ansible/module_utils/connection.py", line 190, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [Switch_01]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": null, 
            "commands": [
                "show run", 
                "show version", 
                "show inventory", 
                "show switch"
            ], 
            "host": null, 
            "interval": 1, 
            "match": "all", 
            "password": null, 
            "port": null, 
            "provider": null, 
            "retries": 10, 
            "ssh_keyfile": null, 
            "timeout": null, 
            "username": null, 
            "wait_for": null
        }
    }, 
    "msg": "show switch\r\nshow switch\r\n      ^\r\n% Invalid input detected at '^' marker.\r\n\r\nSwitch_01#"
}

PLAY RECAP *********************************************************************************************************
Switch_01           : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```
