### ISSUE TITLE
ios_command "show tech" not working as expected

### ISSUE THREAD

**Issue by ao-inoue** [ansible-collections/cisco.ios#531]
##### SUMMARY
ios_command "show tech" not working as expected

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

```paste below
ansible [core 2.11.9]
python version = 3.7.10
jinja version = 3.0.3
```

##### COLLECTION VERSION

```paste below
cisco.ios           2.7.2
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Host OS: Amazon Linux 2

Cisco IOS Switch: Cisco IOS Software, C2960L Software (C2960L-UNIVERSALK9-M), Version 15.2(6)E2b, RELEASE SOFTWARE (fc3)

##### STEPS TO REPRODUCE

```yaml
- hosts: cisco
  gather_facts: false

  tasks:
    - name: show tech-support command (ios)
      connection: network_cli
      cisco.ios.ios_command:
        commands:
          - show tech
      register: result_sh_tech
      ignore_errors: true

    - debug:
        msg: "{{ result_sh_tech }}"
```

##### EXPECTED RESULTS

The output of the "show tech" command is displayed.

##### ACTUAL RESULTS

```
PLAY [cisco] ****************************************************************************************************************************************************************

TASK [show tech-support command (ios)] **************************************************************************************************************************************
fatal: [sample]: FAILED! => {"changed": false, "msg": "Error: Type:0, Msg:[]\r\n  Prev-Last Service Error: Type:0, Msg:[]\r\n\r\nConfig XML Errors: Total:0\r\n  Last Config Error: Reason:0, Msg:[], RCA:0, Msg:[]\r\nExec XML Errors: Total:0\r\n  Last Exec Error: Reason:0, Msg:[], RCA:0, Msg:[]\r\n\r\n\r\n--------------- show pnp"}
...ignoring

TASK [debug] ****************************************************************************************************************************************************************
ok: [sample] => {
    "msg": {
        "changed": false,
        "failed": true,
        "msg": "Error: Type:0, Msg:[]\r\n  Prev-Last Service Error: Type:0, Msg:[]\r\n\r\nConfig XML Errors: Total:0\r\n  Last Config Error: Reason:0, Msg:[], RCA:0, Msg:[]\r\nExec XML Errors: Total:0\r\n  Last Exec Error: Reason:0, Msg:[], RCA:0, Msg:[]\r\n\r\n\r\n--------------- show pnp"
    }
}

PLAY RECAP ******************************************************************************************************************************************************************
sample                     : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1
```
