### ISSUE TITLE
ios_logging_global inconsistent use of hosts.hostname

### ISSUE THREAD

**Issue by nleiva** [ansible-collections/cisco.ios#545]
##### SUMMARY

`ios_logging_global` uses `hosts.hostname` to define the _"IP address of the syslog server_", while `iosxr_logging_global` and `nxos_logging_global` use `hosts.host`. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_logging_global

##### ANSIBLE VERSION

```paste below
any
```

##### COLLECTION VERSION

```paste below
2.7.2
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Input:

```yaml
cfg:
  # buffered: # nxos
  #   severity: warnings
  hosts:
  - host: 10.10.20.175
    severity: critical
```

Task:

```yaml
    - name: Use Logging resource module [Cisco IOS]
      cisco.ios.ios_logging_global:
        state: merged
        config: "{{ cfg }}"
      when: ansible_network_os == 'ios'
```

##### EXPECTED RESULTS

Be able to apply the config on a Cisco IOS device

##### ACTUAL RESULTS

```paste below
TASK [Use Logging resource module [Cisco IOS]] **********************************************************************************************************************************************
fatal: [sandbox-iosxe-latest-1.cisco.com]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (cisco.ios.ios_logging_global) module: config.hosts.host, config.hosts.severity. Supported parameters include: running_config, config, state."}
```
