### ISSUE TITLE
Allow include and exclude of multiple MIB families in a configured SNMP view.

### ISSUE THREAD

**Issue by stephanblanke** [ansible-collections/cisco.ios#553]
##### SUMMARY
Allow include and exclude of multiple MIB families in a configured SNMP view.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ios_snmp_server

##### ADDITIONAL INFORMATION
I try to configure an IOS device using the ansible modules. I need SNMP views to include multiple MIB families. When configuring this directly on the device using the CLI I would need to create a configuration line for each include or exclude:

`snmp-server view ro iso included`
`snmp-server view ro internet included`
`snmp-server view rw iso included`
`snmp-server view rw internet included`

But the module only respects the latest occurence of view configurations with the same name. 

```yaml
- name: Configure SNMP
  cisco.ios.ios_snmp_server:
    config:
      views:
        - name: ro
          family_name: iso
          included: yes
        - name: ro
          family_name: internet
          included: yes
        - name: rw
          family_name: iso
          included: yes
        - name: rw
          family_name: internet
          included: yes
```
This leads to the following generated commands:
`snmp-server view ro-view internet included`
`snmp-server view rw-view internet included`
