### ISSUE TITLE
IOS_PREFIX_LISTS Shows Changed But Is Not Applied To Running Config

### ISSUE THREAD

**Issue by MrSteve81** [ansible-collections/cisco.ios#560]
##### SUMMARY

Upon applying a Prefix list using variables the ios_prefix_lists module ansible says it is changed but going to the actual Cisco device and  looking at running config the change is not present.   If I run the the same prefix list using ios_commands using the whole line with the inserted variables hard coded to the line it applies in the router.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_prefix_lists

##### ANSIBLE VERSION

```
ansible [core 2.12.1]
  config file = /Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/ansible.cfg
  configured module search path = ['/Users/stephenw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/5.0.1/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/stephenw/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.1 (main, Dec  6 2021, 23:20:29) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```
Collection Version
---------- -------
cisco.ios  2.7.2  

# /usr/local/Cellar/ansible/5.0.1/libexec/lib/python3.10/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  2.5.0  
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/ansible.cfg) = ['/Users/stephenw/Documents/Develo
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/host_vars/ansible.log
HOST_KEY_CHECKING(/Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/ansible.cfg) = 60
```

##### OS / ENVIRONMENT

Cisco IOS Software, 3700 Software (C3725-ADVENTERPRISEK9-M), Version 12.4(15)T14

##### STEPS TO REPRODUCE

```
- name: "LOW | CISC-RT-000570 | PATCH | The Cisco BGP router must be configured to limit the prefix size on any inbound route advertisement to /24 or the least significant prefixes issued to the customer."
  block:
    - name: "Configure PREFIX LISTS"
      ios_prefix_lists:
        config:
          - afi: ipv4
            prefix_lists:
              - name: FILTER_PREFIX_LENGTH
                description: 
                entries:
                  - action: "{{ item.action }}"
                    prefix: "{{ item.prefix }}"
                    ge: "{{ item.ge }}"
                    le: "{{ item.le }}"
                    sequence: "{{ item.seq }}"
      with_items:
        - "{{ iosrtr_flattened }}"
  when:
      - cisc_rt_000570
      - not cisc_rt_dodin_backbone
  tags:
      - CISC-RT-000570
      - CAT2
      - CCI-002385
      - SRG-NET-000362-RTR-000118
      - SV-216605r531085_rule
      - V-216605
```

##### EXPECTED RESULTS

In Defaults Main I have a list of variables it is suppose to call to to run and loop over and apply them to the router.  Below is a example of the variable that is in defaults/main
```
iosrtr_flattened:
    - { seq: 15, action: permit, prefix: 13.0.0.0/24, ge: 8, le: 24 }
```
 Once the command is fired the expected results in the router running config should look like the following:
```
no ip http server
no ip http secure-server
!
!
ip prefix-list FILTER_PREFIX_LENGTH seq 5 permit 0.0.0.0/0 ge 8 le 24
no cdp log mismatch duplex
```

   
##### ACTUAL RESULTS

```
TASK [/Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG : Configure PREFIX LISTS] ***********************************
task path: /Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/tasks/fix-cat3.yml:372
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
redirecting (type: become) ansible.builtin.enable to ansible.netcommon.enable
<192.168.68.114> attempting to start connection
<192.168.68.114> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /usr/local/bin/ansible-connection
<192.168.68.114> found existing local domain socket, using it!
<192.168.68.114> invoked shell using ssh_type: paramiko
<192.168.68.114> ssh connection done, setting terminal
<192.168.68.114> loaded terminal plugin for network_os ios
<192.168.68.114> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<192.168.68.114> firing event: on_become
<192.168.68.114> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<192.168.68.114> firing event: on_open_shell()
<192.168.68.114> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<192.168.68.114> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<192.168.68.114> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<192.168.68.114> ssh connection has completed successfully
<192.168.68.114> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<192.168.68.114> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<192.168.68.114> updating play_context for connection
<192.168.68.114> 
<192.168.68.114> local domain socket path is /Users/stephenw/.ansible/pc/c33e68c226
redirecting (type: action) cisco.ios.ios_prefix_lists to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_prefix_lists to cisco.ios.ios
<192.168.68.114> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<192.168.68.114> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<192.168.68.114> ESTABLISH LOCAL CONNECTION FOR USER: stephenw
<192.168.68.114> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/stephenw/.ansible/tmp/ansible-local-37953r14wd3jd `"&& mkdir "` echo /Users/stephenw/.ansible/tmp/ansible-local-37953r14wd3jd/ansible-tmp-1649947745.729779-38069-230993741857983 `" && echo ansible-tmp-1649947745.729779-38069-230993741857983="` echo /Users/stephenw/.ansible/tmp/ansible-local-37953r14wd3jd/ansible-tmp-1649947745.729779-38069-230993741857983 `" ) && sleep 0'
Using module file /Users/stephenw/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_prefix_lists.py
<192.168.68.114> PUT /Users/stephenw/.ansible/tmp/ansible-local-37953r14wd3jd/tmpsqld_tj2 TO /Users/stephenw/.ansible/tmp/ansible-local-37953r14wd3jd/ansible-tmp-1649947745.729779-38069-230993741857983/AnsiballZ_ios_prefix_lists.py
<192.168.68.114> EXEC /bin/sh -c 'chmod u+x /Users/stephenw/.ansible/tmp/ansible-local-37953r14wd3jd/ansible-tmp-1649947745.729779-38069-230993741857983/ /Users/stephenw/.ansible/tmp/ansible-local-37953r14wd3jd/ansible-tmp-1649947745.729779-38069-230993741857983/AnsiballZ_ios_prefix_lists.py && sleep 0'
<192.168.68.114> EXEC /bin/sh -c '/usr/local/Cellar/ansible/5.0.1/libexec/bin/python3.10 /Users/stephenw/.ansible/tmp/ansible-local-37953r14wd3jd/ansible-tmp-1649947745.729779-38069-230993741857983/AnsiballZ_ios_prefix_lists.py && sleep 0'
<192.168.68.114> EXEC /bin/sh -c 'rm -f -r /Users/stephenw/.ansible/tmp/ansible-local-37953r14wd3jd/ansible-tmp-1649947745.729779-38069-230993741857983/ > /dev/null 2>&1 && sleep 0'
changed: [192.168.68.114] => (item={'seq': 15, 'action': 'permit', 'prefix': '13.0.0.0/24', 'ge': 8, 'le': 24}) => {
    "after": {},
    "ansible_loop_var": "item",
    "before": {},
    "changed": true,
    "commands": [
        "ip prefix-list FILTER_PREFIX_LENGTH seq 15 permit 13.0.0.0/24 ge 8 le 24"
    ],
    "invocation": {
        "module_args": {
            "config": [
                {
                    "afi": "ipv4",
                    "prefix_lists": [
                        {
                            "description": null,
                            "entries": [
                                {
                                    "action": "permit",
                                    "description": null,
                                    "ge": 8,
                                    "le": 24,
                                    "prefix": "13.0.0.0/24",
                                    "sequence": 15
                                }
                            ],
                            "name": "FILTER_PREFIX_LENGTH"
                        }
                    ]
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    },
    "item": {
        "action": "permit",
        "ge": 8,
        "le": 24,
        "prefix": "13.0.0.0/24",
        "seq": 15
    }
}
redirecting (type: action) cisco.ios.ios_bgp to cisco.ios.ios
```

[ansible.log](https://github.com/ansible-collections/cisco.ios/files/8490195/ansible.log)

Processing the actual command on the router under elevated user control in configure terminal here is the actual hand written command that produces expected results on the device.
```
ip prefix-list FILTER_PREFIX_LENGTH seq 5 permit 13.0.0.0/24 ge 8 le 24
```
