### ISSUE TITLE
Issues with setting local_as, timers on BGP neighbors

### ISSUE THREAD

**Issue by ckhordiasma** [ansible-collections/cisco.ios#569]
##### SUMMARY
Get an error when I try to set local_as dict on a BGP neighbor. Error is `TypeError: can only concatenate str (not \"int\") to str` . Am also seeing issues where neighbors are defined in ansible but do not show up in the router configuration

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_bgp_global

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.2]
  config file = /home/admin/ansible/cnap/ansible.cfg
  configured module search path = ['/home/admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/admin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/lib/python3/dist-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  2.7.1  

# /home/admin/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  3.0.0  
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/admin/ansible/cnap/ansible.cfg) = ['/home/admin/ansible/cnap/inventory/hosts']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/admin/ansible/vault
```

##### OS / ENVIRONMENT

client: ubuntu
target: Cisco IOS XE Software, Version 17.07.01a

##### STEPS TO REPRODUCE

```yaml
- name: configure bgp
  cisco.ios.ios_bgp_global:
    config:
      as_number: 121212
      bgp:
        router_id: 
          address: 1.2.3.4
        log_neighbor_changes:  yes
      neighbor:
        - neighbor_address: 10.10.10.1
          local_as:
            number: 56
            set: yes
            no_prepend:
              replace_as: yes
              set: yes
          timers:
            holdtime: 5
            interval: 20
            min_holdtime: 0
```

##### EXPECTED RESULTS

```
router bgp 121212
 bgp router-id 1.2.3.4
 bgp log-neighbor-changes
 neighbor 10.10.11.1 remote-as 27064
 neighbor 10.10.11.1 local-as 56 no-prepend replace-as
 neighbor 10.10.11.1 timers 5 20
```

##### ACTUAL RESULTS

```paste below
( if local_as.set is set to yes )
fatal: [172.18.220.126]: FAILED! => {"changed": false, "module_stderr": "can only concatenate str (not \"int\") to str", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}

( if local_as.set is set to no )
router bgp 121212
 bgp router-id 1.2.3.4
 bgp log-neighbor-changes
 timers bgp 0 0
```
