### ISSUE TITLE
ios_logging_global bugs when using state replaced

### ISSUE THREAD

**Issue by eleksis** [ansible-collections/cisco.ios#571]
##### SUMMARY
With `state: replaced`, i expect module to remove all logging related settings not defined when running ansible task.

Bug number 1:
Running module without specifying console logging . It should generate & run `no logging console`.

Bug number 2:
Module generates invalid command when removing `logging monitor` setting.
It basically adds two `discriminator` words.
```
File "/tmp/ansible_cisco.ios.ios_logging_global_payload_012lgro8/ansible_cisco.ios.ios_logging_global_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: no logging monitor discriminator discriminator TEST\r\nno logging monitor discriminator discriminator TEST\r\n                                                 ^\r\n% Invalid input detected at '^' marker.
```

Bug number 3:
When not specifying `logging buffered` settings, it does not remove them (does not generate any commands).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_logging_global.py

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.4]
```

##### COLLECTION VERSION

```paste below
cisco.ios                     2.8.1  
```

##### IOS VERSION
```
Cisco IOS Software, C1900 Software (C1900-UNIVERSALK9-M), Version 15.6(3)M1, RELEASE SOFTWARE (fc2)
```
##### STEPS TO REPRODUCE
Initial config on device:
```
logging discriminator TEST mnemonics drops ACCESSLOG 
logging buffered discriminator TEST 262144
logging monitor discriminator TEST
logging console (not visible - default)
```

Ansible task:
```yaml
    - cisco.ios.ios_logging_global:
        config:
          logging_on: enable
          trap: informational
          facility: local7
          hosts:
            - hostname: "{{ syslog_host }}"
          source_interface:
            - interface: Loopback0
          #discriminator:
          #  - TEST mnemonics drops ACCESSLOG
          # buffered:
          #   discriminator: TEST
          #   size: 262144
          #   severity: debugging
          # monitor:
          #   discriminator: TEST
          #   severity: debugging
        state: replaced
```

##### ACTUAL RESULTS
Does not add `no logging console`,
does not remove `logging buffered discriminator TEST 262144` line,
crashes when removing `logging monitor discriminator TEST`.
