### ISSUE TITLE
NoneType' object has no attribute 'group

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/cisco.ios#586]
_From @jaiswaldj on Apr 23, 2022 06:50_

```
---
- hosts: switch
  connection: network_cli
  become_method: enable
  gather_facts: no
  tasks:
    - name: Interface Configuration
      ios_interfaces:
        config:
          - name: GE1
            description: Ansible Configured
            enabled: yes
            duplex: full
            speed: 1000
        state: merged
```

_Copied from original issue: ansible/ansible#77615_
