### ISSUE TITLE
ios_l2_interfaces Module Failure

### ISSUE THREAD

**Issue by thault** [ansible-collections/cisco.ios#588]
##### SUMMARY
Cisco ios version does not support the `section` command. Same issue as reported [here](https://github.com/ansible/ansible/issues/39011#issue-315854635) on the ios_l2_interface. Switching to the deprecated ios_l2_interface does allow the playbook to run. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_l2_interfaces

##### ANSIBLE VERSION
```
ansible [core 2.12.5]
  config file = None
  configured module search path = ['/Users/tylerault/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/5.7.1/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/tylerault/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.4 (main, Apr 26 2022, 19:36:29) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```
# /opt/homebrew/Cellar/ansible/5.7.1/libexec/lib/python3.10/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  2.8.1 
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT
- M1 Air
- `Cisco IOS Software, C3560E Software (C3560E-UNIVERSALK9-M), Version 12.2(55)SE13, RELEASE SOFTWARE (fc1)`

##### STEPS TO REPRODUCE
Playbook
```yaml
- hosts: switches
  gather_facts: no
  connection: local

  tasks:

    - name: Merge provided configuration with device configuration
      cisco.ios.ios_l2_interfaces:
        config:
        - name: GigabitEthernet0/47
          mode: access
          access:
            vlan: 10
        state: merged
```
hosts.yaml
```yaml
all:
  children:
    network:
      children:
        switches:
          hosts:
            1.2.3.4:
      vars:
        ansible_ssh_common_args: "-oKexAlgorithms=+diffie-hellman-group1-sha1 -c aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc"
        ansible_user: "user"
        ansible_password: "password"
        ansible_connection: "ansible.netcommon.network_cli"
        ansible_network_os: "ios"
```

run `ansible-playbook -i hosts.yaml playbook.yaml`

##### EXPECTED RESULTS

Expected VLAN added to port

##### ACTUAL RESULTS

```paste below
PLAY [switches] ************************************************************************************************************************************************************

TASK [Merge provided configuration with device configuration] **************************************************************************************************************
fatal: [10.1.3.4]: FAILED! => {"changed": false, "msg": "show running-config | section ^interface\r\nshow running-config | section ^interface\r\n                      ^\r\n% Invalid input detected at '^' marker.\r\n\r\nkingsroad#"}

PLAY RECAP *****************************************************************************************************************************************************************
1.2.3.4                   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


```
