### ISSUE TITLE
SNMPv3 user configuration does not render in running-config

### ISSUE THREAD

**Issue by ledgley** [ansible-collections/cisco.ios#609]
##### SUMMARY
SNMPv3 user configuration does not display in running config and therefore it is not gathered and the module is not idempotent.

Must use `show snmp user`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_snmp_server

##### ANSIBLE VERSION
```
ansible 2.10.17
```

##### COLLECTION VERSION
```
cisco.ios              3.0.0
```

##### CONFIGURATION
```
HOST_KEY_CHECKING(/Users/edgleyl/repos/compliance/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/edgleyl/repos/compliance/ansible.cfg) = 120
```

##### OS / ENVIRONMENT
Tested on various IOS 15.x (1,2,4) and 16.6.7

##### STEPS TO REPRODUCE

```yaml
- name: GATHER DEVICE SNMP CONFIGURATION
   cisco.ios.ios_snmp_server:
    state: gathered
  register: output
```

```yaml
- name: PUSH COMPLIANT SNMP CONFIGURATION
  cisco.ios.ios_snmp_server:
    state: replaced
    config:
      snmp:
        communities:
        - acl_v4: '99'
          name: '{{ snmp_community }}'
          ro: true
        contact: '{{ snmp_contact }}'
        groups:
        - group: network-operator
          version: v3
          version_option: auth
        location: '{{ snmp_location }}'
        trap_source: '{{ mgmt_interface }}'
        traps:
          syslog: false
        users:
        - acl_v4: '99'
          authentication:
            algorithm: sha
            password: '{{ snmpv3user }}'
          encryption:
            password: '{{ snmpv3user }}'
            priv: aes
            priv_option: '128'
          group: network-operator
          username: logicmonitor-snmp
          version: v3
```

##### EXPECTED RESULTS
1. Expect module state `gathered` to gather all SNMP configuration, including SNMPv3 user
2. Expect module to be idempotent when SNMPv3 user configuration already exists on the device

##### ACTUAL RESULTS
1. SNMPv3 user configuration is not gathered:
```
TASK [debug] *********************************************************************************************************************************************************************************
ok: [auq182frm-h1-as01M] => {
    "output": {
        "changed": false,
        "failed": false,
        "gathered": {
            "communities": [
                {
                    "acl_v4": "99",
                    "name": "OMITTED",
                    "ro": true
                },
                {
                    "acl_v4": "95",
                    "name": "OMITTED",
                    "ro": true
                }
            ],
            "contact": "OMITTED",
            "groups": [
                {
                    "group": "network-operator",
                    "version": "v3",
                    "version_option": "auth"
                }
            ],
            "location": "OMITTED",
            "trap_source": "Vlan1211"
        }
    }
}
```

2. SNMPv3 user configuration is 'changed' every run.
```
changed: [auq182frm-h1-as01M] => {
    "after": {
        "communities": [
            {
                "acl_v4": "99",
                "name": "OMITTED",
                "ro": true
            },
            {
                "acl_v4": "95",
                "name": "OMITTED",
                "ro": true
            }
        ],
        "contact": "OMITTED",
        "groups": [
            {
                "group": "network-operator",
                "version": "v3",
                "version_option": "auth"
            }
        ],
        "location": "OMITTED",
        "trap_source": "Vlan1211"
    },
    "before": {
        "communities": [
            {
                "acl_v4": "99",
                "name": "OMITTED",
                "ro": true
            },
            {
                "acl_v4": "95",
                "name": "OMITTED",
                "ro": true
            }
        ],
        "contact": "OMITTED",
        "groups": [
            {
                "group": "network-operator",
                "version": "v3",
                "version_option": "auth"
            }
        ],
        "location": "OMITTED",
        "trap_source": "Vlan1211"
    },
    "changed": true,
    "commands": [
        "snmp-server user logicmonitor-snmp network-operator v3 auth sha ******** priv aes 128 ******** access 99"
    ],
```
