### ISSUE TITLE
IOS extended VLANs (over 1024) not found in facts

### ISSUE THREAD

**Issue by cbueche** [ansible-collections/cisco.ios#636]
##### SUMMARY

`show vlan` on switch can bring up VLANs over 1024. However `gather_network_resources / vlans` stops at 1023 or so. Tested on a C9606R running IOS XE 17.03.04 but most probably same issue on other models and versions.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- cisco.ios.ios_facts

##### ADDITIONAL INFORMATION

```yaml
- name: Gather facts
  cisco.ios.ios_facts:
    gather_network_resources:
      - vlans
```
