### ISSUE TITLE
ios_bgp_global module rendering timers incorrectly

### ISSUE THREAD

**Issue by acvolt** [ansible-collections/cisco.ios#638]
When setting per neighbor timers in the ios_bgp_global module the timers are not rendered under the neighbor and are set as global values.

Neighbor Input to the module:
```
      - neighbor_address: 2.2.2.2
        description: "----- eBGP Peer -----"
        remote_as: 65000
        timers:
          interval: 3
          holdtime: 6
        send_community:
          set: yes
        soft_reconfiguration: yes
        filter_list:
          out: true
          path_acl: 10
        password_options:
          encryption: 0
          pass_key: private_key_here
        route_maps:
          - in: yes
            name: SECONDARY_INBOUND
          - out: yes
            name: SECONDARY_OUTBOUND
        fall_over:
          bfd:
            set: yes
```

The rendered configuration that results is:
            "neighbor 2.2.2.2 remote-as 65000",
            "neighbor 2.2.2.2 description ----- eBGP Peer -----",
            "neighbor 2.2.2.2 fall-over bfd",
            "neighbor 2.2.2.2 password 0 ********",
            "neighbor 2.2.2.2 soft-reconfiguration inbound",
            "timers bgp 6",
            "neighbor 2.2.2.2 filter-list 10 out",
            "neighbor 2.2.2.2 send-community",
            "neighbor 2.2.2.2 route-map SECONDARY_INBOUND in",
            "neighbor 2.2.2.2 route-map SECONDARY_OUTBOUND out"

The biggest issue is the timers are not being applied to the neighbor and the other issue is that the interval is being ignored.  This makes the holdtime apply as the interval which is not the desired result. 

Additional testing shows if you only include an interval the resulting config is "timers bgp" and it doesn't include the interval value.

Ansible Collection Version 3.3.0
