### ISSUE TITLE
IOS_ACL telnet / 23 Not interpreted correctly in check.  

### ISSUE THREAD

**Issue by MrSteve81** [ansible-collections/cisco.ios#647]
##### SUMMARY
Using the IOS_ACLs module to add ACLs to the config the command I enter in permit tcp any any eq 23 gets converted in the router to permit tcp any any eq telnet.  When running the ios_acl again it tried to change it because it sees it as telnet not 23.  This causes a changed every run.  
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_acls

##### ANSIBLE VERSION

```
ansible [core 2.12.1]
  config file = /Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/ansible.cfg
  configured module search path = ['/usr/share/ansible', '/Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/library']
  ansible python module location = /usr/local/Cellar/ansible/5.0.1/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/stephenw/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.1 (main, Dec  6 2021, 23:20:29) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```
# /Users/stephenw/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  3.2.0  

# /usr/local/Cellar/ansible/5.0.1/libexec/lib/python3.10/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  2.5.0  
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/ansible.cfg) = ['/Users/stephenw/Documents/Development/CISCO-IOS-
DEFAULT_MODULE_PATH(/Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/ansible.cfg) = ['/usr/share/ansible', '/Users/stephenw/Document
HOST_KEY_CHECKING(/Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/stephenw/Documents/Development/CISCO-IOS-RTR-STIG/ansible.cfg) = 60
```

##### OS / ENVIRONMENT

Testing against iOS 15.2 and iOS 12.4

##### STEPS TO REPRODUCE

Using a file with input below the 23 gets interpreted in the router as telnet.  When you rerun the ios_acls replaced and it checks against the file it shows its different and changes it.  To not do it I have changed the acl file to say telnet.  

Sample ACL:
Extended IP access list CoPP_UNDESIRABLE
remark management plane traffic that should not be received
10 permit udp any any eq ntp
20 permit udp any any eq snmp
30 permit tcp any any eq 22
40 permit tcp any any eq 23
50 permit eigrp any any
60 permit udp any any eq rip
300 deny ip any any

```yaml
        - name: Parse User Given ACL From host_vars For CoPP_UNDESIRABLE ACL."
          ios_acls:
            running_config: "{{ lookup('file','files/cisc-rt-000120-CoPP_UNDESIRABLE-acl.txt') }}"
            state: parsed
          register: cisc_rt_000120_copp_undesirable_parsed

        - name: Compare And Update ACL For CoPP_UNDESIRABLE ACL."
          ios_acls:
            config: "{{ cisc_rt_000120_copp_undesirable_parsed.parsed }}"
            state: replaced
          register: cisc_rt_000120_copp_undesirable_ran

        - name: Print Changed Lines With Debug When ACL Is Changed For CoPP_UNDESIRABLE ACL."
          debug:
            var: cisc_rt_000120_copp_undesirable_ran.commands
          when: 
            - cisc_rt_000120_copp_undesirable_ran.changed```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->
Would hope the module understands telnet as 23 and not try to change the acl.  

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->
    "changed": true,
    "commands": [
        "ip access-list extended CoPP_UNDESIRABLE",
        "no 40 permit tcp any any eq telnet",
        "40 permit tcp any any eq 23"

\<!--- Paste verbatim command output between quotes -->
```paste below
    "changed": true,
    "commands": [
        "ip access-list extended CoPP_UNDESIRABLE",
        "no 40 permit tcp any any eq telnet",
        "40 permit tcp any any eq 23"
```
