### ISSUE TITLE
Command module fails with connection error

### ISSUE THREAD

**Issue by ninapetr** [ansible-collections/cisco.ios#671]
##### SUMMARY

Running a playbook with three plays in it. The command module works as expected in the first play but fails with connection error in the second. All of the plays have the same host.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_command
##### ANSIBLE VERSION

```
ansible-playbook [core 2.13.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.9.7 (default, Sep 13 2021, 08:18:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True
```

##### OS / ENVIRONMENT

Cisco IOS XE Software, Version 16.12.05b
Cisco IOS Software [Gibraltar], Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 16.12.5b, RELEASE SOFTWARE (fc3)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2021 by Cisco Systems, Inc.
Compiled Thu 25-Mar-21 13:09 by mcpre

##### STEPS TO REPRODUCE

The first play which runs without any issues:
```yaml
- name: Internet Access Premium Level
    hosts: ios
    gather_facts: false
    tasks: 
      - name: Gathering all policies from the customer policy map
        cisco.ios.ios_command:
          commands: show policy-map SHAPE-OUT-CUSTOMER
        register: policies

      - name: Check current directory on the controller node
        ansible.builtin.command: pwd
        register: curr_dir
        delegate_to: localhost

      - name: Storing policies data
        copy:
          dest: "{{ curr_dir.stdout }}/policies"
          content: "{{ policies.stdout_lines }}"
        delegate_to: localhost

      - name: Running INTP.py
        command: "python3 INTP.py policies"
        delegate_to: test.example.com   
        become: yes
```

The problem play:
```yaml
 - name: Internet Remote Connectivity (Site2site VPN)
    hosts: ios
    gather_facts: false
    tasks:
      - name: Gathering ikev2 profiles data
        cisco.ios.ios_command:
          commands: sh crypto ikev2 profile
        register: ikev2profiles
```
Both are part of the same playbook.

##### ACTUAL RESULTS

```
  File "/runner/requirements_collections/ansible_collections/cisco/ios/plugins/module_utils/network/ios/ios.py", line 144, in run_commands
    return connection.run_commands(commands=commands, check_rc=check_rc)
  File "/usr/lib/python3.9/site-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [172.16.10.11]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "sh crypto ikev2 profile"
            ],
            "interval": 1,
            "match": "all",
            "provider": null,
            "retries": 10,
            "wait_for": null
        }
    },
    "msg": "sh crypto ikev…
````
