### ISSUE TITLE
Support for Cisco Interface Templates

### ISSUE THREAD

**Issue by shepherdjay** [ansible-collections/cisco.ios#677]
##### SUMMARY
Enhancement to ios_interfaces to specify interface template

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ios_interfaces

##### ADDITIONAL INFORMATION

The ios_interfaces modules and their l2,l3 variants is very efficient at pushing broad interface changes. Much more efficient then ios_config. However they don't support every possible interface command that exists or may exist in the future. For example port-security, broadcast protections, spanning-tree settings, 802.1x configurations, etc.

Supporting Cisco's Interface Templates would allow for this support, especially on access layers where thousands of ports may share the same configuration.

```yaml
- name: Create Employee Template
  cisco.ios.ios_config:
  lines:
    - load-interval 60
    - description EmployeePort
    - port-security 
    - switchport mode access
    - switchport access vlan 100
    - switchport port-security
  parents: template EMPLOYEE_TEMPLATE

- name: Apply Employee Templates to Ports
  cisco.io.ios_interfaces:
    config
    - name: GigabitEthernet0/1
      template: EMPLOYEE_TEMPLATE
    - name: GigabitEthernet0/2
      template: EMPLOYEE_TEMPLATE
    - name: GigabitEthernet0/3
      template: EMPLOYEE_TEMPLATE
    # etc...
    state: replaced      
```
