### ISSUE TITLE
as-path prepend as-number is not idempotent

### ISSUE THREAD

**Issue by bentole** [ansible-collections/cisco.ios#678]
AS-path prepend as-path operation is not idempotent.

I'll put a suggestion how to fix this in PR #667. Hopefully I'm not the only one experiencing this 😄 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_route_maps

##### STEPS TO REPRODUCE
```
  tasks:
  - name: SET AS PATH PREPEND
    cisco.ios.ios_route_maps:
      config:
        - route_map: TEST
          entries:
            - sequence: 10
              action: permit
              match:
                community:
                  name: I_AM_JUST_TESTING
              set:
                as_path:
                  prepend:
                    as_number:
                    - 65000
                    - 65000
      state: replaced
```

##### EXPECTED RESULTS
PLAY RECAP *********************************************************************
XXX                   : ok=1    changed=0   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  

##### ACTUAL RESULTS
XXX                   : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
