### ISSUE TITLE
set community none is not idempotent

### ISSUE THREAD

**Issue by bentole** [ansible-collections/cisco.ios#679]
set community none operation is not idempotent.

I'll put a suggestion how to fix this in PR #667.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_route_maps

##### STEPS TO REPRODUCE
```
  tasks:
  tasks:
  - name: SET COMMUNITY NONE
    cisco.ios.ios_route_maps:
      config:
        - route_map: TEST
          entries:
            - sequence: 10
              action: permit
              match:
                community:
                  name: I_AM_JUST_TESTING
              set:
                community:
                  none: true
      state: replaced
```

##### EXPECTED RESULTS
PLAY RECAP *********************************************************************
XXX                   : ok=1    changed=0   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  

##### ACTUAL RESULTS
XXX                   : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
