### ISSUE TITLE
Support for private vlans (vlans)

### ISSUE THREAD

**Issue by UvixCreative** [ansible-collections/cisco.ios#693]
##### SUMMARY

Add options for creating private vlans

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`ios_vlans`

##### ADDITIONAL INFORMATION

Add support for features that already exist in IOS XE

Example usage:

```yaml
ios_vlans:
  config:
    - name: pvlan-primary
      vlan_id: 10
      private_vlan:
        type: primary
        association:
          - 25
          - 40
    - name: pvlan-isolated
      vlan_id: 25
      private_vlan:
        type: isolated
    - name: pvlan-community
      vlan_id: 40
      private_vlan:
        type: community
```
