### ISSUE TITLE
Assigning interfaces to existing vrfs doesn't work

### ISSUE THREAD

**Issue by bentole** [ansible-collections/cisco.ios#707]
##### SUMMARY
Assigning interfaces to vrfs already defined on the device doesnt appear to work as intended. There's a very easy fix to this so I'll have a PR up in a jiff.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_vrf

##### STEPS TO REPRODUCE
Run the following task

1. Create a vrf named test1 using CLI. Assign no interfaces
2. Run the following task
```
- name: assign previously defined vrf to interface
  cisco.ios.ios_vrf:
    name: test1
    interfaces:
      - GigabitEthernet5
```

##### EXPECTED RESULTS
```
PLAY RECAP *********************************************************************
XXX                   : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

##### ACTUAL RESULTS
```
PLAY RECAP *********************************************************************
XXX                   : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
