### ISSUE TITLE
ios_l2_interfaces module trunk not taking input 

### ISSUE THREAD

**Issue by azzeddineslimani** [ansible-collections/cisco.ios#715]
##### SUMMARY

ios_l2_interfaces module works fine for access configuration, but trunk is giving error 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_l2_interfaces
##### ANSIBLE VERSION

```paste below
ansible [core 2.12.10]
  config file = /home/eve/ansible/ch2_ios/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

ACTION_WARNINGS(/home/eve/ansible/ch2_ios/ansible.cfg) = False
DEFAULT_GATHERING(/home/eve/ansible/ch2_ios/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/eve/ansible/ch2_ios/ansible.cfg) = ['/home/eve/ansible/ch2_ios/hosts']
DEPRECATION_WARNINGS(/home/eve/ansible/ch2_ios/ansible.cfg) = False
HOST_KEY_CHECKING(/home/eve/ansible/ch2_ios/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/home/eve/ansible/ch2_ios/ansible.cfg) = 60
RETRY_FILES_ENABLED(/home/eve/ansible/ch2_ios/ansible.cfg) = False
 
 
```

##### OS / ENVIRONMENT

Ubuntu 20.04

##### STEPS TO REPRODUCE

```  - name: Merge provided configuration with device configuration
      ios_l2_interfaces:
        config:
          - name: GigabitEthernet0/1
            access:
              vlan: 10
          - name: GigabitEthernet0/2
            trunk:
              allowed_vlan: 10-20, 40
              native_vlan: 20
              pruning_vlan: 10,20
              encapsulation: dot1q
        state: merged

```

##### EXPECTED RESULTS

Trunk configuration on the cisco switch
##### ACTUAL RESULTS

failed: [core01] (item={'name': 'GigabitEthernet1/0', 'description': 'core01_e0/3', 'mode': 'trunk'}) => {"ansible_loop_var": "item", "changed": false, "item": {"description": "core01_e0/3", "mode": "trunk", "name": "GigabitEthernet1/0"}, "msg": "value of state must be one of: present, absent, got: merged"}

```paste below

```

**Comment by KB-perByte** [comment]
@azzeddineslimani The playbook contains attributes that are misspelled, 
config.trunk.allowed_vlan -> _vlans_, config.trunk.pruning_vlan -> _vlans_
Correct playbook
 ```
 tasks:
    - name: Check l2_interface issue #01011
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet0/1
            access:
              vlan: 10
          - name: GigabitEthernet0/2
            trunk:
              allowed_vlans: 10-20, 40
              native_vlan: 20
              pruning_vlans: 10,20
              encapsulation: dot1q
        state: merged
```
task output
```
  commands:
  - interface GigabitEthernet0/1
  - switchport access vlan 10
  - interface GigabitEthernet0/2
  - switchport trunk encapsulation dot1q
  - switchport trunk native vlan 20
  - switchport trunk allowed vlan 10-20,40
  - switchport trunk pruning vlan 10,20
```
Regards
