### ISSUE TITLE
cisco.ios.ios_bgp_address_family does not initially implement the whole set of instructions as written in playbook

### ISSUE THREAD

**Issue by netexgb** [ansible-collections/cisco.ios#719]
##### SUMMARY
The cisco.ios.ios_bgp_address_family collection does not initially implement the whole set of instructions as it has been written in the Ansible playbook in the router when the state of the playbook is either replaced or merged. 

If I want to have the whole configuration to be implemented fully, I have to re-run the playbook again with state=merged.

Also, once I want to add new configuration, I have to run the command twice with state=merged for the playbook to implement the whole configuration, otherwise it does it in parts.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_bgp_address_family

##### ANSIBLE VERSION

```
ansible --version
ansible [core 2.13.7]
  config file = /home/gbloise/ansible.cfg
  configured module search path = ['/home/gbloise/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gbloise/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/gbloise/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/gbloise/.local/bin/ansible
  python version = 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
ansible-galaxy collection list cisco.ios

# /home/gbloise/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  4.2.0

# /home/gbloise/.local/lib/python3.8/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  4.2.0
```

##### CONFIGURATION

```
ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/gbloise/ansible.cfg) = ['/etc/ansible/hosts']
PERSISTENT_COMMAND_TIMEOUT(/home/gbloise/ansible.cfg) = 90
```

##### OS / ENVIRONMENT

```
be2012-gcp-proctor-cs#show ver
Cisco IOS XE Software, Version 17.03.04a
Cisco IOS Software [Amsterdam], Virtual XE Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 17.3.4a, RELEASE SOFTWARE (fc3)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2021 by Cisco Systems, Inc.
Compiled Tue 20-Jul-21 04:59 by mcpre


Cisco IOS-XE software, Copyright (c) 2005-2021 by cisco Systems, Inc.
All rights reserved.  Certain components of Cisco IOS-XE software are
licensed under the GNU General Public License ("GPL") Version 2.0.  The
software code licensed under GPL Version 2.0 is free software that comes
with ABSOLUTELY NO WARRANTY.  You can redistribute and/or modify such
GPL code under the terms of GPL Version 2.0.  For more details, see the
documentation or "License Notice" file accompanying the IOS-XE software,
or the applicable URL provided on the flyer accompanying the IOS-XE
software.


ROM: IOS-XE ROMMON

be2012-gcp-proctor-cs uptime is 1 year, 16 weeks, 5 days, 5 hours, 10 minutes
Uptime for this control processor is 1 year, 16 weeks, 5 days, 5 hours, 11 minutes
System returned to ROM by reload at 16:27:51 UTC Tue Sep 14 2021
System restarted at 16:29:18 GMT Tue Sep 14 2021
System image file is "bootflash:packages.conf"
Last reload reason: Reload Command



This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

License Level: appx
License Type: N/A(Smart License Enabled)
Next reload license Level: appx

The current throughput level is 10000 kbps


Smart Licensing Status: REGISTERED/AUTHORIZED

cisco CSR1000V (VXE) processor (revision VXE) with 2287893K/3075K bytes of memory.
Processor board ID 9UYUREJ0ZUN
Router operating mode: Autonomous
2 Gigabit Ethernet interfaces
32768K bytes of non-volatile configuration memory.
15332148K bytes of physical memory.
8285184K bytes of virtual hard disk at bootflash:.

Configuration register is 0x2102
```

##### STEPS TO REPRODUCE

```
- name: Configure BGP address-family cloud_transit
  hosts:
    - be2012
  # debugger: on_failed
  gather_facts: False

  tasks:
    - name: BGP Address Family cloud_transit
      cisco.ios.ios_bgp_address_family:
        config:
          as_number: 72
          address_family:
            - afi: ipv4
              vrf: cloud_transit
              aggregate_address:
                - address: 10.152.0.0
                  netmask: 255.255.0.0
                  attribute_map: SLB_CLOUD_SUMMARY_AGGREGATE
                - address: 10.156.0.0
                  netmask: 255.255.0.0
                  attribute_map: SLB_CLOUD_SUMMARY_AGGREGATE
                - address: 10.192.0.0
                  netmask: 255.255.0.0
                  attribute_map: SLB_CLOUD_SUMMARY_AGGREGATE
                - address: 10.194.0.0
                  netmask: 255.255.0.0
                  attribute_map: SLB_CLOUD_SUMMARY_AGGREGATE
                - address: 10.195.0.0
                  netmask: 255.255.0.0
                  attribute_map: SLB_CLOUD_SUMMARY_AGGREGATE
                - address: 10.196.0.0
                  netmask: 255.255.0.0
                  attribute_map: SLB_CLOUD_SUMMARY_AGGREGATE
                - address: 10.197.0.0
                  netmask: 255.255.0.0
                  attribute_map: SLB_CLOUD_SUMMARY_AGGREGATE
              neighbors:
                - neighbor_address: CLOUD_TRANSIT_PEER_AZURE
                  peer_group: true
                  remote_as: 12076
                  local_as:
                    number: 64528
                    set: true
                    no_prepend:
                      replace_as: true
                      set: true
                  fall_over:
                    bfd:
                      single_hop: true
                      set: true
                  route_maps:
                    - name: FROM_TRANSIT_CLOUD_GENERAL
                      in: true
                    - name: TO_TRANSIT_CLOUD_GENERAL
                      out: true
                - neighbor_address: CLOUD_TRANSIT_PEER_GCP
                  peer_group: true
                  remote_as: 16550
                  local_as:
                    number: 64528
                    set: true
                    no_prepend:
                      replace_as: true
                      set: true
                  route_maps:
                    - name: FROM_TRANSIT_CLOUD_GENERAL
                      in: true
                    - name: TO_TRANSIT_CLOUD_GENERAL
                      out: true
                - neighbor_address: CLOUD_TRANSIT_PEER_SINET_US1896
                  peer_group: true
                  remote_as: 64680
                  local_as:
                    number: 64528
                    set: true
                    no_prepend:
                      replace_as: true
                      set: true
                  send_community:
                    set: true
                  route_maps:
                    - name: TO_TRANSIT_SINET
                      out: true
        state: replaced
```

##### EXPECTED RESULTS

```
be2012-gcp-proctor-cs#sh run | s add.*tran
 address-family ipv4 vrf cloud_transit
  bgp router-id 172.26.11.249
  aggregate-address 10.197.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.196.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.195.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.194.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.192.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.156.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.152.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  neighbor CLOUD_TRANSIT_PEER_AZURE peer-group
  neighbor CLOUD_TRANSIT_PEER_AZURE remote-as 12076
  neighbor CLOUD_TRANSIT_PEER_AZURE local-as 64528 no-prepend replace-as
  neighbor CLOUD_TRANSIT_PEER_AZURE fall-over bfd single-hop
  neighbor CLOUD_TRANSIT_PEER_AZURE route-map FROM_TRANSIT_CLOUD_GENERAL in
  neighbor CLOUD_TRANSIT_PEER_AZURE route-map TO_TRANSIT_CLOUD_GENERAL out
  neighbor CLOUD_TRANSIT_PEER_GCP peer-group
  neighbor CLOUD_TRANSIT_PEER_GCP remote-as 16550
  neighbor CLOUD_TRANSIT_PEER_GCP local-as 64528 no-prepend replace-as
  neighbor CLOUD_TRANSIT_PEER_GCP route-map FROM_TRANSIT_CLOUD_GENERAL in
  neighbor CLOUD_TRANSIT_PEER_GCP route-map TO_TRANSIT_CLOUD_GENERAL out
  neighbor CLOUD_TRANSIT_PEER_SINET_US1896 peer-group
  neighbor CLOUD_TRANSIT_PEER_SINET_US1896 remote-as 64680
  neighbor CLOUD_TRANSIT_PEER_SINET_US1896 local-as 64528 no-prepend replace-as
  neighbor CLOUD_TRANSIT_PEER_SINET_US1896 send-community
  neighbor CLOUD_TRANSIT_PEER_SINET_US1896 route-map TO_TRANSIT_SINET out

```

##### ACTUAL RESULTS

```
be2012-gcp-proctor-cs#sh run | s add.*tran
 address-family ipv4 vrf cloud_transit
  bgp router-id 172.26.11.249
  aggregate-address 10.197.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.196.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.195.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.194.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.192.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.156.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.152.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  neighbor CLOUD_TRANSIT_PEER_AZURE peer-group
  neighbor CLOUD_TRANSIT_PEER_AZURE route-map FROM_TRANSIT_CLOUD_GENERAL in
  neighbor CLOUD_TRANSIT_PEER_AZURE route-map TO_TRANSIT_CLOUD_GENERAL out
  neighbor CLOUD_TRANSIT_PEER_GCP peer-group
  neighbor CLOUD_TRANSIT_PEER_GCP route-map FROM_TRANSIT_CLOUD_GENERAL in
  neighbor CLOUD_TRANSIT_PEER_GCP route-map TO_TRANSIT_CLOUD_GENERAL out
  neighbor CLOUD_TRANSIT_PEER_SINET_US1896 peer-group
  neighbor CLOUD_TRANSIT_PEER_SINET_US1896 send-community
  neighbor CLOUD_TRANSIT_PEER_SINET_US1896 route-map TO_TRANSIT_SINET out

```

**Comment by KB-perByte** [comment]
Hey @netexgb this is an interesting find, I'll push a fix to it asap
Regards

**Comment by rogertanwc84** [comment]
When running the playbook with **cisco.ios.ios_bgp_address_family module**  the local as does not get configured.
ebgp multihop does not  get configured when running playbook on the first run. on the 2nd run  the ebgp multi hop gets configured but it does not configure correct value from the paramter **hop_count**, instead it configures it as 255.

```
ansible [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/roger/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/roger/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/roger/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/roger/.local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```
```
# /home/xx/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
ansible.netcommon  4.1.0  
ansible.posix      1.3.0  
ansible.utils      2.8.0  
cisco.ios          4.3.0  
community.docker   2.1.1  
community.general  4.3.0  
community.mysql    3.0.0  
```


playbook
```
- hosts: CSR-hub-extend-2 CSR-hub-extend-3
  gather_facts: false
  tasks:
      - name: config bgp global config
        cisco.ios.ios_bgp_global:
          config:
            as_number: '{{ bgp_as }}'
            bgp:
              router_id:
                address: '{{ bgp_r_id }}'
              always_compare_med: true
              log_neighbor_changes: true
              deterministic_med: true
              listen:
                limit: 1000
                range:
                  host_with_subnet: '{{ bgp_range }}/23'
                  peer_group: '{{ bgp_peer_group_name }}'
          state: replaced

      - name: configure BGP ipv4 address family vrf private vrf neighbor
        cisco.ios.ios_bgp_address_family:
          config:
            as_number: '{{ bgp_as }}'
            address_family:
              - afi: ipv4
                safi: unicast
                vrf: private-vrf 
                neighbor:
                  - address: 192.168.255.254
                    activate: true
                    local_as:
                      dual_as: true
                      number: 101
                      set: true
                    remote_as: 100
                    ebgp_multihop: 
                      enable: true
                      hop_count: 2
          state: replaced
```



expectation:

```
router bgp 400
 bgp router-id 192.168.8.85
 bgp always-compare-med
 bgp log-neighbor-changes
 bgp deterministic-med
 bgp listen range 192.168.250.0/23 peer-group extended_sites-2
 bgp listen limit 1000
 no bgp default ipv4-unicast
 !
 address-family ipv4 vrf private-vrf
  neighbor 192.168.255.254 remote-as 100
  neighbor 192.168.255.254 local-as 101
  neighbor 192.168.255.254 ebgp-multihop 2
  neighbor 192.168.255.254 activate
 exit-address-family
```


Result:

```
router bgp 400
 bgp router-id 192.168.8.85
 bgp always-compare-med
 bgp log-neighbor-changes
 bgp deterministic-med
 bgp listen range 192.168.250.0/23 peer-group extended_sites-2
 bgp listen limit 1000
 !
 address-family ipv4 vrf private-vrf
  neighbor 192.168.255.254 remote-as 100
  neighbor 192.168.255.254 activate
 exit-address-family
```

Result from 2nd time running the playbook:

```
router bgp 400
 bgp router-id 192.168.8.85
 bgp always-compare-med
 bgp log-neighbor-changes
 bgp deterministic-med
 bgp listen range 192.168.250.0/23 peer-group extended_sites-2
 bgp listen limit 1000
 !
 address-family ipv4 vrf private-vrf
  neighbor 192.168.255.254 remote-as 100
  neighbor 192.168.255.254 ebgp-multihop 255
  neighbor 192.168.255.254 activate
 exit-address-family
```
