### ISSUE TITLE
Module ios_interfaces always 'changing' Loopback interfaces

### ISSUE THREAD

**Issue by poroping** [ansible-collections/cisco.ios#73]
##### SUMMARY

Loopback interfaces will a capital 'L' will always show as changed. This is causing issues with idempotentcy as when the interface is referenced in other lines of config by the ios_config module (in my case for radius/logging source) the interface needs to be 'Loopback' as this is how it is displayed in the config.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_interfaces

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Apr 16 2020, 17:47:17) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto
PARAMIKO_HOST_KEY_AUTO_ADD(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT

Target device:
```
Cisco IOS Software, C3560CX Software (C3560CX-UNIVERSALK9-M), Version 15.2(4)E5, RELEASE SOFTWARE (fc2)
```
##### STEPS TO REPRODUCE

Use ios_interfaces module to configure a loopback interface.

```yaml
- ios_interfaces:
  config:
  - name: Loopback0
    description: 'MGMT loopback'
  state: replaced
  register: debugging
- debug: var=debugging
```
Device config:
```
xxx-dist-sw1#show run | sec ^interface Loopback
interface Loopback0
 description MGMT loopback
xxx-dist-sw1#
```

##### EXPECTED RESULTS

Module makes no changes if Loopback interface is configured already.

##### ACTUAL RESULTS

Module attempts to 'change' interface.

```paste below
TASK [interfaces : configure interfaces] **************************************************************************
changed: [xxx-dist-sw1]

TASK [interfaces : debug] *****************************************************************************************
ok: [xxx-dist-sw1] => {
    "debugging": {
        "after": [
            {
                "description": "MGMT loopback",
                "enabled": true,
                "name": "loopback0"
            }
        ],
        "before": [
            {
                "description": "MGMT loopback",
                "enabled": true,
                "name": "loopback0"
            }
        ],
        "changed": true,
        "commands": [
            "interface Loopback0",
            "description MGMT loopback",
            "no shutdown"
        ],
        "failed": false
    }
}
```
##### With lowercase 'L'
```yaml
- ios_interfaces:
  config:
  - name: loopback0
    description: 'MGMT loopback'
  state: replaced
  register: debugging
- debug: var=debugging
```
```yaml
TASK [interfaces : configure interfaces] **************************************************************************
ok: [xxx-dist-sw1]

TASK [interfaces : debug] *****************************************************************************************
ok: [xxx-dist-sw1] => {
    "debugging": {
        "before": [
            {
                "description": "MGMT loopback",
                "enabled": true,
                "name": "loopback0"
            }
        ],
        "changed": false,
        "commands": [],
        "failed": false
    }
}
```
This issue does not occur with ios_l3_interfaces module. I am not sure why as I would imagine it uses the same/similar function to compare before and after.
As far as I'm aware it's always 'Loopback' with IOS and IOS-XE and 'loopback' on NXOS.
