### ISSUE TITLE
ios_acls : execution time is affected by the amount of ACLs that don't change

### ISSUE THREAD

**Issue by hirose003** [ansible-collections/cisco.ios#732]
##### SUMMARY

When changing specific ACL with the ios_acls module, the execution time is determined by the total amount of ACLs set on the device, not by the amount of ACLs that change.
In other words, execution time is affected by the amount of ACLs that don't change

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

cisco.ios.ios_acls

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/hirose/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/hirose/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
cisco.ios         4.3.0  
```

##### CONFIGURATION

```paste below
CALLBACKS_ENABLED(/home/hirose/ansible-network/ansible.cfg) = ['profile_tasks']
PERSISTENT_COMMAND_TIMEOUT(/home/hirose/ansible-network/ansible.cfg) = 300
PERSISTENT_CONNECT_TIMEOUT(/home/hirose/ansible-network/ansible.cfg) = 300
```
command_timeout and connect_timeout need longer than execution time.

##### OS / ENVIRONMENT

```
Cisco IOS Software, vios_l2 Software (vios_l2-ADVENTERPRISEK9-M), Experimental Version 15.2(20200924:215240) [sweickge-sep24-2020-l2iol-release 135]
```

##### STEPS TO REPRODUCE

Create two acls.
The first is a modified acl with only one rule. This is `changed_acl`.
The second is an acl that does not change. This is `unchanged_acl`.

Measure the execution time of adding 1 rule to `changed_acl` when `unchanged_acl` is 10 rules and 1000 rules.

`changed_acl`

```
ip access-list extended changed_acl
 permit icmp 192.168.0.0 0.0.255.255 10.0.0.0 0.255.255.255
```

`unchanged_acl`

pattern 1

10 rules

```
ip access-list extended unchanged_acl
 permit icmp host 192.168.0.0 any
 permit icmp host 192.168.0.1 any
 permit icmp host 192.168.0.2 any
 permit icmp host 192.168.0.3 any
 permit icmp host 192.168.0.4 any
 permit icmp host 192.168.0.5 any
 permit icmp host 192.168.0.6 any
 permit icmp host 192.168.0.7 any
 permit icmp host 192.168.0.8 any
 permit icmp host 192.168.0.9 any
```

pattern 2

1000 rules

```
ip access-list extended unchanged_acl
 permit icmp host 192.168.0.0 any
 permit icmp host 192.168.0.1 any
 permit icmp host 192.168.0.2 any
 permit icmp host 192.168.0.3 any
 .
 .
 .
```

site.yaml

```yaml
- name: Confiuration acl
  hosts: all
  gather_facts: false
  connection: local
  vars:
    ansible_user: network
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_become: true
    ansible_become_method: enable
  tasks:
    - name: Configure acls
      cisco.ios.ios_acls:
        config:
          - afi: ipv4
            acls:
              - name: "changed_acl"
                acl_type: extended
                aces:
                  - grant: permit
                    protocol: icmp
                    source:
                      host: 192.168.0.1
                    destination:
                      any: true
        state: merged
```

##### EXPECTED RESULTS

Execution time depending on the amount of ACLs that change.

##### ACTUAL RESULTS

The execution time of pattern1 is 5.75s, and the execution time of pattern2 is 215.25s.
If the number of rules in `unchanged_acl` is multiplied by 100, the execution time increases by about 40.

pattern1

```
$ ansible-playbook site.yml -i 10.111.111.11, --ask-pass --ask-become-pass 
SSH password: 
BECOME password[defaults to SSH password]: 

PLAY [Confiuration acl] *********************************************************************************************************************************************************************

TASK [Configure acls] ***********************************************************************************************************************************************************************
Wednesday 25 January 2023  19:39:29 +0900 (0:00:00.060)       0:00:00.060 ***** 
changed: [10.111.111.11]

PLAY RECAP **********************************************************************************************************************************************************************************
10.111.111.11              : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Wednesday 25 January 2023  19:39:34 +0900 (0:00:05.752)       0:00:05.813 ***** 
=============================================================================== 
Configure acls ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- 5.75s
```

pattern2

```
$ ansible-playbook site.yml -i 10.111.111.11, --ask-pass --ask-become-pass
SSH password: 
BECOME password[defaults to SSH password]: 

PLAY [Confiuration acl] *********************************************************************************************************************************************************************

TASK [Configure acls] ***********************************************************************************************************************************************************************
Wednesday 25 January 2023  19:32:40 +0900 (0:00:00.062)       0:00:00.062 ***** 
changed: [10.111.111.11]

PLAY RECAP **********************************************************************************************************************************************************************************
10.111.111.11              : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Wednesday 25 January 2023  19:36:15 +0900 (0:03:35.247)       0:03:35.309 ***** 
=============================================================================== 
Configure acls --------------------------------------------------------------------------------------------------------------------------------------------------------------------- 215.25s
```
