### ISSUE TITLE
ios user module not connecting to devices

### ISSUE THREAD

**Issue by xkoldxx** [ansible-collections/cisco.ios#733]
I am trying to leverage cisco.ios.ios_user to clean up some config, but when i run my play book only the gather_facts runs the other task doesnt 

Playbook is as follows

```

 - hosts: ios
  connection: network_cli
  become: yes
  gather_facts: yes
  tasks:
    - name: remove all users except admin and these listed users
      cisco.ios.ios_user:
        aggregate:
        - name: testadmin
        purge: yes

```
