### ISSUE TITLE
Implementing cisco.ios.ios_bgp_address_family fails due to 'default originate' issue in basic.py

### ISSUE THREAD

**Issue by netexgb** [ansible-collections/cisco.ios#738]
##### SUMMARY
When implementing a playbook running the cisco.ios.ios_bgp_address_family, the implementation fails with the following message:
"Unsupported parameters for (basic.py) module: config.address_family.neighbors.default-originate. Supported parameters include: running_config, state, config."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_bgp_address_family

##### ANSIBLE VERSION

```
ansible [core 2.13.7]
  config file = None
  configured module search path = ['/home/gbloise/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gbloise/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/gbloise/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/gbloise/.local/bin/ansible
  python version = 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
# /home/gbloise/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  4.3.1

# /home/gbloise/.local/lib/python3.8/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  4.3.1
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/home/gbloise/ansible.cfg) = ['/etc/ansible/hosts']
PERSISTENT_COMMAND_TIMEOUT(/home/gbloise/ansible.cfg) = 90
```

##### OS / ENVIRONMENT

```
Cisco IOS XE Software, Version 17.06.03a
Cisco IOS Software [Bengaluru], ASR1000 Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 17.6.3a, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2022 by Cisco Systems, Inc.
Compiled Fri 08-Apr-22 04:50 by mcpre


Cisco IOS-XE software, Copyright (c) 2005-2022 by cisco Systems, Inc.
All rights reserved.  Certain components of Cisco IOS-XE software are
licensed under the GNU General Public License ("GPL") Version 2.0.  The
software code licensed under GPL Version 2.0 is free software that comes
with ABSOLUTELY NO WARRANTY.  You can redistribute and/or modify such
GPL code under the terms of GPL Version 2.0.  For more details, see the
documentation or "License Notice" file accompanying the IOS-XE software,
or the applicable URL provided on the flyer accompanying the IOS-XE
software.


ROM: 16.9(4r)

us1896-atlanta4-internet-cs uptime is 1 week, 1 day, 20 hours, 0 minutes
Uptime for this control processor is 1 week, 1 day, 20 hours, 3 minutes
System returned to ROM by Reload Command
System restarted at 19:52:10 GMT Mon Jan 23 2023
System image file is "bootflash:asr1000-universalk9.17.06.03a.SPA.bin"
Last reload reason: Reload Command



This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

License Type: Smart License is permanent
License Level: adventerprise
Next reload license Level: adventerprise

The current crypto throughput level is 8000000 kbps


Smart Licensing Status: Registration Not Applicable/Not Applicable

cisco ASR1002-HX (2KH) processor (revision 2KH) with 9886322K/6147K bytes of memory.
Processor board ID FXS2402Q1WS
Router operating mode: Autonomous
Crypto Hardware Module present
8 Gigabit Ethernet interfaces
8 Ten Gigabit Ethernet interfaces
32768K bytes of non-volatile configuration memory.
33554432K bytes of physical memory.
27762687K bytes of eUSB flash at bootflash:.

Configuration register is 0x2102

```

##### STEPS TO REPRODUCE

```
# tasks_cloud_bgp_vrf_cloud_transit.yml
- name: Configure BGP IPv4 VRF cloud_transit
  cisco.ios.ios_bgp_address_family:
    config:
      as_number: 72
      address_family:
        - afi: ipv4
          vrf: cloud_transit
          aggregate_address:
            - address: 10.152.0.0
              netmask: 255.255.0.0
              attribute_map: SLB_CLOUD_SUMMARY_AGGREGATE
            - address: 10.156.0.0
              netmask: 255.255.0.0
              attribute_map: SLB_CLOUD_SUMMARY_AGGREGATE
            - address: 10.192.0.0
              netmask: 255.255.0.0
              attribute_map: SLB_CLOUD_SUMMARY_AGGREGATE
            - address: 10.194.0.0
              netmask: 255.255.0.0
              attribute_map: SLB_CLOUD_SUMMARY_AGGREGATE
            - address: 10.195.0.0
              netmask: 255.255.0.0
              attribute_map: SLB_CLOUD_SUMMARY_AGGREGATE
            - address: 10.196.0.0
              netmask: 255.255.0.0
              attribute_map: SLB_CLOUD_SUMMARY_AGGREGATE
            - address: 10.197.0.0
              netmask: 255.255.0.0
              attribute_map: SLB_CLOUD_SUMMARY_AGGREGATE
          neighbors:
            - neighbor_address: CLOUD_TRANSIT_PEER_AZURE
              peer_group: true
              remote_as: 12076
              local_as:
                number: "{{local_azr_asn}}"
                set: true
                no_prepend:
                  replace_as: true
                  set: true
              fall_over:
                bfd:
                  single_hop: true
                  set: true
              route_maps:
                - name: FROM_TRANSIT_CLOUD_GENERAL
                  in: true
                - name: TO_TRANSIT_CLOUD_GENERAL
                  out: true
            - neighbor_address: CLOUD_TRANSIT_PEER_GCP
              peer_group: true
              remote_as: 16550
              local_as:
                number: "{{local_gcp_asn}}"
                set: true
                no_prepend:
                  replace_as: true
                  set: true
              route_maps:
                - name: FROM_TRANSIT_CLOUD_GENERAL
                  in: true
                - name: TO_TRANSIT_CLOUD_GENERAL
                  out: true
            - neighbor_address: CLOUD_TRANSIT_PEER_SINET_{{it_site_code}}
              peer_group: true
              remote_as: "{{remote_sinet_asn}}"
              local_as:
                number: "{{local_sinet_asn}}"
                set: true
                no_prepend:
                  replace_as: true
                  set: true
              send_community:
                set: true
              route_maps:
                - name: TO_TRANSIT_SINET
                  out: true
            - neighbor_address: CLOUD_TRANSIT_INTERNET_ROUTERS
              peer_group: true
              remote_as: "{{remote_intercolo_asn}}"
              local_as:
                number: "{{local_intercolo_asn}}"
                set: true
                no_prepend:
                  replace_as: true
                  set: true
              send_community:
                set: true
              route_maps:
                - name: "CLOUD_TRANSIT_{{it_site_code_other}}"
                  out: true
            - neighbor_address: "{{remote_nbr_gcp_ip}}"
              peer_group_name: CLOUD_TRANSIT_PEER_GCP
              description: description Google Cloud Partner InterConnect | Google Cloud Router {{gcp_ic_rtr_name}}
              activate: true
            - neighbor_address: "{{remote_nbr_azr_ip}}"
              peer_group_name: CLOUD_TRANSIT_PEER_AZURE
              description: Azure ExpressRoute {{azr_er_name}}
              activate: true
            - neighbor_address: "{{remote_nbr_intercolo_1_ip}}"
              peer_group_name: CLOUD_TRANSIT_INTERNET_ROUTERS
              description: "{{remote_nbr_intercolo_1_name}}_cloud_transit"
              activate: true
            - neighbor_address: "{{remote_nbr_intercolo_2_ip}}"
              peer_group_name: CLOUD_TRANSIT_INTERNET_ROUTERS
              description: "{{remote_nbr_intercolo_2_name}}_cloud_transit"
              activate: true
            - neighbor_address: "{{remote_nbr_dc_primary_ip}}"
              peer_group_name: CLOUD_TRANSIT_PEER_SINET_{{it_site_code}}
              description: "{{remote_nbr_dc_primary_name}}_cloud_transit"
              activate: true
              route_maps:
                - name: FROM-TRANSIT-SINET-{{it_site_code}}-01
                  in: true
            - neighbor_address: "{{remote_nbr_dc_secondary_ip}}"
              peer_group_name: CLOUD_TRANSIT_PEER_SINET_{{it_site_code}}
              description: "{{remote_nbr_dc_secondary_name}}_cloud_transit"
              activate: true
              route_maps:
                - name: FROM-TRANSIT-SINET-{{it_site_code}}-02
                  in: true
            - neighbor_address: "{{remote_nbr_intracolo_ip}}"
              remote_as: 72
              description: "{{remote_nbr_intracolo_name}}_cloud_transit"
              next_hop_self: true
              send_community:
                set: true
              route_maps:
                - name: CLOUD_TRANSIT
                  out: true
    state: replaced

# test_bgp_a4.yml
---
- name: Configuring BGP IPv4 VRF BGP IPv4 VRF cloud_transit address family
  hosts:
    - us1896-atlanta4-internet-cs.mgmt.slb.net
  gather_facts: false
  tasks:
    - import_tasks: tasks_cloud_bgp_vrf_cloud_transit.yml
      vars:
        it_site_code: 'US1896'
        it_site_code_other: 'US1895'
        local_azr_asn: 64528
        azr_er_name: "ER2-US1896-TRANSIT"
        local_gcp_asn: 64528
        gcp_ic_rtr_name: "us1898-use1-2-gcp"
        local_sinet_asn: 64528
        remote_sinet_asn: 64680
        local_intercolo_asn: 4200000003
        remote_intercolo_asn: 4200000002
        remote_nbr_azr_ip: 172.26.9.246
        remote_nbr_gcp_ip: 169.254.152.193
        remote_nbr_intercolo_1_ip: 172.26.11.243
        remote_nbr_intercolo_1_name: "us1895-dallas3-internet-cs"
        remote_nbr_intercolo_2_ip: 172.26.11.244
        remote_nbr_intercolo_2_name: "us1895-dallas4-internet-cs"
        remote_nbr_intracolo_ip: 172.26.11.249
        remote_nbr_intracolo_name: "us1896-atlanta3-internet-cs"
        remote_nbr_dc_primary_ip: 172.26.11.247
        remote_nbr_dc_primary_name: "us1896-atlanta1-dc-cs"
        remote_nbr_dc_secondary_ip: 172.26.11.248
        remote_nbr_dc_secondary_name: "us1896-atlanta2-dc-cs"
```

##### EXPECTED RESULTS

```
us1896-atlanta4-internet-cs#sh run | s add.*tran
 address-family ipv4 vrf cloud_transit
  bgp router-id 172.26.11.250
  aggregate-address 10.197.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.196.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.195.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.194.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.192.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.156.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  aggregate-address 10.152.0.0 255.255.0.0 attribute-map SLB_CLOUD_SUMMARY_AGGREGATE
  neighbor CLOUD_TRANSIT_PEER_AZURE peer-group
  neighbor CLOUD_TRANSIT_PEER_AZURE remote-as 12076
  neighbor CLOUD_TRANSIT_PEER_AZURE local-as 64528 no-prepend replace-as
  neighbor CLOUD_TRANSIT_PEER_AZURE fall-over bfd single-hop
  neighbor CLOUD_TRANSIT_PEER_AZURE route-map FROM_TRANSIT_CLOUD_GENERAL in
  neighbor CLOUD_TRANSIT_PEER_AZURE route-map TO_TRANSIT_CLOUD_GENERAL out
  neighbor CLOUD_TRANSIT_PEER_GCP peer-group
  neighbor CLOUD_TRANSIT_PEER_GCP remote-as 16550
  neighbor CLOUD_TRANSIT_PEER_GCP local-as 64528 no-prepend replace-as
  neighbor CLOUD_TRANSIT_PEER_GCP route-map FROM_TRANSIT_CLOUD_GENERAL in
  neighbor CLOUD_TRANSIT_PEER_GCP route-map TO_TRANSIT_CLOUD_GENERAL out
  neighbor CLOUD_TRANSIT_PEER_SINET_US1896 peer-group
  neighbor CLOUD_TRANSIT_PEER_SINET_US1896 remote-as 64680
  neighbor CLOUD_TRANSIT_PEER_SINET_US1896 local-as 64528 no-prepend replace-as
  neighbor CLOUD_TRANSIT_PEER_SINET_US1896 send-community
  neighbor CLOUD_TRANSIT_PEER_SINET_US1896 route-map TO_TRANSIT_SINET out
  neighbor CLOUD_TRANSIT_INTERNET_ROUTERS peer-group
  neighbor CLOUD_TRANSIT_INTERNET_ROUTERS remote-as 4200000002
  neighbor CLOUD_TRANSIT_INTERNET_ROUTERS local-as 4200000003 no-prepend replace-as
  neighbor CLOUD_TRANSIT_INTERNET_ROUTERS send-community
  neighbor CLOUD_TRANSIT_INTERNET_ROUTERS route-map CLOUD_TRANSIT_US1895 out
  neighbor 169.254.152.193 peer-group CLOUD_TRANSIT_PEER_GCP
  neighbor 169.254.152.193 description description Google Cloud Partner InterConnect | Google Cloud Router us1898-use1-2-gcp
  neighbor 169.254.152.193 activate
  neighbor 172.26.9.246 peer-group CLOUD_TRANSIT_PEER_AZURE
  neighbor 172.26.9.246 description Azure ExpressRoute ER2-US1896-TRANSIT
  neighbor 172.26.9.246 activate
  neighbor 172.26.11.243 peer-group CLOUD_TRANSIT_INTERNET_ROUTERS
  neighbor 172.26.11.243 description us1895-dallas3-internet-cs_cloud_transit
  neighbor 172.26.11.243 activate
  neighbor 172.26.11.244 peer-group CLOUD_TRANSIT_INTERNET_ROUTERS
  neighbor 172.26.11.244 description us1895-dallas4-internet-cs_cloud_transit
  neighbor 172.26.11.244 activate
  neighbor 172.26.11.247 peer-group CLOUD_TRANSIT_PEER_SINET_US1896
  neighbor 172.26.11.247 description us1896-atlanta1-dc-cs_cloud_transit NOTMONITORED
  neighbor 172.26.11.247 activate
  neighbor 172.26.11.247 route-map FROM-TRANSIT-SINET-US1896-01 in
  neighbor 172.26.11.248 peer-group CLOUD_TRANSIT_PEER_SINET_US1896
  neighbor 172.26.11.248 description us1896-atlanta2-dc-cs_cloud_transit
  neighbor 172.26.11.248 activate
  neighbor 172.26.11.248 route-map FROM-TRANSIT-SINET-US1896-02 in
  neighbor 172.26.11.249 remote-as 72
  neighbor 172.26.11.249 description us1896-atlanta3-internet-cs_cloud_transit
  neighbor 172.26.11.249 activate
  neighbor 172.26.11.249 send-community
  neighbor 172.26.11.249 next-hop-self
  neighbor 172.26.11.249 route-map CLOUD_TRANSIT out

```

##### ACTUAL RESULTS

```
ansible-playbook test_bgp_a4.yml -k
SSH password:

PLAY [Configuring BGP IPv4 VRF BGP IPv4 VRF cloud_transit address family] *******************************************************************************************************************************************************************

TASK [Configure BGP IPv4 VRF cloud_transit] *************************************************************************************************************************************************************************************************
[WARNING]: ansible-pylibssh not installed, falling back to paramiko
fatal: [us1896-atlanta4-internet-cs.mgmt.slb.net]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (basic.py) module: config.address_family.neighbors.default-originate. Supported parameters include: state, config, running_config."}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
us1896-atlanta4-internet-cs.mgmt.slb.net : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
