### ISSUE TITLE
cisco.ios.ios_bgp_global - shutdown of the BGP neighbor works, but not "no shut"

### ISSUE THREAD

**Issue by okin8** [ansible-collections/cisco.ios#744]
##### SUMMARY
I'm able to shutdown bgp neighbor using following task, but I cannot revert it using "set: false" 

This is how I shutdown 
```
    - name: Shut BGP peer
      cisco.ios.ios_bgp_global:
        config:
          as_number: "{{ local_bgp_as }}"
          neighbors:
            - address: "{{ local_bgp_neighbor }}"
              remote_as: 65000
              shutdown: 
                set: true
        state: merged
```

This is how I try to revert shutdown 

```
    - name: Unshut BGP peer
      cisco.ios.ios_bgp_global:
        config:
          as_number: "{{ local_bgp_as }}"
          neighbors:
            - address: "{{ local_bgp_neighbor }}"
              shutdown: 
                set: false
        state: merged
```

Task is shutting the neighbor 

```
changed: [R48] => {
    "after": {
        "as_number": "65001", 
        "bgp": {
            "log_neighbor_changes": true
        }, 
        "neighbors": [
            {
                "neighbor_address": "192.168.10.2", 
                "remote_as": "65000", 
                "shutdown": {
                    "set": true
                }
            }, 
            {
                "neighbor_address": "192.168.13.2", 
                "remote_as": "65003"
            }
        ]
    }, 
    "before": {
        "as_number": "65001", 
        "bgp": {
            "log_neighbor_changes": true
        }, 
        "neighbors": [
            {
                "neighbor_address": "192.168.10.2", 
                "remote_as": "65000", 
                "shutdown": {
                    "set": true
                }
            }, 
            {
                "neighbor_address": "192.168.13.2", 
                "remote_as": "65003"
            }
        ]
    }, 
    "changed": true, 
    "commands": [
        "router bgp 65001", 
        "neighbor 192.168.10.2 shutdown"
    ], 

```
