### ISSUE TITLE
ios_ospfv2: network parameter in EXAMPLES should be list 

### ISSUE THREAD

**Issue by akira6592** [ansible-collections/cisco.ios#750]
##### SUMMARY

The `config.processes.network` parameter  in EXAMPLES should be `list`. Like below:

```yaml
        network:
          - address: 198.51.100.0
            wildcard_bits: 0.0.0.255
            area: 5
```

The current example is not `list` as  below.

```yaml
        network:
          address: 198.51.100.0
          wildcard_bits: 0.0.0.255
          area: 5
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

- `cisco.ios.ios_ospfv2` module

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.1]
  config file = /Users/sakana/ansible/ansible.cfg
  configured module search path = ['/Users/sakana/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sakana/envs/a7/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/sakana/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/sakana/envs/a7/bin/ansible
  python version = 3.9.16 (main, Dec  7 2022, 10:15:43) [Clang 14.0.0 (clang-1400.0.29.202)] (/Users/sakana/envs/a7/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```
