### ISSUE TITLE
cisco.ios.ios_system state

### ISSUE THREAD

**Issue by jorgenspange** [ansible-collections/cisco.ios#769]
When i run the module like this:
```yml
- name: set hostname and domain-name and disable dns-lookup
  cisco.ios.ios_system:
    hostname: "{{ inventory_hostname }}"
    domain_name: "{{ ip_domain_name }}"
    lookup_enabled: false
    domain_search:
    name_servers:
    state: present
``` 
  I would expect all existing name_servers and domain_search to be deleted, but it's not.
  
  this also removes everything including hostname:
  ```yml
  - name: remove name servers and domain-lists
    cisco.ios.ios_system:
      domain_search:
      name_servers:
      state: absent
```
