### ISSUE TITLE
cisco.ios.ios_acls - list index out of range

### ISSUE THREAD

**Issue by jorgenspange** [ansible-collections/cisco.ios#792]
I have a playbook consisting of a number of roles for confiugration compliance.
'Suddenly' one of the roles has started failing towards certain switches.

The problem is with the cisco.ios.ios_acls and the output i get is:

```
fatal: [Cisco-Catalyst4507]: FAILED! => changed=false 
  msg: list index out of range
```

Worked very well up until some point this week, not aware of patches installed or anything, does anyone have suggestions to how I can troubleshoot this, or have been out for the same problem themselves?

Here's the task, even though it fails for all tasks with cisco.ios.ios_acls

```
---
# tasks file for network_snmp

- name: create extended acl for snmp
  cisco.ios.ios_acls:
    config:
      - afi: ipv4
        acls:
          - name: DNB-SNMP
            acl_type: extended
            aces:
              - grant: permit
                sequence: 10
                protocol_options:
                  ip: true
                source:
                  host: "{{ snmp_server_1 }}"
                destination:
                  any: true
              - grant: permit
                sequence: 20
                protocol_options:
                  ip: true
                source:
                  host: "{{ snmp_server_2 }}"
                destination:
                  any: true
              - grant: permit
                sequence: 30
                protocol_options:
                  ip: true
                source:
                  host: "{{ snmp_server_3 }}"
                destination:
                  any: true
              - grant: deny
                sequence: 40
                protocol_options:
                  ip: true
                source:
                  any: true
                destination:
                  any: true
                log:
                  set: true
    state: replaced
```

Here's the output with -vvv:
https://codeshare.io/loZWeZ
