### ISSUE TITLE
ios_bgp_global: per neighbor timer values attempts to configure global bgp timers

### ISSUE THREAD

**Issue by rbh1981** [ansible-collections/cisco.ios#794]
##### SUMMARY

When attempting to set per neighbor bgp timers the module instead attempts to configure global bgp timers

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_bgp_global

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.4]
  config file = /home/rbh/Ansible/cisco/ansible.cfg
  configured module search path = ['/home/rbh/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rbh/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/rbh/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rbh/.local/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```paste below
# /home/rbh/.local/lib/python3.10/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  4.4.0  

# /home/rbh/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  4.4.0  

```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/rbh/Ansible/cisco/ansible.cfg
DEFAULT_GATHERING(/home/rbh/Ansible/cisco/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/rbh/Ansible/cisco/ansible.cfg) = ['/home/rbh/Ansible/cisco/hosts.yaml']
DISPLAY_SKIPPED_HOSTS(/home/rbh/Ansible/cisco/ansible.cfg) = False
HOST_KEY_CHECKING(/home/rbh/Ansible/cisco/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/rbh/Ansible/cisco/ansible.cfg) = 30
PERSISTENT_CONNECT_TIMEOUT(/home/rbh/Ansible/cisco/ansible.cfg) = 60

```

##### OS / ENVIRONMENT

Cisco IOSv 15.9(3)M3

##### STEPS TO REPRODUCE

Run the following against a device

```yaml
---
- name: "Configure BGP Global"
  cisco.ios.ios_bgp_global:
    config:
      as_number: '64537'
      bgp:
        log_neighbor_changes: true
        router_id:
          address: 10.2.1.1
      neighbors:
      - neighbor_address: 10.254.1.2
        remote_as: '64537'
        timers:
          holdtime: 30
          interval: 10

```

##### EXPECTED RESULTS

bgp commands sent to device should be 'neighbor 10.254.1.2 timers 10 30'

##### ACTUAL RESULTS

ansible-playbook [core 2.14.4]
  config file = /home/rbh/Ansible/cisco/ansible.cfg
  configured module search path = ['/home/rbh/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rbh/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/rbh/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rbh/.local/bin/ansible-playbook
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /home/rbh/Ansible/cisco/ansible.cfg as config file
host_list declined parsing /home/rbh/Ansible/cisco/hosts.yaml as it did not pass its verify_file() method
script declined parsing /home/rbh/Ansible/cisco/hosts.yaml as it did not pass its verify_file() method
Parsed /home/rbh/Ansible/cisco/hosts.yaml inventory source with yaml plugin
redirecting (type: action) cisco.ios.ios_bgp_global to cisco.ios.ios
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: config-bgp.yml ***********************************************************************************************************************************************
1 plays in config-bgp.yml

PLAY [Configure Cisco BGP] *********************************************************************************************************************************************
redirecting (type: action) cisco.ios.ios_bgp_global to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_bgp_global to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_bgp_global to cisco.ios.ios

TASK [Configure BGP Global] ********************************************************************************************************************************************
task path: /home/rbh/Ansible/cisco/config-bgp.yml:7
fatal: [iosv-2]: FAILED! => {
    "changed": false,
    "module_stderr": "timers bgp 30\r\ntimers bgp 30\r\n% Incomplete command.\r\n\r\niosv-2(config-router)#",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}

```paste below
    "commands": [
        "router bgp 64537",
        "neighbor 10.254.1.2 remote-as 64537",
        "timers bgp 30"
    ],

```

**Comment by rbh1981** [comment]
Found duplicate issue #638 which was closed with the recommendation to use the bgp_address_family module. The problem I face with this is that configuring neighbor timers under bgp_address_family module seems to result in the config being placed in the global bgp section on the IOS XE router, at least as of my testing with 15.9(3)M3 on CML. This makes the configuration not idempotent. 

Using the folowing bgp_address_family config with neighbor timers
```
bgp_address_family:
  as_number: '64536'
  address_family:
  - afi: ipv4
    neighbors:
    - neighbor_address: 10.254.1.2
      activate: true
      soft_reconfiguration: true
      remote_as: 63537
      timers:
        interval: 10
        holdtime: 30
    networks:
    - address: 10.1.0.0
      mask: 255.255.0.0
```

Results in the following config on the router (neighbor timers config is under global router bgp and not address family) which is not idempotent on the next bgp_address_family module execution
```
router bgp 64536
 neighbor 10.254.1.2 remote-as 63537
 neighbor 10.254.1.2 timers 10 30
 !
 address-family ipv4
  network 10.1.0.0 mask 255.255.0.0
  neighbor 10.254.1.2 activate
  neighbor 10.254.1.2 soft-reconfiguration inbound
 exit-address-family
```
