### ISSUE TITLE
cisco.ios.ios_l2_interfaces module by default configuring spanning tree portfast

### ISSUE THREAD

**Issue by saifvs** [ansible-collections/cisco.ios#796]
##### SUMMARY

when running cisco.ios.ios_l2_interfaces module to configure access port, it is by deault enabling portfast on the interface even though I have not specified.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_l2_interfaces, access vlan configuration

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/saif/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/saif/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```paste below
# /home/saif/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  4.3.1  

# /usr/lib/python3/dist-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  3.3.2 
```

##### CONFIGURATION

```paste below
CALLBACKS_ENABLED(/etc/ansible/ansible.cfg) = ['timer']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 5
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

##### STEPS TO REPRODUCE

1. Setup a yaml variable for cisco switch in host_vars.
For eg : 
```
interface:
  GigabitEthernet3/0/1:
    description: 
    mode: trunk
  GigabitEthernet3/0/2:
    access_vlan: '7'
    mode: access
    voice_vlan: '25'`
```
2. in the task add cisco.ios.ios_l2_interfaces to configure the access port.

Before the chnage
```
Switch#sh run | in portf
Switch#
```

After the change
```
Switch#sh run | in portf
 spanning-tree portfast
 spanning-tree portfast
 spanning-tree portfast
```

```yaml

- name: assign access port
  cisco.ios.ios_l2_interfaces:
    config:
      - name: "{{item.key}}"
        mode: "{{item.value.mode | default (omit)}}"
        access:
          vlan: "{{item.value.access_vlan | default (omit)}}"
        voice:
          vlan: "{{ item.value.voice_vlan | default (omit) }}"
    state: merged
  with_dict: "{{ interface }}"
  when: (item.value.mode is defined and item.value.mode == 'access')

```

##### EXPECTED RESULTS

I don't want to enable portfast on all the access ports, wanted to have full control on where to enable portfast.
```
!
interface GigabitEthernet3/0/2
 switchport access vlan 7
 switchport mode access
 switchport voice vlan 25
!
```

##### ACTUAL RESULTS

```
!
interface GigabitEthernet3/0/2
 switchport access vlan 7
 switchport mode access
 switchport voice vlan 25
 spanning-tree portfast
!
```

```paste below
skipping: [sw-lab-01] => (item={'key': 'GigabitEthernet3/0/1', 'value': {'description': '***** Trunk to 2nd Sw 10.200.200.173 ****', 'mode': 'trunk'}}) 
[WARNING]: ansible-pylibssh not installed, falling back to paramiko
changed: [sw-lab-01] => (item={'key': 'GigabitEthernet3/0/2', 'value': {'access_vlan': '7', 'mode': 'access', 'voice_vlan': '25'}})

```
