### ISSUE TITLE
logging history size seems to be broken.

### ISSUE THREAD

**Issue by sachinsprasad** [ansible-collections/cisco.ios#803]
##### SUMMARY
Logging history size 500 works on the switch but throws an error when using ansible
Switch(config)#logging history size 500
Switch(config)#

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_logging_global module

##### ANSIBLE VERSION
[sachinp@ansible-vmw ~]$ ansible --version
ansible [core 2.14.3]
  config file = /home/sachinp/ansible.cfg
  configured module search path = ['/home/sachinp/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/sachinp/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

```

##### COLLECTION VERSION
<!--- Paste verbatim output from "ansible-galaxy collection list <namespace>.<collection>"  between the quotes
for example: ansible-galaxy collection list community.general
-->
```paste below
[sachinp@ansible-vmw ~]$ ansible-galaxy collection list community.general

# /usr/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.4.0
```

##### CONFIGURATION

```
 - name: Configure Logging
      cisco.ios.ios_logging_global:
        config:
          userinfo: true
          buffered:
            size: 65536
          reload:
            severity: debugging
          console:
            severity: critical
          monitor:
            severity: critical
          hosts:
            - hostname: "{{ syslog_server }}"
          history:
           severity: debugging
           size: 500

```

##### OS / ENVIRONMENT

Fedora release 37 (Thirty Seven)

##### STEPS TO REPRODUCE

Run the above playbook

```
Already pasted above

```

##### ACTUAL RESULTS

ASK [Configure Logging] **********************************************************************************************************************************************************************************************************************
fatal: [atl01-sw-lab01]: FAILED! => {"changed": false, "module_stderr": "logging history 500 debugging\r\nlogging history 500 debugging\r\n                 ^\r\n% Invalid input detected at '^' marker.\r\n\r\natl01-sw-lab01(config)#", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}

```paste below

```
