### ISSUE TITLE
OSPFv2 capability vrf-lite uses underscore in command generation

### ISSUE THREAD

**Issue by mathewblackberry** [ansible-collections/cisco.ios#808]
##### SUMMARY
Module cisco.ios.ios_ospfv2 does not correctly create the capability vrf-lite command.
It instead creates "capability vrf_lite"

[plugins/module_utils/network/ios/rm_templates/ospfv2.py]

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_ospfv2

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below
4.5.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- name: Build OSPF Process
  cisco.ios.ios_ospfv2:
    config:
      processes:
        - process_id: 1
          router_id: 0.0.0.1
          vrf: vrf
          areas: 
            area_id: 0
          capability:
            vrf_lite: true
```

##### EXPECTED RESULTS

create command capability vrf-lite

##### ACTUAL RESULTS

create command capability vrf_lite

```paste below

```
