### ISSUE TITLE
ios_facts for lag_interfaces returns a list when lags exist and an empty dictionary when lags do not exist

### ISSUE THREAD

**Issue by wollmannbruno** [ansible-collections/cisco.ios#814]
##### SUMMARY
When a switch has lag interfaces configured, the facts module returns a **list** of dictionaries for these interfaces.
When a switch has no lag interfaces configured, the facts module returns an empty **dictionary**.

This inconsistency causes extra processing of the variable in a play.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lag_interfaces inside the cisco.ios.ios_facts module.

##### ANSIBLE VERSION
```
ansible [core 2.13.8]
  config file = /home/bwollmann/repos/iac/ansible.cfg
  configured module search path = ['/home/bwollmann/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bwollmann/venv/ans2_9_24/lib/python3.8/site-packages/ansible
  ansible collection location = /home/bwollmann/.ansible/collections
  executable location = /home/bwollmann/venv/ans2_9_24/bin/ansible
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
# /home/bwollmann/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  4.5.0  
```

##### CONFIGURATION
```
COLLECTIONS_PATHS(/home/bwollmann/repos/iac/ansible.cfg) = ['/home/bwollmann/.ansible/collections']
DEFAULT_GATHERING(/home/bwollmann/repos/iac/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/bwollmann/repos/iac/ansible.cfg) = ['/home/bwollmann/repos/iac/hosts']
DEFAULT_ROLES_PATH(/home/bwollmann/repos/iac/ansible.cfg) = ['/home/bwollmann/repos/iac/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/bwollmann/repos/iac/ansible.cfg) = /home/bwollmann/repos/vault
HOST_KEY_CHECKING(/home/bwollmann/repos/iac/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Cisco IOS XE Software, Version 16.12.04
Cisco IOS Software [Gibraltar], Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 16.12.4, RELEASE SOFTWARE (fc5)
ROM: IOS-XE ROMMON
BOOTLDR: CAT3K_CAA Boot Loader (CAT3K_CAA-HBOOT-M) Version 4.78, RELEASE SOFTWARE (P)
|Switch|Ports|Model|SW Version|SW Image|Mode|
|------|-----|-----|----------|----------|----|
|*    1|32|WS-C3850-24U|16.12.4|CAT3K_CAA-UNIVERSALK9|INSTALL

##### STEPS TO REPRODUCE
Use the ios_facts module to gather the lag_interfaces from switches with and without lag interfaces configured.

```yaml
---
- name: GET FACTS
  hosts: swt-rga-01-dside,swt-rga-a500-a
  gather_facts: no

  tasks:
    - name: GET LAG INTERFACES
      cisco.ios.ios_facts:
        gather_network_resources: lag_interfaces
      register: lag_ints

    - name: ASSOCIATE VARIABLE TO LIST OF LAG INTERFACES FROM FACTS
      ansible.builtin.set_fact:
        lags: "{{ lag_ints['ansible_facts']['ansible_network_resources']['lag_interfaces'] }}"

    - name: PRINT LAGS
      ansible.builtin.debug:
        var: lags
```

##### EXPECTED RESULTS
I would expect that the same type of data structure be returned whether there are lag interfaces configured or not. Either return a list in both cases or a dictionary in both cases.

```
ok: [swt-rga-01-dside] => {
    "lags": []
}
ok: [swt-rga-a500-a] => {
    "lags": [
        {
            "members": [
                {
                    "member": "TenGigabitEthernet1/1/3",
                    "mode": "active"
                },
                {
                    "member": "TenGigabitEthernet2/1/3",
                    "mode": "active"
                }
            ],
            "name": "Port-channel5"
        }
    ]
}
```
![empty_list](https://user-images.githubusercontent.com/17262574/234355381-8ba79c48-efdf-4c88-9f03-249176481a64.jpg)

##### ACTUAL RESULTS
ios_facts returns a dictionary when no lag interfaces exist and a list when they do exist.

```
ok: [swt-rga-01-dside] => {
    "lags": {}
}
ok: [swt-rga-a500-a] => {
    "lags": [
        {
            "members": [
                {
                    "member": "TenGigabitEthernet1/1/3",
                    "mode": "active"
                },
                {
                    "member": "TenGigabitEthernet2/1/3",
                    "mode": "active"
                }
            ],
            "name": "Port-channel5"
        }
    ]
}
```
![empty_dict](https://user-images.githubusercontent.com/17262574/234355473-c5d90e62-23a9-4b35-93ed-4a7ac2383a91.jpg)

**Comment by KB-perByte** [comment]
@wollmannbruno, would you share the output of your `sh running-config | section ^interface` command from the appliance where there are no facts generated?
As I don't see the issue at my end, the device when some lag-specific configuration is present, 
```
  lags:
  - members:
    - member: GigabitEthernet2
      mode: active
    name: Port-channel10
  - members:
    - member: GigabitEthernet4
      mode: active
    name: Port-channel20
  - members:
    - {}
    name: Port-channel30
```
and when no lag-specific configuration is present
```
  lags:
  - members:
    - {}
    name: Port-channel10
  - members:
    - {}
    name: Port-channel20
  - members:
    - {}
    name: Port-channel30
```
Regards
