### ISSUE TITLE
When trying to utilise the ( ios_l3_interfaces and ios_interfaces ) module more than once within a playbook, a ConnectionError is thrown.

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/cisco.ios#85]
_From @luwei19941010 on Jun 18, 2020 06:34_

##### SUMMARY
When trying to utilise the ( ios_l3_interfaces and ios_insterfaces ) module more than once within a playbook, a ConnectionError is thrown.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-connection
connection.py

##### ANSIBLE VERSION
```
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
[root@luwei ~]# 
```

##### OS / ENVIRONMENT
CentOS-7-x86_64-DVD-1804
ROM: 3700 Software (C3725-ADVIPSERVICESK9-M), Version 12.4(3), RELEASE SOFTWARE (fc2)

##### STEPS TO REPRODUCE
```
ansible-playbook.yml
---

- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: 192.168.174.200

  tasks:
    - name: Set GigabitEthernet0/3 IPv4 address
      ios_l3_interfaces:
        config:
          - name: FastEthernet0/1    
            ipv4:
            - address: 192.168.0.1/24
        state: merged 
    - name: Merge provided configuration with device configuration
      ios_interfaces:
        config:
          - name: FastEthernet0/1
            description: 'Configured and Merged by Ansible Network'
            enabled: True
        state: merged
```

##### EXPECTED RESULTS
interface f0/1 config ip and port status change up.

##### ACTUAL RESULTS
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/bin/ansible-connection", line 308, in main
    conn.update_play_context(pc_data)
  File "/usr/local/python3/lib/python3.6/site-packages/ansible/module_utils/connection.py", line 185, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
```

_Copied from original issue: ansible/ansible#70135_
