### ISSUE TITLE
Add parsed and rendered states to ios_vrf

### ISSUE THREAD

**Issue by nleiva** [ansible-collections/cisco.ios#886]
##### SUMMARY

cisco.ios.ios_vrf only supports present and absent states today. Would it be possible to add the remaining network resource  module state options to it?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`cisco.ios.ios_vrf`

##### ADDITIONAL INFORMATION

It will allow us to test this module without a remote network device.

```yaml
 - name: Parse VRFs for provided configuration
   cisco.ios.ios_vrf:
     running_config: "{{ lookup('file', config) }}"
     state: parsed
```

and:

```yaml
 - name: Parse VRFs for provided configuration
   cisco.ios.ios_vrf:
     config: "{{ lookup('file', config) }}"
     state: rendered
```
