### ISSUE TITLE
Add parsed and rendered states to ios_system

### ISSUE THREAD

**Issue by nleiva** [ansible-collections/cisco.ios#887]
##### SUMMARY

cisco.ios.ios_system only supports present and absent states today. Would it be possible to add the remaining network resource  module state options to it?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`cisco.ios.ios_system`

##### ADDITIONAL INFORMATION

It will allow us to test this module without a remote network device.

```yaml
 - name: Parse system attributes for provided configuration
   cisco.ios.ios_system:
     running_config: "{{ lookup('file', config) }}"
     state: parsed
```

and:

```yaml
 - name: Render system attributes for provided configuration
   cisco.ios.ios_system:
     config: "{{ lookup('file', config) }}"
     state: rendered
```
