### ISSUE TITLE
ios_vlans tries to connect to device for parsed

### ISSUE THREAD

**Issue by nleiva** [ansible-collections/cisco.ios#888]
##### SUMMARY

Not sure why, but `ios_vlans` is attempting to connect to a device? to parse the data from a local running config?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

 `cisco.ios.ios_vlans`

##### ANSIBLE VERSION

```paste below
2.15
```

##### COLLECTION VERSION

```paste below
N/A
```

##### CONFIGURATION

```paste below
N/A
```

##### STEPS TO REPRODUCE

Pass a config to the following task:

```yaml
- name: Parse VLANs for provided configuration
  cisco.ios.ios_vlans:
    running_config: "{{ lookup('file', config) }}"
    state: parsed
  register: ios_vlans
```

I use vars:

```yaml
vars:
  ansible_connection: ansible.netcommon.network_cli
  ansible_network_os: cisco.ios.ios
```

This works fine for all other Cisco IOS resource modules.

##### EXPECTED RESULTS

Parse VLANs from file.

##### ACTUAL RESULTS

The error says: "ssh connect failed: Connection refused"

```python
TASK [Parse VLANs for provided configuration] ************************************************************************************************************
task path: /home/nleiva/projects/ansible-config-template/parse_tasks.yml:92
The full traceback is:
  File "/usr/share/ansible/collections/ansible_collections/cisco/ios/plugins/module_utils/network/ios/ios.py", line 60, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": null,
            "running_config": "hostname TestRouter\n!\nno ip domain lookup\n...\n!",
            "state": "parsed"
        }
    },
    "msg": "ssh connection failed: ssh connect failed: Connection refused"
}
```
