### ISSUE TITLE
cisco.ios.ios_service - Error related to the private-config-encryption feature

### ISSUE THREAD

**Issue by earendilfr** [ansible-collections/cisco.ios#910]
##### SUMMARY
The feature `private-config-encryption` is indicated in the list of defaults services that should be enable but, on many switches, this service is not available.
So, this part should be conditioned to the fact that you seen the this services in the current configuration...

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_service 

##### ANSIBLE VERSION
<!--- Paste verbatim output from "ansible --version" between quotes -->
```paste below
ansible [core 2.15.2]
  config file = /opt/ansible/ansible.cfg
  configured module search path = ['/home/dadmrossetam/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/ansible8.2/lib64/python3.11/site-packages/ansible
  ansible collection location = /opt/ansible/collections
  executable location = /opt/ansible/ansible8.2/bin/ansible
  python version = 3.11.2 (main, Jun 22 2023, 04:35:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/opt/ansible/ansible8.2/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
<!--- Paste verbatim output from "ansible-galaxy collection list <namespace>.<collection>"  between the quotes
for example: ansible-galaxy collection list community.general
-->
```paste below
ansible-galaxy collection list cisco.ios

# /opt/ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  5.0.0
```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below
ACHE_PLUGIN(/opt/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/opt/ansible/ansible.cfg) = /tmp/facts_cache
CACHE_PLUGIN_TIMEOUT(/opt/ansible/ansible.cfg) = 7200
COLLECTIONS_PATHS(/opt/ansible/ansible.cfg) = ['/opt/ansible/collections']
CONFIG_FILE() = /opt/ansible/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(/opt/ansible/ansible.cfg) = ['/opt/ansible/filter_plugins']
DEFAULT_GATHERING(/opt/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/opt/ansible/ansible.cfg) = ['/opt/ansible/hosts']
DEFAULT_ROLES_PATH(/opt/ansible/ansible.cfg) = ['/opt/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/opt/ansible/ansible.cfg) = debug
DEFAULT_VAULT_PASSWORD_FILE(/opt/ansible/ansible.cfg) = /opt/ansible/.vault_pass
DEPRECATION_WARNINGS(/opt/ansible/ansible.cfg) = True
EDITOR(env: EDITOR) = vim
PAGER(env: PAGER) = less
PERSISTENT_COMMAND_TIMEOUT(/opt/ansible/ansible.cfg) = 60
TRANSFORM_INVALID_GROUP_CHARS(/opt/ansible/ansible.cfg) = ignore
```

##### OS / ENVIRONMENT
<!--- Provide all relvant information below, e.g. target OS versions, network device firmware, etc. -->
Linux / Rocky Linux 8.8
Target switches: `Cisco WS-C3850-24P` or `Cisco C9300-48P`

##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->

And the module tasks:
```yaml
- name: Configure services
  tags: [ "service" ]
  cisco.ios.ios_service:
    state: "replaced"
    config:
      call_home: true
      compress_config: true
      counters: 5
      password_encryption: true
      tcp_keepalives_in: true
      tcp_keepalives_out: true
      timestamps:
        - msg: "debug"
          timestamp: "datetime"
          datetime_options:
            localtime: true
            msec: true
            show_timezone: true
            year: true
        - msg: "log"
          timestamp: "datetime"
          datetime_options:
            localtime: true
            msec: true
            show_timezone: true
            year: true
      unsupported_transceiver: true
  register: out_ios_service
```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->
This configuration should not be pushed if:
- not present in the service config
- not present in the current configuration

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->

<!--- Paste verbatim command output between quotes -->
```paste below
TASK [system : Configure services] *********************************************************************************************************************************************************************************************************fatal: [hostname]: FAILED! => {                                                                                                                                                                                                            "changed": false
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

service private-config-encryption
service private-config-encryption
          ^
% Invalid input detected at '^' marker.

hostname(config)#
```
