### ISSUE TITLE
Issues with setting filter_list , as_path_acl on bgp_address_family

### ISSUE THREAD

**Issue by dirennaidoo-salt** [ansible-collections/cisco.ios#913]
##### SUMMARY

Get an error when I try to set as_path_acl on a BGP neighbor using bgp_address_family module. Error is "module_stderr": "can only concatenate str (not \"int\") to str"

Very similar to this issue: https://github.com/ansible-collections/cisco.ios/issues/569
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_bgp_address_family
##### ANSIBLE VERSION

```paste below
ansible [core 2.14.3]
  config file = /home/user/projects/networkautomation-ansible/device-provisioning/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.11.1 (main, Mar  8 2023, 17:54:41) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] (/usr/local/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True```

##### COLLECTION VERSION
<!--- Paste verbatim output from "ansible-galaxy collection list <namespace>.<collection>"  between the quotes
for example: ansible-galaxy collection list community.general
-->
```paste below
# /home/user/.local/lib/python3.11/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  4.3.1  

# /home/user/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  5.0.0  
```

##### CONFIGURATION

```paste below
ACTION_WARNINGS(/home/user/projects/ansible.cfg) = False
CONFIG_FILE() = /home/user/projects/ansible.cfg
DEFAULT_FORKS(/home/user/projects/ansible.cfg) = 10
DEFAULT_GATHERING(/home/user/projects/ansible.cfg) = explicit
HOST_KEY_CHECKING(/home/user/projects/ansible.cfg) = False
INTERPRETER_PYTHON(/home/user/projects/ansible.cfg) = /usr/local/bin/python3.11
PERSISTENT_COMMAND_TIMEOUT(/home/user/projects/ansible.cfg) = 90
RETRY_FILES_ENABLED(/home/user/projects/ansible.cfg) = False
```

##### OS / ENVIRONMENT

client: CentOS 7
target: Cisco IOS XE Software, Version 17.07
##### STEPS TO REPRODUCE

```yaml
- name: Add IPv4 BGP address family config
  cisco.ios.ios_bgp_address_family:
    config:
      as_number: 1234
      address_family:
      - afi: ipv4
        neighbor:
          - address: 100.64.25.1
            activate: true
            soft_reconfiguration: true 
            maximum_prefix: 
              number: 6000
              warning_only: true
            filter_list: 
                as_path_acl: 1
                out: true
            route_maps:
              - name: route-in
                in: true
              - name: route-out
                out: true
            send_community:
              set: true 
```

##### EXPECTED RESULTS

            "router bgp 1234",
            "address-family ipv4",
            "neighbor 100.64.25.1 activate",
            "neighbor 100.64.25.1 maximum-prefix 6000 warning-only",
            "neighbor 100.64.25.1 filter-list 1 out"
            "neighbor 100.64.25.1 send-community",
            "neighbor 100.64.25.1 soft-reconfiguration inbound",
            "neighbor 100.64.25.1 route-map route-in in",
            "neighbor 100.64.25.1 route-map route-out out",

##### ACTUAL RESULTS

```paste below
FAILED! => {"changed": false, "module_stderr": "can only concatenate str (not \"int\") to str", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}
```
