### ISSUE TITLE
When using the cisco.ios.ios_prefix_lists module when using the state delete with ipv6, the last three ipv4  prefix lists are sent to be deleted instead of the ipv6 prefix lists specified in the playbook

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.ios#914]
##### SUMMARY

When using the cisco.ios.ios_prefix_lists module when using the state delete with ipv6, the last three ipv4  prefix lists are sent to be deleted instead of the ipv6 prefix lists specified in the playbook.

Example before configuration:

```
ipv6 prefix-list Ansible-prefix-list-test-ipv6-1: 1 entries
   seq 10 permit ::/0
```
Configuration change data model:
```
- configs:
      - prefix_lists:
          - afi: "ipv6"
            prefix_lists:
              - name: "Ansible-prefix-list-test-ipv6-1"
        state: deleted
```

After Run through the playbook:
```

ipv6 prefix-list Ansible-prefix-list-test-ipv6-1: 1 entries
   seq 10 permit ::/0
```

IPv6 prefix list to be deleted is still there.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_prefix_lists module

##### ANSIBLE VERSIO

```paste below
ansible [core 2.12.6]
  config file = /home/REDACTED/.ansible.cfg
  configured module search path = ['/home/REDACTED/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/REDACTED/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.2
  libyaml = True

##### COLLECTION VERSION
<!--- Paste verbatim output from "ansible-galaxy collection list
<namespace>.<collection>"  between the quotes
for example: ansible-galaxy collection list community.general
-->
```paste below
collection Version
---------- -------
cisco.ios             5.0.0
```

##### CONFIGURATION

```paste below
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/REDACTED/.ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/REDACTED/.ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/REDACTED/.ansible.cfg) = 120
DEPRECATION_WARNINGS(/home/REDACTED/.ansible.cfg) = False
GALAXY_IGNORE_CERTS(/home/REDACTED/.ansible.cfg) = True
GALAXY_SERVER_LIST(/home/REDACTED/.ansible.cfg) = ['inbound_yeti_repo', 'published_repo', 'rh-certified_repo']
HOST_KEY_CHECKING(/home/REDACTED/.ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/home/REDACTED/.ansible.cfg) = True
PERSISTENT_COMMAND_TIMEOUT(/home/REDACTED/.ansible.cfg) = 300
PERSISTENT_CONNECT_TIMEOUT(/home/REDACTED/.ansible.cfg) = 120
RETRY_FILES_ENABLED(/home/REDACTED/.ansible.cfg) = False

```

##### OS / ENVIRONMENT

System image file is "bootflash:cat4500e-entservicesk9-mz.152-4.E2.bin"
Cisco IOS

##### STEPS TO REPRODUCE

Add an IPv6 prefix list to an IOS device and try and use the deleted state to remove it.

Playbook Run with -vvv:
```
changed: [4948E-02] => changed=true 
  after:
  - afi: ipv4
    prefix_lists:
    - description: REDACTED routes to Vesta-SLC
      name: VestaSLC-out
    - description: TEST-PREFIX-LIST1
      name: prefix1
    - description: TEST-PREFIX-LIST2
      name: prefix2
  - afi: ipv6
    prefix_lists:
    - entries:
      - action: permit
        prefix: 2607:FB90:2400::/40
        sequence: 6
      name: ADV-CDN-SIGNAL-OUT-V6
    - description: Test ipv6 prefix-list for Ansible
      entries:
      - action: permit
        prefix: ::/0
        sequence: 10
      name: Ansible-prefix-list-test-ipv6
    - description: Test ipv6 prefix-list for Ansible
      entries:
      - action: permit
        prefix: ::/0
        sequence: 10
      name: Ansible-prefix-list-test-ipv6-1
    - entries:
      - action: deny
        prefix: 2607:FB90:2400::/40
        sequence: 7
      name: BGP-FILTER-TO-CORE-V6
    - entries:
      - action: permit
        prefix: FD00:976A:C202:1F::/64
        sequence: 5
      - action: permit
        prefix: FD00:976A:C206:10::/64
        sequence: 10
      - action: permit
        prefix: FD00:976A:B69B:193E::/64
        sequence: 15
      - action: permit
        prefix: DD00:976A:C206:10::/64
        sequence: 20
      name: PREFIX_IPv6_TEST1
    - entries:
      - action: permit
        ge: 64
        prefix: ::/0
        sequence: 10
      name: prefix-list-modify-test-ipv6
  before:
  - afi: ipv4
    prefix_lists:
    - description: REDACTED routes to Vesta-SLC
      name: VestaSLC-out
    - description: TEST-PREFIX-LIST1
      name: prefix1
    - description: TEST-PREFIX-LIST2
      name: prefix2
  - afi: ipv6
    prefix_lists:
    - entries:
      - action: permit
        prefix: 2607:FB90:2400::/40
        sequence: 6
      name: ADV-CDN-SIGNAL-OUT-V6
    - description: Test ipv6 prefix-list for Ansible
      entries:
      - action: permit
        prefix: ::/0
        sequence: 10
      name: Ansible-prefix-list-test-ipv6
    - description: Test ipv6 prefix-list for Ansible
      entries:
      - action: permit
        prefix: ::/0
        sequence: 10
      name: Ansible-prefix-list-test-ipv6-1
    - entries:
      - action: deny
        prefix: 2607:FB90:2400::/40
        sequence: 7
      name: BGP-FILTER-TO-CORE-V6
    - entries:
      - action: permit
        prefix: FD00:976A:C202:1F::/64
        sequence: 5
      - action: permit
        prefix: FD00:976A:C206:10::/64
        sequence: 10
      - action: permit
        prefix: FD00:976A:B69B:193E::/64
        sequence: 15
      - action: permit
        prefix: DD00:976A:C206:10::/64
        sequence: 20
      name: PREFIX_IPv6_TEST1
    - entries:
      - action: permit
        ge: 64
        prefix: ::/0
        sequence: 10
      name: prefix-list-modify-test-ipv6
  commands:
  - no ip prefix-list VestaSLC-out
  - no ip prefix-list prefix1
  - no ip prefix-list prefix2
  invocation:
    module_args:
      config:
      - afi: ipv6
        prefix_lists:
        - description: null
          entries: null
          name: Ansible-prefix-list-test-ipv6-1
      running_config: null
      state: deleted
```
Read vars_file 'vars/project_standards.yml'

```yaml
- name: Configure ACL
   cisco.ios.ios_acls:
      state: gathered

```

##### EXPECTED RESULTS

Expect the module to delete the specified prefix list

```
commands:
  - no ipv6 prefix-list Ansible-prefix-list-test-ipv6-1
```

##### ACTUAL RESULTS

```paste below
commands:
  - no ip prefix-list VestaSLC-out
  - no ip prefix-list prefix1
  - no ip prefix-list prefix2
  invocation:
    module_args:
      config:
      - afi: ipv6
        prefix_lists:
        - description: null
          entries: null
          name: Ansible-prefix-list-test-ipv6-1
      running_config: null
      state: deleted
```
