### ISSUE TITLE
cisco.ios.ios_snmp - if_index: true, breakes idempotency.

### ISSUE THREAD

**Issue by jorgenspange** [ansible-collections/cisco.ios#948]
##### SUMMARY
When using 
```yaml
if_index: true
```
In cisco.ios.ios_snmp idempotency is broken as this isthe command that is fired:
```yaml
  commands:
  - snmp-server ifindex persist
```

And on Cisco IOS-XE it is displayed like this in show run:
```yaml
snmp ifmib ifindex persist
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_snmp

##### ANSIBLE VERSION
```yaml
[jorgenspange@jorgens-mbp git/ansible-network-automation (main) ]$ ansible --version
ansible [core 2.15.5]
  config file = /Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg
  configured module search path = ['/Users/jorgenspange/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/8.5.0_1/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/jorgenspange/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)] (/opt/homebrew/Cellar/ansible/8.5.0_1/libexec/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```yaml
# /Users/jorgenspange/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  5.1.0

# /opt/homebrew/Cellar/ansible/8.5.0_1/libexec/lib/python3.11/site-packages/ansible_collections
```

##### CONFIGURATION
```yaml
[jorgenspange@jorgens-mbp git/ansible-network-automation (main) ]$ ansible-config dump --only-changed
ANSIBLE_COW_PATH(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = /opt/homebrew/bin/cowsay
ANSIBLE_COW_SELECTION(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = small
ANSIBLE_NOCOWS(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = False
ANSIBLE_PIPELINING(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = True
CONFIG_FILE() = /Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg
DEFAULT_FORKS(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = 10
DEFAULT_GATHERING(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = smart
DEFAULT_HOST_LIST(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = ['/Users/jorgenspange/Documents/git/ansible-network-automation/inventory/S-TEST']
DEFAULT_ROLES_PATH(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = ['/Users/jorgenspange/Documents/git/ansible-network-automation/roles']
DEFAULT_STDOUT_CALLBACK(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = 120
DEFAULT_VAULT_PASSWORD_FILE(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = 
DISPLAY_SKIPPED_HOSTS(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = False
HOST_KEY_CHECKING(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = False
```

##### OS / ENVIRONMENT
HW: Apple M1 Pro 2021
OS: Sonoma 14.0

##### STEPS TO REPRODUCE
```yaml
        hosts:
        - community_string: readonly
          host: 192.168.1.10
        if_index: true
```

**Comment by jorgenspange** [comment]
```yaml
---
- name: Check snmp
  hosts: "{{ target }}"
  gather_facts: false
  tasks:
    - name: Gather snmp cfg.
      cisco.ios.ios_snmp_server:
        state: gathered
      register: snmp_data

    - name: Override device configuration of all acls with provided configuration
      check_mode: true
      cisco.ios.ios_snmp_server:
        config: "{{ snmp_data.gathered }}"
        state: overridden
```

When using state gathered in the module the if_index: true is not gathered.
