### ISSUE TITLE
cisco.ios.ios_user - ssh users breaks idempotency/users are not removed.

### ISSUE THREAD

**Issue by jorgenspange** [ansible-collections/cisco.ios#949]
##### SUMMARY
When purging all users except admin users defined with ssh certs are collected and tried to removed.
This breaks idempotency. The user is not removed, which it probably should not be when using this module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_user

##### ANSIBLE VERSION
```yaml
[jorgenspange@jorgens-mbp git/ansible-network-automation (main) ]$ ansible --version
ansible [core 2.15.5]
  config file = /Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg
  configured module search path = ['/Users/jorgenspange/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/8.5.0_1/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/jorgenspange/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)] (/opt/homebrew/Cellar/ansible/8.5.0_1/libexec/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```yaml
# /Users/jorgenspange/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  5.1.0

# /opt/homebrew/Cellar/ansible/8.5.0_1/libexec/lib/python3.11/site-packages/ansible_collections
```

##### CONFIGURATION
```yaml
[jorgenspange@jorgens-mbp git/ansible-network-automation (main) ]$ ansible-config dump --only-changed
ANSIBLE_COW_PATH(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = /opt/homebrew/bin/cowsay
ANSIBLE_COW_SELECTION(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = small
ANSIBLE_NOCOWS(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = False
ANSIBLE_PIPELINING(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = True
CONFIG_FILE() = /Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg
DEFAULT_FORKS(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = 10
DEFAULT_GATHERING(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = smart
DEFAULT_HOST_LIST(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = ['/Users/jorgenspange/Documents/git/ansible-network-automation/inventory/S-TEST']
DEFAULT_ROLES_PATH(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = ['/Users/jorgenspange/Documents/git/ansible-network-automation/roles']
DEFAULT_STDOUT_CALLBACK(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = 120
DEFAULT_VAULT_PASSWORD_FILE(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = 
DISPLAY_SKIPPED_HOSTS(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = False
HOST_KEY_CHECKING(/Users/jorgenspange/Documents/git/ansible-network-automation/ansible.cfg) = False
```

##### OS / ENVIRONMENT
HW: Apple M1 Pro 2021
OS: Sonoma 14.0

##### STEPS TO REPRODUCE
```yaml
- name: configure_cisco.ios.ios | Purge all users except admin.
  cisco.ios.ios_user:
    aggregate:
    purge: true
```
Here is the output from running that play with -vvv:
```yaml
changed: [Cat9k] => changed=true
  commands:
  - answer: y
    command: no username sshuser
    newline: false
    prompt: This operation will remove all username related configurations with same name
  invocation:
    module_args:
      aggregate: null
      configured_password: null
      hashed_password: null
      name: null
      nopassword: null
      password_type: secret
      privilege: null
      purge: true
      sshkey: null
      state: present
      update_password: always
      view: null
```

On the switch it looks like this:

```bash
ip ssh pubkey-chain
  username sshuser
   key-hash ssh-rsa ...
 ```
 
 I guess the problem is that when you do show run and incl username it looks like this:
 ```bash
 Cat9k#show run | incl username
username admin privilege 15 secret 9 ...
  username sshuser
  ```
