### ISSUE TITLE
cisco.ios.ios_user - existing user with password cannot be updated to use secret

### ISSUE THREAD

**Issue by noziwatele** [ansible-collections/cisco.ios#950]
##### SUMMARY
Using ios_user module to change an existing local user account with a password (type 7) to a secret (type 9) appears to succeed, with changed=true, but the device configuration is not actually updated. When the command is run manually on the switch CLI there is an error that is not caught by the ios_user module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_user

##### ANSIBLE VERSION

```
ansible [core 2.15.0]
  config file = /<path to ansible project>/ansible.cfg
  configured module search path = ['/<user home>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /<user home>/.pyenv/versions/3.11.5/envs/ansible-2.15-py3.11/lib/python3.11/site-packages/ansible
  ansible collection location = /<user home>/.ansible/collections:/usr/share/ansible/collections
  executable location = /<user home>/.pyenv/versions/ansible-2.15-py3.11/bin/ansible
  python version = 3.11.5 (main, Sep 25 2023, 21:05:43) [Clang 14.0.0 (clang-1400.0.29.202)] (/<user home>/.pyenv/versions/3.11.5/envs/ansible-2.15-py3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
# /<user home>/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  5.1.0
```

##### CONFIGURATION

```
CONFIG_FILE() = /<ansible project path>/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(/<ansible project path>/ansible.cfg) = ['/<ansible project path>/plugins/filter']
DEFAULT_FORKS(/<ansible project path>/ansible.cfg) = 20
DEFAULT_GATHERING(/<ansible project path>/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/<ansible project path>/ansible.cfg) = ['/<ansible project path>/ipam-inventory.yml']
DEFAULT_LOG_PATH(/<ansible project path>/ansible.cfg) = /<ansible project path>/log/ansible.log
DEFAULT_ROLES_PATH(/<ansible project path>/ansible.cfg) = ['/<ansible project path>/roles']
DEFAULT_STDOUT_CALLBACK(/<ansible project path>/ansible.cfg) = yaml
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
INTERPRETER_PYTHON(env: ANSIBLE_PYTHON_INTERPRETER) = /<user home>/.pyenv/shims/python
INVENTORY_ENABLED(/<ansible project path>/ansible.cfg) = ['infoblox.nios_modules.nios_inventory']
PERSISTENT_COMMAND_TIMEOUT(/<ansible project path>/ansible.cfg) = 60
RETRY_FILES_ENABLED(/<ansible project path>/ansible.cfg) = False
TRANSFORM_INVALID_GROUP_CHARS(/<ansible project path>/ansible.cfg) = never
```

##### OS / ENVIRONMENT
Ansible control node: Macos 12.6.8
Target node: Cisco Catalyst 9500-32C, IOS-XE 17.6.4

##### STEPS TO REPRODUCE

The running-config already contains a local user with the username that I am trying to update, like this:

```
username existing_user privilege 15 password 7 548398DHGDBD096536955469042490EVD
```

Then run this play to change the user's password 7 to a secret 9:

```
- name: "Update local users on Cisco network devices"
  hosts: all
  connection: network_cli
  tasks:
    - name: "1 - Update existing user"
      cisco.ios.ios_user:
        name: existing_user
        hashed_password: 
          type: 9
          value: "{{ type9_secret }}"
        privilege: 15
        state: present
        purge: true
```

##### EXPECTED RESULTS

Either:

1. (preferred option) existing username config line above is replaced with:
```
username existing_user privilege 15 secret 9 $Vw52YVfCdeyYUCEje44Oc.$itjjpp2yYCqEpTmLSQwCiY9$sm5N2ybExBzMg
```

OR:

2. module errors out informing me that it can't update an existing user.

##### ACTUAL RESULTS

The task completes successfully with changed=true.

```
changed: [<switch hostname>] => changed=true
  commands:
  - username existing_user secret ******** $********$Vw52YVfCdeyYUCEje44Oc.$itjjpp2yYCqEpTmLSQwCiY9$sm5N2ybExBzMg
  invocation:
    module_args:
      aggregate: null
      configured_password: null
      hashed_password:
        type: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        value: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      name: existing_user
      nopassword: null
      password_type: secret
      privilege: 15
      purge: true
      sshkey: null
      state: present
      update_password: always
      view: null
```

Note this is a copy/paste of the output, the command output is not correctly obfuscated, as per issue #559.
