### ISSUE TITLE
Issue with IOS_ACLS writing new ACLs (cisco.ios  5.2.0 )

### ISSUE THREAD

**Issue by JKemp617** [ansible-collections/cisco.ios#959]
##### SUMMARY

I am trying to use the ios_acls module to create new ACLs on Cisco switches, I've attempted it two different ways, and received two different errors.  Code Snips and Errors Follow:
1)
   
```
-  name: Create SNMPv3-ACL
           cisco.ios.ios_acls:
              config:
                 - afi: ipv4
                   acls:
                      - name: SNMPv3-ACL
                        acl_type: extended
                        aces:
                           - grant: permit
                             protocol_options:
                                ip:
                                   fin: true
                             source:
                                host: 10.107.36.33
                           - grant: permit
                             protocol_options:
                                ip:
                                   fin: true
                             source:
                                host: 10.101.36.23
                           - grant: permit
                             protocol_options:
                                ip:
                                   fin: true
                             source:
                                host: 10.111.36.25
                           - grant: permit
                             protocol_options:
                                ip:
                                   fin: true
                             source:
                                host: 10.129.36.55
                           - grant: permit
                             protocol_options:
                                ip:
                                   fin: true
                             source:
                                host: 10.121.37.15
                           - grant: permit
                             protocol_options:
                                ip:
                                   fin: true
                             source:
                                address: 10.127.36.16
              state: merged
```
ERROR: "msg": "argument 'ip' is of type <class 'dict'> found in 'config -> acls -> aces -> protocol_options'. and we were unable to convert to bool: <class 'dict'> cannot be converted to a bool"

```
2)
        -  name: Create SNMPv3-ACL
           cisco.ios.ios_acls:
              config:
                 - afi: ipv4
                   acls:
                      - name: SNMPv3-ACL
                        acl_type: standard
                        aces:
                           - grant: permit
                             source:
                                host: 10.107.36.33
                           - grant: permit
                             source:
                                host: 10.101.36.23
                           - grant: permit
                             source:
                                host: 10.111.36.25
                           - grant: permit
                             source:
                                host: 10.129.36.55
                           - grant: permit
                             source:
                                host: 10.121.37.15
                           - grant: permit
                             source:
                                address: 10.127.36.16
              state: merged
```

ERROR: "msg": "Unsupported attribute for standard ACL - protocol_options."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_acls

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Sep 14 2023, 10:46:13) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/ansible/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 5.3.0  
ansible.utils     2.11.0 
cisco.ios         5.2.0  
cisco.nxos        5.2.1 
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
        -  name: Create SNMPv3-ACL
           cisco.ios.ios_acls:
              config:
                 - afi: ipv4
                   acls:
                      - name: SNMPv3-ACL
                        acl_type: extended
                        aces:
                           - grant: permit
                             sequence: 10
                             protocol_options:
                                ip: true
                             source:
                                host: 10.101.36.23
                             destination:
                                any: true
                           - grant: permit
                             sequence: 20
                             protocol_options:
                                ip: true
                             source:
                                host: 10.107.36.33
                             destination:
                                any: true
                           - grant: permit
                             sequence: 30
                             protocol_options:
                                ip: true
                             source:
                                host: 10.111.36.25
                             destination:
                                any: true
                           - grant: permit
                             sequence: 40
                             protocol_options:
                                ip: true
                             source:
                                host=10.129.36.55
                           - grant: permit
                             sequence: 50
                             protocol_options:
                                ip: true
                             source:
                                host: 10.121.37.15
                             destination:
                                any: true
                           - grant: permit
                             sequence: 60
                             protocol_options:
                                ip: true
                             source:
                                address: 10.127.36.16
                             destination:
                                any: true
              state: merged

```

##### EXPECTED RESULTS

I would expect the ACL to be created like this:
```
ip access-list extended SNMPv3-ACL 
10 permit ip host 10.101.36.23 any
20 permit ip host 10.107.36.33 any
30 permit ip host 10.111.36.25 any
40 permit ip host 10.121.37.15 any
50 permit ip host 10.127.36.16 any
60 permit ip host 10.129.36.55 any
```

##### ACTUAL RESULTS

```
TASK [Create SNMPv3-ACL] **********************************************************************************************************************************
fatal: [has1-n-sw45a.XXX.com]: FAILED! => {"changed": false, "msg": "Unsupported attribute for standard ACL - protocol_options."}
```

```paste below

```

**Comment by KB-perByte** [comment]
Hey @JKemp617 could you please help us with the running config data `show running-config | section access-list`
It would help us narrow down the debugging.

Regards

**Comment by JKemp617** [comment]
I will, but at this point the playbook hasn't actually written anything to the switch.  Here is the entire playbook as written, I had run it with --check and -vvv options

```

---

-  name: IOS SNMPv3 Deployment
   connection: network_cli
   gather_facts: false
   hosts: has1-n-sw45a.XXX.com
   vars_files:
    - ~/vars/Network_Vault.yml
   tasks:

        -  name: Get config for IOS devices
           ios_facts:
              gather_subset: config

        -  name: Backup device
           ios_config:
              backup: yes

        -  name: Create SNMPv3-ACL
           cisco.ios.ios_acls:
              config:
                 - afi: ipv4
                   acls:
                      - name: SNMPv3-ACL
                        acl_type: extended
                        aces:
                           - grant: permit
                             protocol_options:
                                ip:
                                   fin: true
                             source:
                                host: 10.107.36.33
                           - grant: permit
                             protocol_options:
                                ip:
                                   fin: true
                             source:
                                host: 10.101.36.23
                           - grant: permit
                             protocol_options:
                                ip:
                                   fin: true
                             source:
                                host: 10.111.36.25
                           - grant: permit
                             protocol_options:
                                ip:
                                   fin: true
                             source:
                                host: 10.129.36.55
                           - grant: permit
                             protocol_options:
                                ip:
                                   fin: true
                             source:
                                host: 10.121.37.15
                           - grant: permit
                             protocol_options:
                                ip:
                                   fin: true
                             source:
                                address: 10.127.36.16
              state: merged

        -  name: Configure SNMP User
           cisco.ios.ios_snmp_server:
              config:
                 groups:
                    - group: SNMPv3-RO
                      version: v3
                      version_option: auth
                      read: SNMPv3-ACL
                 users:
                    - acl_v4: SNMPv3-ACL
                      group: SNMPv3-RO
                      username:  "{{ snmpv3_user }}"
                      authentication:
                         algorithm: sha
                         password:  "{{ snmpv3_password }}"
                      encryption:
                         priv: des
                         password:  "{{ snmpv3_password }}"
                      version: v3
              state: merged

        -  name: Save running to startup when modified
           ios_config:
              save_when: modified
```

ERROR:

```
TASK [Create SNMPv3-ACL] **********************************************************************************************************************************
task path: /home/ansible/playbooks/SNMPv3_IOS_Deployment.yml:21
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
redirecting (type: become) ansible.builtin.enable to ansible.netcommon.enable
redirecting (type: action) cisco.ios.ios_acls to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_acls to cisco.ios.ios
fatal: [has1-n-sw45a.XXX.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "acls": [
                        {
                            "aces": [
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "enable_fragments": null,
                                    "evaluate": null,
                                    "fragments": null,
                                    "grant": "permit",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": {
                                        "ahp": null,
                                        "eigrp": null,
                                        "esp": null,
                                        "gre": null,
                                        "hbh": null,
                                        "icmp": null,
                                        "igmp": null,
                                        "ip": {
                                            "fin": true
                                        },
                                        "ipinip": null,
                                        "ipv6": null,
                                        "nos": null,
                                        "ospf": null,
                                        "pcp": null,
                                        "pim": null,
                                        "protocol_number": null,
                                        "sctp": null,
                                        "tcp": null,
                                        "udp": null
                                    },
                                    "remarks": null,
                                    "sequence": null,
                                    "source": {
                                        "address": null,
                                        "any": null,
                                        "host": "10.107.36.33",
                                        "object_group": null,
                                        "port_protocol": null,
                                        "wildcard_bits": null
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                },
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "enable_fragments": null,
                                    "evaluate": null,
                                    "fragments": null,
                                    "grant": "permit",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": {
                                        "ahp": null,
                                        "eigrp": null,
                                        "esp": null,
                                        "gre": null,
                                        "hbh": null,
                                        "icmp": null,
                                        "igmp": null,
                                        "ip": {
                                            "fin": true
                                        },
                                        "ipinip": null,
                                        "ipv6": null,
                                        "nos": null,
                                        "ospf": null,
                                        "pcp": null,
                                        "pim": null,
                                        "protocol_number": null,
                                        "sctp": null,
                                        "tcp": null,
                                        "udp": null
                                    },
                                    "remarks": null,
                                    "sequence": null,
                                    "source": {
                                        "address": null,
                                        "any": null,
                                        "host": "10.101.36.23",
                                        "object_group": null,
                                        "port_protocol": null,
                                        "wildcard_bits": null
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                },
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "enable_fragments": null,
                                    "evaluate": null,
                                    "fragments": null,
                                    "grant": "permit",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": {
                                        "ahp": null,
                                        "eigrp": null,
                                        "esp": null,
                                        "gre": null,
                                        "hbh": null,
                                        "icmp": null,
                                        "igmp": null,
                                        "ip": {
                                            "fin": true
                                        },
                                        "ipinip": null,
                                        "ipv6": null,
                                        "nos": null,
                                        "ospf": null,
                                        "pcp": null,
                                        "pim": null,
                                        "protocol_number": null,
                                        "sctp": null,
                                        "tcp": null,
                                        "udp": null
                                    },
                                    "remarks": null,
                                    "sequence": null,
                                    "source": {
                                        "address": null,
                                        "any": null,
                                        "host": "10.111.36.25",
                                        "object_group": null,
                                        "port_protocol": null,
                                        "wildcard_bits": null
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                },
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "enable_fragments": null,
                                    "evaluate": null,
                                    "fragments": null,
                                    "grant": "permit",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": {
                                        "ahp": null,
                                        "eigrp": null,
                                        "esp": null,
                                        "gre": null,
                                        "hbh": null,
                                        "icmp": null,
                                        "igmp": null,
                                        "ip": {
                                            "fin": true
                                        },
                                        "ipinip": null,
                                        "ipv6": null,
                                        "nos": null,
                                        "ospf": null,
                                        "pcp": null,
                                        "pim": null,
                                        "protocol_number": null,
                                        "sctp": null,
                                        "tcp": null,
                                        "udp": null
                                    },
                                    "remarks": null,
                                    "sequence": null,
                                    "source": {
                                        "address": null,
                                        "any": null,
                                        "host": "10.129.36.55",
                                        "object_group": null,
                                        "port_protocol": null,
                                        "wildcard_bits": null
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                },
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "enable_fragments": null,
                                    "evaluate": null,
                                    "fragments": null,
                                    "grant": "permit",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": {
                                        "ahp": null,
                                        "eigrp": null,
                                        "esp": null,
                                        "gre": null,
                                        "hbh": null,
                                        "icmp": null,
                                        "igmp": null,
                                        "ip": {
                                            "fin": true
                                        },
                                        "ipinip": null,
                                        "ipv6": null,
                                        "nos": null,
                                        "ospf": null,
                                        "pcp": null,
                                        "pim": null,
                                        "protocol_number": null,
                                        "sctp": null,
                                        "tcp": null,
                                        "udp": null
                                    },
                                    "remarks": null,
                                    "sequence": null,
                                    "source": {
                                        "address": null,
                                        "any": null,
                                        "host": "10.121.37.15",
                                        "object_group": null,
                                        "port_protocol": null,
                                        "wildcard_bits": null
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                },
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "enable_fragments": null,
                                    "evaluate": null,
                                    "fragments": null,
                                    "grant": "permit",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": {
                                        "ahp": null,
                                        "eigrp": null,
                                        "esp": null,
                                        "gre": null,
                                        "hbh": null,
                                        "icmp": null,
                                        "igmp": null,
                                        "ip": {
                                            "fin": true
                                        },
                                        "ipinip": null,
                                        "ipv6": null,
                                        "nos": null,
                                        "ospf": null,
                                        "pcp": null,
                                        "pim": null,
                                        "protocol_number": null,
                                        "sctp": null,
                                        "tcp": null,
                                        "udp": null
                                    },
                                    "remarks": null,
                                    "sequence": null,
                                    "source": {
                                        "address": "10.127.36.16",
                                        "any": null,
                                        "host": null,
                                        "object_group": null,
                                        "port_protocol": null,
                                        "wildcard_bits": null
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                }
                            ],
                            "acl_type": "extended",
                            "name": "SNMPv3-ACL"
                        }
                    ],
                    "afi": "ipv4"
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    },
    "msg": "argument 'ip' is of type <class 'dict'> found in 'config -> acls -> aces -> protocol_options'. and we were unable to convert to bool: <class 'dict'> cannot be converted to a bool"
}
```

**Comment by JKemp617** [comment]
For what it is worth, running without the --check and -vvv options ends in the same error, as expected.

**Comment by JKemp617** [comment]
So someone on Reddit pointed out that I was trying to call the protocol option wrong, so I did make a change, and it did have a different result, but it still doesn't work.  I also tried with "ip: true" and ip=true", no differance.

Here is what changed:

```
                      - name: SNMPv3-ACL
                        acl_type: extended
                        aces:
                           - grant: permit
                             sequence: 10
                             protocol_options:
                                ip: true
                             source:
                                host: 10.101.36.23
                           - grant: permit
                             sequence: 20
                             protocol_options:
                                ip: true
                             source:
                                host: 10.107.36.33
                           - grant: permit
                             sequence: 30
                             protocol_options:
                                ip: true
                             source:
                                host: 10.111.36.25
                           - grant: permit
                             sequence: 40
                             protocol_options:
                                ip: true
                             source:
                                host=10.129.36.55
                           - grant: permit
                             sequence: 50
                             protocol_options:
                                ip: true
                             source:
                                host: 10.121.37.15
                           - grant: permit
                             sequence: 60
                             protocol_options:
                                ip: true
                             source:
                                address: 10.127.36.16
```

and the new error
```
FAILED! => {"changed": false, "msg": "Unsupported attribute for standard ACL - protocol_options."}
```

The error is interesting because this is calling "acl_type: extended" not standard.
Thanks

**Comment by JKemp617** [comment]
Just one more thing here, I replaced all my script with the first entry from the Examples, and I still get the same error.
```

---

-  name: ACL Test
   connection: network_cli
   gather_facts: false
   hosts: has1-n-sw45a.XXX.com
   vars_files:
    - ~/vars/Network_Vault.yml
   tasks:

        -  name: Get config for IOS devices
           ios_facts:
              gather_subset: config

        -  name: Backup device
           ios_config:
              backup: yes

        - name: Merge provided configuration with device configuration
          cisco.ios.ios_acls:
              config:
                 - afi: ipv4
                   acls:
                      - name: 100
                        aces:
                           - sequence: 10
                             protocol_options:
                                icmp:
                                   traceroute: true
              state: merged
```

ERROR

```
redirecting (type: action) cisco.ios.ios_acls to cisco.ios.ios
fatal: [has1-n-sw45a.XXX.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "acls": [
                        {
                            "aces": [
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "enable_fragments": null,
                                    "evaluate": null,
                                    "fragments": null,
                                    "grant": null,
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": {
                                        "ahp": null,
                                        "eigrp": null,
                                        "esp": null,
                                        "gre": null,
                                        "hbh": null,
                                        "icmp": {
                                            "administratively_prohibited": null,
                                            "alternate_address": null,
                                            "conversion_error": null,
                                            "dod_host_prohibited": null,
                                            "dod_net_prohibited": null,
                                            "echo": null,
                                            "echo_reply": null,
                                            "general_parameter_problem": null,
                                            "host_isolated": null,
                                            "host_precedence_unreachable": null,
                                            "host_redirect": null,
                                            "host_tos_redirect": null,
                                            "host_tos_unreachable": null,
                                            "host_unknown": null,
                                            "host_unreachable": null,
                                            "information_reply": null,
                                            "information_request": null,
                                            "mask_reply": null,
                                            "mask_request": null,
                                            "mobile_redirect": null,
                                            "net_redirect": null,
                                            "net_tos_redirect": null,
                                            "net_tos_unreachable": null,
                                            "net_unreachable": null,
                                            "network_unknown": null,
                                            "no_room_for_option": null,
                                            "option_missing": null,
                                            "packet_too_big": null,
                                            "parameter_problem": null,
                                            "port_unreachable": null,
                                            "precedence_unreachable": null,
                                            "protocol_unreachable": null,
                                            "reassembly_timeout": null,
                                            "redirect": null,
                                            "router_advertisement": null,
                                            "router_solicitation": null,
                                            "source_quench": null,
                                            "source_route_failed": null,
                                            "time_exceeded": null,
                                            "timestamp_reply": null,
                                            "timestamp_request": null,
                                            "traceroute": true,
                                            "ttl_exceeded": null,
                                            "unreachable": null
                                        },
                                        "igmp": null,
                                        "ip": null,
                                        "ipinip": null,
                                        "ipv6": null,
                                        "nos": null,
                                        "ospf": null,
                                        "pcp": null,
                                        "pim": null,
                                        "protocol_number": null,
                                        "sctp": null,
                                        "tcp": null,
                                        "udp": null
                                    },
                                    "remarks": null,
                                    "sequence": 10,
                                    "source": null,
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                }
                            ],
                            "acl_type": null,
                            "name": "100"
                        }
                    ],
                    "afi": "ipv4"
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    },
    "msg": "Unsupported attribute for standard ACL - protocol_options."
}

PLAY RECAP ************************************************************************************************************************************************
has1-n-sw45a.XXX.com  : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
