### ISSUE TITLE
 issue on cisco.ios.ios_user

### ISSUE THREAD

**Issue by Chorinzo** [ansible-collections/cisco.ios#966]
##### SUMMARY
When i'am using the collection : cisco.ios.ios_user to create user on a WS-C2960X-48LPS-L version 15.2(7)E4, it didin't work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
**cisco.ios.ios_user** in **cisco.ios** (**version 4.6.1**)

##### ANSIBLE VERSION

```
ansible-playbook [core 2.11.12]
config file = /home/semaphore/playbook/repository_13_52/ansible.cfg
configured module search path = ['/home/semaphore/playbook/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /home/mmgbastion/venv/lib64/python3.6/site-packages/ansible
ansible collection location = /home/semaphore/playbook/.ansible/collections:/usr/share/ansible/collections
executable location = /home/mmgbastion/venv/bin/ansible-playbook
python version = 3.6.8 (default, Oct 2 2023, 21:12:58) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)]
jinja version = 3.0.3
libyaml = True
```

##### COLLECTION VERSION
cisco.ios.ios_user in cisco.ios (version 4.6.1).

##### OS / ENVIRONMENT
Tested on  Cisco WS-C2960CX-8TC-L en version 15.2(4)E6 : OK
Tested on Cisco C1000-16P-2G-L en version 15.2(7)E6 : OK
Tested on Cisco C9200L-48P-4G en version 17.09.04a : OK

Tested on  WS-C2960X-48LPS-L en version 15.2(7)E4 : **KO**

##### STEPS TO REPRODUCE

My Playbook :
```
---
- name: "User creation test"
  hosts: MYFRNSPaUATEur01
  gather_facts: false

   vars:
     ansible_user: "login"
     ansible_password: "password"
     ansible_become_password: "password"
     ansible_become: true
     ansible_become_method: enable
     ansible_network_os: cisco.ios.ios

  tasks:
  - name: User creation test : admin-test
    cisco.ios.ios_user:
      name: admin-test
      privilege: 15
      password_type: secret
      configured_password: password      
```

##### EXPECTED RESULTS
The collection create the user.

##### ACTUAL RESULTS

```
fatal: [MYFRNSPaUATEur01]: FAILED! => {
"changed": false,
"invocation": {
"module_args": {
"aggregate": null,
"configured_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
"hashed_password": null,
"name": "admin-test",
"nopassword": null,
"password_type": "secret",
"privilege": 15,
"purge": false,
"sshkey": null,
"state": "present",
"update_password": "always",
"view": null
}
},
"msg": "username admin-test privilege 15\r\nusername admin-test privilege 15\r\n% Incomplete command.\r\n\r\nMYFRNSPaUATEur01(config)#"
}
```
